import Goldbach.Cert.MajorArcModules.Q0MajorTailTTStarStep5LXBound
#check Goldbach.Cert.MajorArcModules.Q0MajorTailTTStarStep5LXBound.LXMeanSquareUpperCore
#check Goldbach.Cert.MajorArcModules.Q0MajorTailTTStarStep5LXBound.divGcdSum
