import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBridge
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup000
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039
import Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverageX0PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.constructorNameAsVariable false

namespace Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverage

open Goldbach
open Goldbach.BankParams
open Goldbach.Windows

/- Generated row-local final actual-sum theorem from grouped record modules. -/

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup000Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo000 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup000Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo000 := by
  simpa [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000, PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo000] using periodicMainNonzeroWithoutRowFiveDyadicBaseGroup000_actual_sum

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo001 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo000 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo001 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup001Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo000_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup001_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo002 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo001 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo002 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup002Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo001_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup002_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo003 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo002 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo003 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup003Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo002_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup003_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo004 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo003 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo004 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup004Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo003_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup004_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo005 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo004 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo005 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup005Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo004_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup005_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo006 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo005 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo006 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup006Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo005_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup006_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo007 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo006 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo007 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup007Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo006_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup007_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo008 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo007 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo008 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup008Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo007_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup008_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo009 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo008 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo009 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup009Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo008_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup009_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo010 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo009 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo010 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup010Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo009_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup010_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo011 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo010 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo011 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup011Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo010_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup011_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo012 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo011 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo012 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup012Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo011_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup012_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo013 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo012 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo013 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup013Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo012_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup013_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo014 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo013 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo014 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup014Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo013_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup014_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo015 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo014 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo015 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup015Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo014_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup015_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo016 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo015 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo016 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup016Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo015_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup016_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo017 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo016 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo017 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup017Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo016_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup017_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo018 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo017 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo018 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup018Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo017_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup018_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo019 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo018 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo019 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup019Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo018_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup019_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo020 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo019 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo020 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup020Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo019_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup020_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo021 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo020 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo021 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup021Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo020_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup021_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo022 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo021 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo022 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup022Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo021_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup022_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo023 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo022 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo023 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup023Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo022_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup023_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo024 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo023 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo024 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup024Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo023_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup024_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo025 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo024 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo025 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup025Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo024_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup025_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo026 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo025 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo026 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup026Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo025_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup026_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo027 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo026 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo027 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup027Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo026_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup027_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo028 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo027 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo028 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup028Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo027_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup028_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo029 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo028 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo029 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup029Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo028_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup029_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo030 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo029 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo030 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup030Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo029_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup030_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo031 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo030 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo031 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup031Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo030_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup031_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo032 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo031 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo032 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup032Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo031_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup032_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo033 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo032 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo033 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup033Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo032_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup033_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo034 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo033 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo034 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup034Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo033_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup034_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo035 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo034 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo035 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup035Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo034_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup035_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo036 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo035 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo036 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup036Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo035_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup036_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo037 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo036 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo037 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup037Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo036_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup037_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo038 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo037 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo038 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup038Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo037_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup038_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo039 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo038 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo039 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup039Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo038_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup039_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040 : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039 ∪ PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040Pairs

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo040 : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo039 + PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040Total

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040Pairs :
    Disjoint PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039 PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040Pairs := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo040 := by
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040, Finset.sum_union PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039_disjoint_PeriodicMainNonzeroWithoutRowFiveDyadicBaseGroup040Pairs]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo039_actual_sum, periodicMainNonzeroWithoutRowFiveDyadicBaseGroup040_actual_sum]
  rfl

def PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs : Finset (ℕ × ℕ) :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040

def PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotal : ℚ :=
  PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotalUpTo040

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs_eq_target :
    PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs = PeriodicMainNonzeroRecordPairsWithoutRowFiveDyadic := by
  native_decide

theorem PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotal := by
  simpa [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs, PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotal] using PeriodicMainNonzeroWithoutRowFiveDyadicBasePairsUpTo040_actual_sum

theorem periodicMainNonzeroRecordPairsWithoutRowFiveDyadic_actual_sum :
    (∑ p ∈ PeriodicMainNonzeroRecordPairsWithoutRowFiveDyadic, surrogatePeriodicMainActiveOrderedPairSummandRat X0 p) = PeriodicMainNonzeroWithoutRowFiveDyadicBaseTotal := by
  rw [← PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs_eq_target]
  rw [PeriodicMainNonzeroWithoutRowFiveDyadicBasePairs_actual_sum]

end Goldbach.Cert.MajorArcModules.Q0MinorZeroModeNormalizedAverage
