/-
AUTOGENERATED (soundness mode): Chunk [584524..584760]
    Source: chunk_058.json  •  SHA256(JSON): 909df3fccd4e1574a38d9bbcae1ca46c11dc45fdb55a5ee286c2bcfd1ff30a78
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk058_t_verified

noncomputable section

def nLo : Nat := 584524
def nHi : Nat := 584760
def dataSHA256 : String := "909df3fccd4e1574a38d9bbcae1ca46c11dc45fdb55a5ee286c2bcfd1ff30a78"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (584524, (53, 584471)),
    (584526, (17, 584509)),
    (584528, (19, 584509)),
    (584530, (59, 584471)),
    (584532, (23, 584509)),
    (584534, (3, 584531)),
    (584536, (5, 584531)),
    (584538, (7, 584531)),
    (584540, (31, 584509)),
    (584542, (11, 584531)),
    (584544, (13, 584531)),
    (584546, (37, 584509)),
    (584548, (17, 584531)),
    (584550, (19, 584531)),
    (584552, (43, 584509)),
    (584554, (23, 584531)),
    (584556, (47, 584509)),
    (584558, (181, 584377)),
    (584560, (3, 584557)),
    (584562, (5, 584557)),
    (584564, (3, 584561)),
    (584566, (5, 584561)),
    (584568, (7, 584561)),
    (584570, (13, 584557)),
    (584572, (11, 584561)),
    (584574, (13, 584561)),
    (584576, (19, 584557)),
    (584578, (17, 584561)),
    (584580, (19, 584561)),
    (584582, (73, 584509)),
    (584584, (23, 584561)),
    (584586, (29, 584557)),
    (584588, (31, 584557)),
    (584590, (3, 584587)),
    (584592, (5, 584587)),
    (584594, (7, 584587)),
    (584596, (3, 584593)),
    (584598, (5, 584593)),
    (584600, (7, 584593)),
    (584602, (3, 584599)),
    (584604, (5, 584599)),
    (584606, (3, 584603)),
    (584608, (5, 584603)),
    (584610, (7, 584603)),
    (584612, (3, 584609)),
    (584614, (5, 584609)),
    (584616, (7, 584609)),
    (584618, (19, 584599)),
    (584620, (11, 584609)),
    (584622, (13, 584609)),
    (584624, (3, 584621)),
    (584626, (5, 584621)),
    (584628, (7, 584621)),
    (584630, (3, 584627)),
    (584632, (5, 584627)),
    (584634, (7, 584627)),
    (584636, (37, 584599)),
    (584638, (11, 584627)),
    (584640, (13, 584627)),
    (584642, (43, 584599)),
    (584644, (17, 584627)),
    (584646, (19, 584627)),
    (584648, (61, 584587)),
    (584650, (23, 584627)),
    (584652, (31, 584621)),
    (584654, (61, 584593)),
    (584656, (29, 584627)),
    (584658, (31, 584627)),
    (584660, (61, 584599)),
    (584662, (3, 584659)),
    (584664, (5, 584659)),
    (584666, (3, 584663)),
    (584668, (5, 584663)),
    (584670, (7, 584663)),
    (584672, (13, 584659)),
    (584674, (11, 584663)),
    (584676, (13, 584663)),
    (584678, (19, 584659)),
    (584680, (3, 584677)),
    (584682, (5, 584677)),
    (584684, (7, 584677)),
    (584686, (23, 584663)),
    (584688, (11, 584677)),
    (584690, (13, 584677)),
    (584692, (29, 584663)),
    (584694, (17, 584677)),
    (584696, (3, 584693)),
    (584698, (5, 584693)),
    (584700, (7, 584693)),
    (584702, (3, 584699)),
    (584704, (5, 584699)),
    (584706, (7, 584699)),
    (584708, (31, 584677)),
    (584710, (3, 584707)),
    (584712, (5, 584707)),
    (584714, (7, 584707)),
    (584716, (3, 584713)),
    (584718, (5, 584713)),
    (584720, (7, 584713)),
    (584722, (3, 584719)),
    (584724, (5, 584719)),
    (584726, (3, 584723)),
    (584728, (5, 584723)),
    (584730, (7, 584723)),
    (584732, (13, 584719)),
    (584734, (11, 584723)),
    (584736, (13, 584723)),
    (584738, (19, 584719)),
    (584740, (3, 584737)),
    (584742, (5, 584737)),
    (584744, (7, 584737)),
    (584746, (23, 584723)),
    (584748, (11, 584737)),
    (584750, (13, 584737)),
    (584752, (29, 584723)),
    (584754, (17, 584737)),
    (584756, (19, 584737)),
    (584758, (59, 584699)),
    (584760, (23, 584737))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk058_t_verified
