/-
AUTOGENERATED (soundness mode): Chunk [458808..459044]
    Source: chunk_045.json  •  SHA256(JSON): 45895201285133936bb4eabb82ea94088232b83a3341bf06a044322a07560dcf
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk045_al_verified

noncomputable section

def nLo : Nat := 458808
def nHi : Nat := 459044
def dataSHA256 : String := "45895201285133936bb4eabb82ea94088232b83a3341bf06a044322a07560dcf"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (458808, (11, 458797)),
    (458810, (3, 458807)),
    (458812, (5, 458807)),
    (458814, (7, 458807)),
    (458816, (19, 458797)),
    (458818, (11, 458807)),
    (458820, (13, 458807)),
    (458822, (3, 458819)),
    (458824, (5, 458819)),
    (458826, (7, 458819)),
    (458828, (31, 458797)),
    (458830, (11, 458819)),
    (458832, (13, 458819)),
    (458834, (37, 458797)),
    (458836, (17, 458819)),
    (458838, (19, 458819)),
    (458840, (43, 458797)),
    (458842, (23, 458819)),
    (458844, (37, 458807)),
    (458846, (127, 458719)),
    (458848, (29, 458819)),
    (458850, (31, 458819)),
    (458852, (3, 458849)),
    (458854, (5, 458849)),
    (458856, (7, 458849)),
    (458858, (61, 458797)),
    (458860, (11, 458849)),
    (458862, (13, 458849)),
    (458864, (67, 458797)),
    (458866, (3, 458863)),
    (458868, (5, 458863)),
    (458870, (7, 458863)),
    (458872, (23, 458849)),
    (458874, (11, 458863)),
    (458876, (13, 458863)),
    (458878, (29, 458849)),
    (458880, (17, 458863)),
    (458882, (3, 458879)),
    (458884, (5, 458879)),
    (458886, (7, 458879)),
    (458888, (97, 458791)),
    (458890, (11, 458879)),
    (458892, (13, 458879)),
    (458894, (3, 458891)),
    (458896, (5, 458891)),
    (458898, (7, 458891)),
    (458900, (3, 458897)),
    (458902, (5, 458897)),
    (458904, (7, 458897)),
    (458906, (43, 458863)),
    (458908, (11, 458897)),
    (458910, (13, 458897)),
    (458912, (193, 458719)),
    (458914, (17, 458897)),
    (458916, (19, 458897)),
    (458918, (127, 458791)),
    (458920, (3, 458917)),
    (458922, (5, 458917)),
    (458924, (3, 458921)),
    (458926, (5, 458921)),
    (458928, (7, 458921)),
    (458930, (13, 458917)),
    (458932, (3, 458929)),
    (458934, (5, 458929)),
    (458936, (7, 458929)),
    (458938, (17, 458921)),
    (458940, (11, 458929)),
    (458942, (13, 458929)),
    (458944, (23, 458921)),
    (458946, (17, 458929)),
    (458948, (19, 458929)),
    (458950, (3, 458947)),
    (458952, (5, 458947)),
    (458954, (7, 458947)),
    (458956, (59, 458897)),
    (458958, (11, 458947)),
    (458960, (3, 458957)),
    (458962, (3, 458959)),
    (458964, (5, 458959)),
    (458966, (3, 458963)),
    (458968, (5, 458963)),
    (458970, (7, 458963)),
    (458972, (13, 458959)),
    (458974, (3, 458971)),
    (458976, (5, 458971)),
    (458978, (7, 458971)),
    (458980, (3, 458977)),
    (458982, (5, 458977)),
    (458984, (3, 458981)),
    (458986, (5, 458981)),
    (458988, (7, 458981)),
    (458990, (3, 458987)),
    (458992, (5, 458987)),
    (458994, (7, 458987)),
    (458996, (3, 458993)),
    (458998, (5, 458993)),
    (459000, (7, 458993)),
    (459002, (31, 458971)),
    (459004, (11, 458993)),
    (459006, (13, 458993)),
    (459008, (31, 458977)),
    (459010, (3, 459007)),
    (459012, (5, 459007)),
    (459014, (7, 459007)),
    (459016, (3, 459013)),
    (459018, (5, 459013)),
    (459020, (7, 459013)),
    (459022, (29, 458993)),
    (459024, (11, 459013)),
    (459026, (3, 459023)),
    (459028, (5, 459023)),
    (459030, (7, 459023)),
    (459032, (3, 459029)),
    (459034, (3, 459031)),
    (459036, (5, 459031)),
    (459038, (7, 459031)),
    (459040, (3, 459037)),
    (459042, (5, 459037)),
    (459044, (7, 459037))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk045_al_verified
