/-
AUTOGENERATED (soundness mode): Chunk [438808..439044]
    Source: chunk_043.json  •  SHA256(JSON): ac93a42340d290fa24f788f082e6140707c39c10a6f603b7b364191ef7b643fb
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk043_al_verified

noncomputable section

def nLo : Nat := 438808
def nHi : Nat := 439044
def dataSHA256 : String := "ac93a42340d290fa24f788f082e6140707c39c10a6f603b7b364191ef7b643fb"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (438808, (47, 438761)),
    (438810, (17, 438793)),
    (438812, (19, 438793)),
    (438814, (53, 438761)),
    (438816, (23, 438793)),
    (438818, (97, 438721)),
    (438820, (59, 438761)),
    (438822, (29, 438793)),
    (438824, (31, 438793)),
    (438826, (257, 438569)),
    (438828, (59, 438769)),
    (438830, (3, 438827)),
    (438832, (3, 438829)),
    (438834, (5, 438829)),
    (438836, (3, 438833)),
    (438838, (5, 438833)),
    (438840, (7, 438833)),
    (438842, (13, 438829)),
    (438844, (11, 438833)),
    (438846, (13, 438833)),
    (438848, (19, 438829)),
    (438850, (3, 438847)),
    (438852, (5, 438847)),
    (438854, (7, 438847)),
    (438856, (3, 438853)),
    (438858, (5, 438853)),
    (438860, (7, 438853)),
    (438862, (29, 438833)),
    (438864, (11, 438853)),
    (438866, (13, 438853)),
    (438868, (41, 438827)),
    (438870, (17, 438853)),
    (438872, (3, 438869)),
    (438874, (5, 438869)),
    (438876, (7, 438869)),
    (438878, (31, 438847)),
    (438880, (3, 438877)),
    (438882, (5, 438877)),
    (438884, (7, 438877)),
    (438886, (17, 438869)),
    (438888, (11, 438877)),
    (438890, (3, 438887)),
    (438892, (5, 438887)),
    (438894, (7, 438887)),
    (438896, (19, 438877)),
    (438898, (11, 438887)),
    (438900, (13, 438887)),
    (438902, (3, 438899)),
    (438904, (5, 438899)),
    (438906, (7, 438899)),
    (438908, (31, 438877)),
    (438910, (11, 438899)),
    (438912, (13, 438899)),
    (438914, (37, 438877)),
    (438916, (3, 438913)),
    (438918, (5, 438913)),
    (438920, (7, 438913)),
    (438922, (23, 438899)),
    (438924, (11, 438913)),
    (438926, (13, 438913)),
    (438928, (29, 438899)),
    (438930, (17, 438913)),
    (438932, (19, 438913)),
    (438934, (47, 438887)),
    (438936, (23, 438913)),
    (438938, (61, 438877)),
    (438940, (3, 438937)),
    (438942, (5, 438937)),
    (438944, (3, 438941)),
    (438946, (5, 438941)),
    (438948, (7, 438941)),
    (438950, (13, 438937)),
    (438952, (11, 438941)),
    (438954, (13, 438941)),
    (438956, (3, 438953)),
    (438958, (5, 438953)),
    (438960, (7, 438953)),
    (438962, (109, 438853)),
    (438964, (3, 438961)),
    (438966, (5, 438961)),
    (438968, (7, 438961)),
    (438970, (3, 438967)),
    (438972, (5, 438967)),
    (438974, (7, 438967)),
    (438976, (23, 438953)),
    (438978, (11, 438967)),
    (438980, (13, 438967)),
    (438982, (3, 438979)),
    (438984, (5, 438979)),
    (438986, (3, 438983)),
    (438988, (5, 438983)),
    (438990, (7, 438983)),
    (438992, (3, 438989)),
    (438994, (5, 438989)),
    (438996, (7, 438989)),
    (438998, (19, 438979)),
    (439000, (11, 438989)),
    (439002, (13, 438989)),
    (439004, (37, 438967)),
    (439006, (17, 438989)),
    (439008, (19, 438989)),
    (439010, (3, 439007)),
    (439012, (3, 439009)),
    (439014, (5, 439009)),
    (439016, (7, 439009)),
    (439018, (11, 439007)),
    (439020, (11, 439009)),
    (439022, (13, 439009)),
    (439024, (17, 439007)),
    (439026, (17, 439009)),
    (439028, (19, 439009)),
    (439030, (23, 439007)),
    (439032, (23, 439009)),
    (439034, (67, 438967)),
    (439036, (29, 439007)),
    (439038, (29, 439009)),
    (439040, (31, 439009)),
    (439042, (53, 438989)),
    (439044, (37, 439007))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk043_al_verified
