/-
AUTOGENERATED (soundness mode): Chunk [547856..548092]
    Source: chunk_054.json  •  SHA256(JSON): ccdcbc73d02d0c3e00ff8c526e2e13e61d2578f1192ed9ccc9481bca920ab400
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk054_ah_verified

noncomputable section

def nLo : Nat := 547856
def nHi : Nat := 548092
def dataSHA256 : String := "ccdcbc73d02d0c3e00ff8c526e2e13e61d2578f1192ed9ccc9481bca920ab400"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (547856, (3, 547853)),
    (547858, (5, 547853)),
    (547860, (7, 547853)),
    (547862, (13, 547849)),
    (547864, (11, 547853)),
    (547866, (13, 547853)),
    (547868, (19, 547849)),
    (547870, (17, 547853)),
    (547872, (19, 547853)),
    (547874, (3, 547871)),
    (547876, (5, 547871)),
    (547878, (7, 547871)),
    (547880, (31, 547849)),
    (547882, (11, 547871)),
    (547884, (13, 547871)),
    (547886, (37, 547849)),
    (547888, (17, 547871)),
    (547890, (19, 547871)),
    (547892, (3, 547889)),
    (547894, (5, 547889)),
    (547896, (7, 547889)),
    (547898, (67, 547831)),
    (547900, (11, 547889)),
    (547902, (13, 547889)),
    (547904, (3, 547901)),
    (547906, (5, 547901)),
    (547908, (7, 547901)),
    (547910, (61, 547849)),
    (547912, (3, 547909)),
    (547914, (5, 547909)),
    (547916, (7, 547909)),
    (547918, (17, 547901)),
    (547920, (11, 547909)),
    (547922, (13, 547909)),
    (547924, (23, 547901)),
    (547926, (17, 547909)),
    (547928, (19, 547909)),
    (547930, (29, 547901)),
    (547932, (23, 547909)),
    (547934, (103, 547831)),
    (547936, (47, 547889)),
    (547938, (29, 547909)),
    (547940, (31, 547909)),
    (547942, (41, 547901)),
    (547944, (43, 547901)),
    (547946, (37, 547909)),
    (547948, (47, 547901)),
    (547950, (41, 547909)),
    (547952, (43, 547909)),
    (547954, (3, 547951)),
    (547956, (5, 547951)),
    (547958, (7, 547951)),
    (547960, (3, 547957)),
    (547962, (5, 547957)),
    (547964, (7, 547957)),
    (547966, (113, 547853)),
    (547968, (11, 547957)),
    (547970, (13, 547957)),
    (547972, (71, 547901)),
    (547974, (17, 547957)),
    (547976, (19, 547957)),
    (547978, (89, 547889)),
    (547980, (23, 547957)),
    (547982, (31, 547951)),
    (547984, (83, 547901)),
    (547986, (29, 547957)),
    (547988, (31, 547957)),
    (547990, (89, 547901)),
    (547992, (41, 547951)),
    (547994, (37, 547957)),
    (547996, (107, 547889)),
    (547998, (41, 547957)),
    (548000, (43, 547957)),
    (548002, (3, 547999)),
    (548004, (5, 547999)),
    (548006, (3, 548003)),
    (548008, (5, 548003)),
    (548010, (7, 548003)),
    (548012, (13, 547999)),
    (548014, (11, 548003)),
    (548016, (13, 548003)),
    (548018, (19, 547999)),
    (548020, (17, 548003)),
    (548022, (19, 548003)),
    (548024, (67, 547957)),
    (548026, (23, 548003)),
    (548028, (29, 547999)),
    (548030, (31, 547999)),
    (548032, (29, 548003)),
    (548034, (31, 548003)),
    (548036, (37, 547999)),
    (548038, (137, 547901)),
    (548040, (37, 548003)),
    (548042, (3, 548039)),
    (548044, (5, 548039)),
    (548046, (7, 548039)),
    (548048, (97, 547951)),
    (548050, (11, 548039)),
    (548052, (13, 548039)),
    (548054, (97, 547957)),
    (548056, (17, 548039)),
    (548058, (19, 548039)),
    (548060, (61, 547999)),
    (548062, (3, 548059)),
    (548064, (5, 548059)),
    (548066, (7, 548059)),
    (548068, (29, 548039)),
    (548070, (11, 548059)),
    (548072, (3, 548069)),
    (548074, (5, 548069)),
    (548076, (7, 548069)),
    (548078, (19, 548059)),
    (548080, (11, 548069)),
    (548082, (13, 548069)),
    (548084, (127, 547957)),
    (548086, (3, 548083)),
    (548088, (5, 548083)),
    (548090, (7, 548083)),
    (548092, (3, 548089))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk054_ah_verified
