/-
AUTOGENERATED (soundness mode): Chunk [166428..166664]
    Source: chunk_016.json  •  SHA256(JSON): dee0fc0af880770c3745ec0945ac7c56a1034c5e26ffa40e702aa0bc09697ea2
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk016_ab_verified

noncomputable section

def nLo : Nat := 166428
def nHi : Nat := 166664
def dataSHA256 : String := "dee0fc0af880770c3745ec0945ac7c56a1034c5e26ffa40e702aa0bc09697ea2"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (166428, (11, 166417)),
    (166430, (13, 166417)),
    (166432, (3, 166429)),
    (166434, (5, 166429)),
    (166436, (7, 166429)),
    (166438, (29, 166409)),
    (166440, (11, 166429)),
    (166442, (13, 166429)),
    (166444, (41, 166403)),
    (166446, (17, 166429)),
    (166448, (19, 166429)),
    (166450, (41, 166409)),
    (166452, (23, 166429)),
    (166454, (37, 166417)),
    (166456, (47, 166409)),
    (166458, (29, 166429)),
    (166460, (3, 166457)),
    (166462, (5, 166457)),
    (166464, (7, 166457)),
    (166466, (37, 166429)),
    (166468, (11, 166457)),
    (166470, (13, 166457)),
    (166472, (43, 166429)),
    (166474, (3, 166471)),
    (166476, (5, 166471)),
    (166478, (7, 166471)),
    (166480, (23, 166457)),
    (166482, (11, 166471)),
    (166484, (13, 166471)),
    (166486, (29, 166457)),
    (166488, (17, 166471)),
    (166490, (3, 166487)),
    (166492, (5, 166487)),
    (166494, (7, 166487)),
    (166496, (67, 166429)),
    (166498, (11, 166487)),
    (166500, (13, 166487)),
    (166502, (31, 166471)),
    (166504, (17, 166487)),
    (166506, (19, 166487)),
    (166508, (37, 166471)),
    (166510, (23, 166487)),
    (166512, (41, 166471)),
    (166514, (43, 166471)),
    (166516, (29, 166487)),
    (166518, (31, 166487)),
    (166520, (103, 166417)),
    (166522, (113, 166409)),
    (166524, (37, 166487)),
    (166526, (97, 166429)),
    (166528, (41, 166487)),
    (166530, (43, 166487)),
    (166532, (61, 166471)),
    (166534, (47, 166487)),
    (166536, (79, 166457)),
    (166538, (67, 166471)),
    (166540, (53, 166487)),
    (166542, (71, 166471)),
    (166544, (3, 166541)),
    (166546, (5, 166541)),
    (166548, (7, 166541)),
    (166550, (79, 166471)),
    (166552, (11, 166541)),
    (166554, (13, 166541)),
    (166556, (127, 166429)),
    (166558, (17, 166541)),
    (166560, (19, 166541)),
    (166562, (163, 166399)),
    (166564, (3, 166561)),
    (166566, (5, 166561)),
    (166568, (7, 166561)),
    (166570, (3, 166567)),
    (166572, (5, 166567)),
    (166574, (3, 166571)),
    (166576, (5, 166571)),
    (166578, (7, 166571)),
    (166580, (13, 166567)),
    (166582, (11, 166571)),
    (166584, (13, 166571)),
    (166586, (19, 166567)),
    (166588, (17, 166571)),
    (166590, (19, 166571)),
    (166592, (31, 166561)),
    (166594, (23, 166571)),
    (166596, (29, 166567)),
    (166598, (31, 166567)),
    (166600, (3, 166597)),
    (166602, (5, 166597)),
    (166604, (3, 166601)),
    (166606, (3, 166603)),
    (166608, (5, 166603)),
    (166610, (7, 166603)),
    (166612, (3, 166609)),
    (166614, (5, 166609)),
    (166616, (3, 166613)),
    (166618, (5, 166613)),
    (166620, (7, 166613)),
    (166622, (3, 166619)),
    (166624, (5, 166619)),
    (166626, (7, 166619)),
    (166628, (19, 166609)),
    (166630, (3, 166627)),
    (166632, (5, 166627)),
    (166634, (3, 166631)),
    (166636, (5, 166631)),
    (166638, (7, 166631)),
    (166640, (13, 166627)),
    (166642, (11, 166631)),
    (166644, (13, 166631)),
    (166646, (3, 166643)),
    (166648, (5, 166643)),
    (166650, (7, 166643)),
    (166652, (43, 166609)),
    (166654, (11, 166643)),
    (166656, (13, 166643)),
    (166658, (31, 166627)),
    (166660, (3, 166657)),
    (166662, (5, 166657)),
    (166664, (7, 166657))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk016_ab_verified
