/-
AUTOGENERATED (soundness mode): Chunk [558570..558806]
    Source: chunk_055.json  •  SHA256(JSON): 03905e41686032ffe2eba148e14fecf48c3a53b66e09f906976c0b867addb06e
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk055_ak_verified

noncomputable section

def nLo : Nat := 558570
def nHi : Nat := 558806
def dataSHA256 : String := "03905e41686032ffe2eba148e14fecf48c3a53b66e09f906976c0b867addb06e"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (558570, (7, 558563)),
    (558572, (31, 558541)),
    (558574, (11, 558563)),
    (558576, (13, 558563)),
    (558578, (37, 558541)),
    (558580, (17, 558563)),
    (558582, (19, 558563)),
    (558584, (43, 558541)),
    (558586, (3, 558583)),
    (558588, (5, 558583)),
    (558590, (3, 558587)),
    (558592, (5, 558587)),
    (558594, (7, 558587)),
    (558596, (13, 558583)),
    (558598, (11, 558587)),
    (558600, (13, 558587)),
    (558602, (3, 558599)),
    (558604, (5, 558599)),
    (558606, (7, 558599)),
    (558608, (67, 558541)),
    (558610, (11, 558599)),
    (558612, (13, 558599)),
    (558614, (3, 558611)),
    (558616, (5, 558611)),
    (558618, (7, 558611)),
    (558620, (37, 558583)),
    (558622, (11, 558611)),
    (558624, (13, 558611)),
    (558626, (43, 558583)),
    (558628, (17, 558611)),
    (558630, (19, 558611)),
    (558632, (3, 558629)),
    (558634, (5, 558629)),
    (558636, (7, 558629)),
    (558638, (97, 558541)),
    (558640, (11, 558629)),
    (558642, (13, 558629)),
    (558644, (61, 558583)),
    (558646, (3, 558643)),
    (558648, (5, 558643)),
    (558650, (7, 558643)),
    (558652, (23, 558629)),
    (558654, (11, 558643)),
    (558656, (13, 558643)),
    (558658, (29, 558629)),
    (558660, (17, 558643)),
    (558662, (19, 558643)),
    (558664, (3, 558661)),
    (558666, (5, 558661)),
    (558668, (7, 558661)),
    (558670, (41, 558629)),
    (558672, (11, 558661)),
    (558674, (13, 558661)),
    (558676, (47, 558629)),
    (558678, (17, 558661)),
    (558680, (19, 558661)),
    (558682, (53, 558629)),
    (558684, (23, 558661)),
    (558686, (3, 558683)),
    (558688, (5, 558683)),
    (558690, (7, 558683)),
    (558692, (31, 558661)),
    (558694, (11, 558683)),
    (558696, (13, 558683)),
    (558698, (37, 558661)),
    (558700, (17, 558683)),
    (558702, (19, 558683)),
    (558704, (43, 558661)),
    (558706, (3, 558703)),
    (558708, (5, 558703)),
    (558710, (7, 558703)),
    (558712, (29, 558683)),
    (558714, (11, 558703)),
    (558716, (13, 558703)),
    (558718, (89, 558629)),
    (558720, (17, 558703)),
    (558722, (19, 558703)),
    (558724, (3, 558721)),
    (558726, (5, 558721)),
    (558728, (7, 558721)),
    (558730, (47, 558683)),
    (558732, (11, 558721)),
    (558734, (3, 558731)),
    (558736, (5, 558731)),
    (558738, (7, 558731)),
    (558740, (19, 558721)),
    (558742, (11, 558731)),
    (558744, (13, 558731)),
    (558746, (43, 558703)),
    (558748, (17, 558731)),
    (558750, (19, 558731)),
    (558752, (31, 558721)),
    (558754, (23, 558731)),
    (558756, (53, 558703)),
    (558758, (37, 558721)),
    (558760, (3, 558757)),
    (558762, (5, 558757)),
    (558764, (7, 558757)),
    (558766, (83, 558683)),
    (558768, (11, 558757)),
    (558770, (13, 558757)),
    (558772, (3, 558769)),
    (558774, (5, 558769)),
    (558776, (7, 558769)),
    (558778, (47, 558731)),
    (558780, (11, 558769)),
    (558782, (13, 558769)),
    (558784, (3, 558781)),
    (558786, (5, 558781)),
    (558788, (7, 558781)),
    (558790, (3, 558787)),
    (558792, (5, 558787)),
    (558794, (3, 558791)),
    (558796, (3, 558793)),
    (558798, (5, 558793)),
    (558800, (7, 558793)),
    (558802, (11, 558791)),
    (558804, (11, 558793)),
    (558806, (13, 558793))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk055_ak_verified
