/-
AUTOGENERATED (soundness mode): Chunk [698808..699044]
    Source: chunk_069.json  •  SHA256(JSON): d0de925454578f3038772f690f939f5c9658c3f05b02dea504bddc78914f08c0
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk069_al_verified

noncomputable section

def nLo : Nat := 698808
def nHi : Nat := 699044
def dataSHA256 : String := "d0de925454578f3038772f690f939f5c9658c3f05b02dea504bddc78914f08c0"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (698808, (29, 698779)),
    (698810, (31, 698779)),
    (698812, (83, 698729)),
    (698814, (41, 698773)),
    (698816, (37, 698779)),
    (698818, (89, 698729)),
    (698820, (41, 698779)),
    (698822, (43, 698779)),
    (698824, (3, 698821)),
    (698826, (5, 698821)),
    (698828, (7, 698821)),
    (698830, (3, 698827)),
    (698832, (5, 698827)),
    (698834, (7, 698827)),
    (698836, (107, 698729)),
    (698838, (11, 698827)),
    (698840, (13, 698827)),
    (698842, (113, 698729)),
    (698844, (17, 698827)),
    (698846, (19, 698827)),
    (698848, (179, 698669)),
    (698850, (23, 698827)),
    (698852, (3, 698849)),
    (698854, (5, 698849)),
    (698856, (7, 698849)),
    (698858, (31, 698827)),
    (698860, (11, 698849)),
    (698862, (13, 698849)),
    (698864, (37, 698827)),
    (698866, (17, 698849)),
    (698868, (19, 698849)),
    (698870, (43, 698827)),
    (698872, (23, 698849)),
    (698874, (47, 698827)),
    (698876, (97, 698779)),
    (698878, (29, 698849)),
    (698880, (31, 698849)),
    (698882, (61, 698821)),
    (698884, (293, 698591)),
    (698886, (37, 698849)),
    (698888, (61, 698827)),
    (698890, (41, 698849)),
    (698892, (43, 698849)),
    (698894, (3, 698891)),
    (698896, (5, 698891)),
    (698898, (7, 698891)),
    (698900, (73, 698827)),
    (698902, (3, 698899)),
    (698904, (5, 698899)),
    (698906, (3, 698903)),
    (698908, (5, 698903)),
    (698910, (7, 698903)),
    (698912, (13, 698899)),
    (698914, (11, 698903)),
    (698916, (13, 698903)),
    (698918, (19, 698899)),
    (698920, (17, 698903)),
    (698922, (19, 698903)),
    (698924, (97, 698827)),
    (698926, (3, 698923)),
    (698928, (5, 698923)),
    (698930, (7, 698923)),
    (698932, (29, 698903)),
    (698934, (11, 698923)),
    (698936, (13, 698923)),
    (698938, (47, 698891)),
    (698940, (17, 698923)),
    (698942, (3, 698939)),
    (698944, (5, 698939)),
    (698946, (7, 698939)),
    (698948, (127, 698821)),
    (698950, (11, 698939)),
    (698952, (13, 698939)),
    (698954, (31, 698923)),
    (698956, (17, 698939)),
    (698958, (19, 698939)),
    (698960, (37, 698923)),
    (698962, (23, 698939)),
    (698964, (41, 698923)),
    (698966, (43, 698923)),
    (698968, (29, 698939)),
    (698970, (31, 698939)),
    (698972, (73, 698899)),
    (698974, (71, 698903)),
    (698976, (37, 698939)),
    (698978, (79, 698899)),
    (698980, (3, 698977)),
    (698982, (5, 698977)),
    (698984, (7, 698977)),
    (698986, (3, 698983)),
    (698988, (5, 698983)),
    (698990, (7, 698983)),
    (698992, (53, 698939)),
    (698994, (11, 698983)),
    (698996, (13, 698983)),
    (698998, (59, 698939)),
    (699000, (17, 698983)),
    (699002, (19, 698983)),
    (699004, (3, 699001)),
    (699006, (5, 699001)),
    (699008, (7, 699001)),
    (699010, (3, 699007)),
    (699012, (5, 699007)),
    (699014, (7, 699007)),
    (699016, (113, 698903)),
    (699018, (11, 699007)),
    (699020, (13, 699007)),
    (699022, (83, 698939)),
    (699024, (17, 699007)),
    (699026, (19, 699007)),
    (699028, (89, 698939)),
    (699030, (23, 699007)),
    (699032, (31, 699001)),
    (699034, (131, 698903)),
    (699036, (29, 699007)),
    (699038, (31, 699007)),
    (699040, (3, 699037)),
    (699042, (5, 699037)),
    (699044, (7, 699037))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk069_al_verified
