/-
AUTOGENERATED (soundness mode): Chunk [44762..44998]
    Source: chunk_004.json  •  SHA256(JSON): e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk004_u_verified

noncomputable section

def nLo : Nat := 44762
def nHi : Nat := 44998
def dataSHA256 : String := "e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (44762, (61, 44701)),
    (44764, (11, 44753)),
    (44766, (13, 44753)),
    (44768, (67, 44701)),
    (44770, (17, 44753)),
    (44772, (19, 44753)),
    (44774, (3, 44771)),
    (44776, (3, 44773)),
    (44778, (5, 44773)),
    (44780, (3, 44777)),
    (44782, (5, 44777)),
    (44784, (7, 44777)),
    (44786, (13, 44773)),
    (44788, (11, 44777)),
    (44790, (13, 44777)),
    (44792, (3, 44789)),
    (44794, (5, 44789)),
    (44796, (7, 44789)),
    (44798, (97, 44701)),
    (44800, (3, 44797)),
    (44802, (5, 44797)),
    (44804, (7, 44797)),
    (44806, (17, 44789)),
    (44808, (11, 44797)),
    (44810, (13, 44797)),
    (44812, (3, 44809)),
    (44814, (5, 44809)),
    (44816, (7, 44809)),
    (44818, (29, 44789)),
    (44820, (11, 44809)),
    (44822, (3, 44819)),
    (44824, (5, 44819)),
    (44826, (7, 44819)),
    (44828, (19, 44809)),
    (44830, (11, 44819)),
    (44832, (13, 44819)),
    (44834, (37, 44797)),
    (44836, (17, 44819)),
    (44838, (19, 44819)),
    (44840, (31, 44809)),
    (44842, (3, 44839)),
    (44844, (5, 44839)),
    (44846, (3, 44843)),
    (44848, (5, 44843)),
    (44850, (7, 44843)),
    (44852, (13, 44839)),
    (44854, (3, 44851)),
    (44856, (5, 44851)),
    (44858, (7, 44851)),
    (44860, (17, 44843)),
    (44862, (11, 44851)),
    (44864, (13, 44851)),
    (44866, (23, 44843)),
    (44868, (17, 44851)),
    (44870, (3, 44867)),
    (44872, (5, 44867)),
    (44874, (7, 44867)),
    (44876, (37, 44839)),
    (44878, (11, 44867)),
    (44880, (13, 44867)),
    (44882, (3, 44879)),
    (44884, (5, 44879)),
    (44886, (7, 44879)),
    (44888, (37, 44851)),
    (44890, (3, 44887)),
    (44892, (5, 44887)),
    (44894, (7, 44887)),
    (44896, (3, 44893)),
    (44898, (5, 44893)),
    (44900, (7, 44893)),
    (44902, (23, 44879)),
    (44904, (11, 44893)),
    (44906, (13, 44893)),
    (44908, (29, 44879)),
    (44910, (17, 44893)),
    (44912, (3, 44909)),
    (44914, (5, 44909)),
    (44916, (7, 44909)),
    (44918, (31, 44887)),
    (44920, (3, 44917)),
    (44922, (5, 44917)),
    (44924, (7, 44917)),
    (44926, (17, 44909)),
    (44928, (11, 44917)),
    (44930, (3, 44927)),
    (44932, (5, 44927)),
    (44934, (7, 44927)),
    (44936, (19, 44917)),
    (44938, (11, 44927)),
    (44940, (13, 44927)),
    (44942, (3, 44939)),
    (44944, (5, 44939)),
    (44946, (7, 44939)),
    (44948, (31, 44917)),
    (44950, (11, 44939)),
    (44952, (13, 44939)),
    (44954, (37, 44917)),
    (44956, (3, 44953)),
    (44958, (5, 44953)),
    (44960, (7, 44953)),
    (44962, (3, 44959)),
    (44964, (5, 44959)),
    (44966, (3, 44963)),
    (44968, (5, 44963)),
    (44970, (7, 44963)),
    (44972, (13, 44959)),
    (44974, (3, 44971)),
    (44976, (5, 44971)),
    (44978, (7, 44971)),
    (44980, (17, 44963)),
    (44982, (11, 44971)),
    (44984, (13, 44971)),
    (44986, (3, 44983)),
    (44988, (5, 44983)),
    (44990, (3, 44987)),
    (44992, (5, 44987)),
    (44994, (7, 44987)),
    (44996, (13, 44983)),
    (44998, (11, 44987))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk004_u_verified
