/-
AUTOGENERATED (soundness mode): Chunk [231192..231428]
    Source: chunk_023.json  •  SHA256(JSON): 70063d5b4a04ba8cf60d12aacad8e18b8ee15a65c0a132555f594bdadddb7f19
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk023_f_verified

noncomputable section

def nLo : Nat := 231192
def nHi : Nat := 231428
def dataSHA256 : String := "70063d5b4a04ba8cf60d12aacad8e18b8ee15a65c0a132555f594bdadddb7f19"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (231192, (23, 231169)),
    (231194, (127, 231067)),
    (231196, (89, 231107)),
    (231198, (29, 231169)),
    (231200, (3, 231197)),
    (231202, (5, 231197)),
    (231204, (7, 231197)),
    (231206, (37, 231169)),
    (231208, (11, 231197)),
    (231210, (13, 231197)),
    (231212, (43, 231169)),
    (231214, (17, 231197)),
    (231216, (19, 231197)),
    (231218, (109, 231109)),
    (231220, (23, 231197)),
    (231222, (53, 231169)),
    (231224, (157, 231067)),
    (231226, (3, 231223)),
    (231228, (5, 231223)),
    (231230, (7, 231223)),
    (231232, (101, 231131)),
    (231234, (11, 231223)),
    (231236, (13, 231223)),
    (231238, (41, 231197)),
    (231240, (17, 231223)),
    (231242, (19, 231223)),
    (231244, (3, 231241)),
    (231246, (5, 231241)),
    (231248, (7, 231241)),
    (231250, (53, 231197)),
    (231252, (11, 231241)),
    (231254, (13, 231241)),
    (231256, (59, 231197)),
    (231258, (17, 231241)),
    (231260, (19, 231241)),
    (231262, (131, 231131)),
    (231264, (23, 231241)),
    (231266, (43, 231223)),
    (231268, (71, 231197)),
    (231270, (29, 231241)),
    (231272, (3, 231269)),
    (231274, (3, 231271)),
    (231276, (5, 231271)),
    (231278, (7, 231271)),
    (231280, (3, 231277)),
    (231282, (5, 231277)),
    (231284, (7, 231277)),
    (231286, (17, 231269)),
    (231288, (11, 231277)),
    (231290, (13, 231277)),
    (231292, (3, 231289)),
    (231294, (5, 231289)),
    (231296, (3, 231293)),
    (231298, (5, 231293)),
    (231300, (7, 231293)),
    (231302, (3, 231299)),
    (231304, (5, 231299)),
    (231306, (7, 231299)),
    (231308, (19, 231289)),
    (231310, (11, 231299)),
    (231312, (13, 231299)),
    (231314, (37, 231277)),
    (231316, (17, 231299)),
    (231318, (19, 231299)),
    (231320, (3, 231317)),
    (231322, (5, 231317)),
    (231324, (7, 231317)),
    (231326, (3, 231323)),
    (231328, (5, 231323)),
    (231330, (7, 231323)),
    (231332, (43, 231289)),
    (231334, (3, 231331)),
    (231336, (5, 231331)),
    (231338, (7, 231331)),
    (231340, (17, 231323)),
    (231342, (11, 231331)),
    (231344, (13, 231331)),
    (231346, (23, 231323)),
    (231348, (17, 231331)),
    (231350, (3, 231347)),
    (231352, (3, 231349)),
    (231354, (5, 231349)),
    (231356, (7, 231349)),
    (231358, (11, 231347)),
    (231360, (11, 231349)),
    (231362, (3, 231359)),
    (231364, (5, 231359)),
    (231366, (7, 231359)),
    (231368, (19, 231349)),
    (231370, (3, 231367)),
    (231372, (5, 231367)),
    (231374, (7, 231367)),
    (231376, (17, 231359)),
    (231378, (11, 231367)),
    (231380, (13, 231367)),
    (231382, (3, 231379)),
    (231384, (5, 231379)),
    (231386, (7, 231379)),
    (231388, (29, 231359)),
    (231390, (11, 231379)),
    (231392, (13, 231379)),
    (231394, (47, 231347)),
    (231396, (17, 231379)),
    (231398, (19, 231379)),
    (231400, (41, 231359)),
    (231402, (23, 231379)),
    (231404, (37, 231367)),
    (231406, (47, 231359)),
    (231408, (29, 231379)),
    (231410, (31, 231379)),
    (231412, (3, 231409)),
    (231414, (5, 231409)),
    (231416, (7, 231409)),
    (231418, (59, 231359)),
    (231420, (11, 231409)),
    (231422, (3, 231419)),
    (231424, (5, 231419)),
    (231426, (7, 231419)),
    (231428, (19, 231409))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk023_f_verified
