/-
AUTOGENERATED (soundness mode): Chunk [307380..307616]
    Source: chunk_030.json  •  SHA256(JSON): f1186dcbb6b87dae3797d7e8e5af2c06ab5ec7ac84747b24ecc1ea45963fa436
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk030_af_verified

noncomputable section

def nLo : Nat := 307380
def nHi : Nat := 307616
def dataSHA256 : String := "f1186dcbb6b87dae3797d7e8e5af2c06ab5ec7ac84747b24ecc1ea45963fa436"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (307380, (13, 307367)),
    (307382, (43, 307339)),
    (307384, (3, 307381)),
    (307386, (5, 307381)),
    (307388, (7, 307381)),
    (307390, (23, 307367)),
    (307392, (11, 307381)),
    (307394, (13, 307381)),
    (307396, (29, 307367)),
    (307398, (17, 307381)),
    (307400, (3, 307397)),
    (307402, (3, 307399)),
    (307404, (5, 307399)),
    (307406, (7, 307399)),
    (307408, (11, 307397)),
    (307410, (11, 307399)),
    (307412, (3, 307409)),
    (307414, (5, 307409)),
    (307416, (7, 307409)),
    (307418, (19, 307399)),
    (307420, (11, 307409)),
    (307422, (13, 307409)),
    (307424, (43, 307381)),
    (307426, (3, 307423)),
    (307428, (5, 307423)),
    (307430, (7, 307423)),
    (307432, (23, 307409)),
    (307434, (11, 307423)),
    (307436, (13, 307423)),
    (307438, (29, 307409)),
    (307440, (17, 307423)),
    (307442, (19, 307423)),
    (307444, (47, 307397)),
    (307446, (23, 307423)),
    (307448, (67, 307381)),
    (307450, (41, 307409)),
    (307452, (29, 307423)),
    (307454, (3, 307451)),
    (307456, (5, 307451)),
    (307458, (7, 307451)),
    (307460, (37, 307423)),
    (307462, (11, 307451)),
    (307464, (13, 307451)),
    (307466, (43, 307423)),
    (307468, (17, 307451)),
    (307470, (19, 307451)),
    (307472, (73, 307399)),
    (307474, (3, 307471)),
    (307476, (5, 307471)),
    (307478, (7, 307471)),
    (307480, (29, 307451)),
    (307482, (11, 307471)),
    (307484, (3, 307481)),
    (307486, (5, 307481)),
    (307488, (7, 307481)),
    (307490, (19, 307471)),
    (307492, (11, 307481)),
    (307494, (13, 307481)),
    (307496, (73, 307423)),
    (307498, (17, 307481)),
    (307500, (19, 307481)),
    (307502, (31, 307471)),
    (307504, (23, 307481)),
    (307506, (83, 307423)),
    (307508, (37, 307471)),
    (307510, (29, 307481)),
    (307512, (31, 307481)),
    (307514, (3, 307511)),
    (307516, (5, 307511)),
    (307518, (7, 307511)),
    (307520, (97, 307423)),
    (307522, (11, 307511)),
    (307524, (13, 307511)),
    (307526, (3, 307523)),
    (307528, (5, 307523)),
    (307530, (7, 307523)),
    (307532, (3, 307529)),
    (307534, (5, 307529)),
    (307536, (7, 307529)),
    (307538, (67, 307471)),
    (307540, (3, 307537)),
    (307542, (5, 307537)),
    (307544, (7, 307537)),
    (307546, (3, 307543)),
    (307548, (5, 307543)),
    (307550, (7, 307543)),
    (307552, (23, 307529)),
    (307554, (11, 307543)),
    (307556, (13, 307543)),
    (307558, (29, 307529)),
    (307560, (17, 307543)),
    (307562, (19, 307543)),
    (307564, (41, 307523)),
    (307566, (23, 307543)),
    (307568, (31, 307537)),
    (307570, (41, 307529)),
    (307572, (29, 307543)),
    (307574, (31, 307543)),
    (307576, (47, 307529)),
    (307578, (41, 307537)),
    (307580, (3, 307577)),
    (307582, (5, 307577)),
    (307584, (7, 307577)),
    (307586, (3, 307583)),
    (307588, (5, 307583)),
    (307590, (7, 307583)),
    (307592, (3, 307589)),
    (307594, (5, 307589)),
    (307596, (7, 307589)),
    (307598, (61, 307537)),
    (307600, (11, 307589)),
    (307602, (13, 307589)),
    (307604, (61, 307543)),
    (307606, (17, 307589)),
    (307608, (19, 307589)),
    (307610, (67, 307543)),
    (307612, (3, 307609)),
    (307614, (5, 307609)),
    (307616, (7, 307609))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk030_af_verified
