/-
AUTOGENERATED (soundness mode): Chunk [391668..391904]
    Source: chunk_039.json  •  SHA256(JSON): 483b26fd3755bedc6017fe0a4b6016e215b79fa2ddc72bf3bb60de1318685369
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk039_h_verified

noncomputable section

def nLo : Nat := 391668
def nHi : Nat := 391904
def dataSHA256 : String := "483b26fd3755bedc6017fe0a4b6016e215b79fa2ddc72bf3bb60de1318685369"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (391668, (7, 391661)),
    (391670, (31, 391639)),
    (391672, (11, 391661)),
    (391674, (13, 391661)),
    (391676, (37, 391639)),
    (391678, (17, 391661)),
    (391680, (19, 391661)),
    (391682, (3, 391679)),
    (391684, (5, 391679)),
    (391686, (7, 391679)),
    (391688, (61, 391627)),
    (391690, (11, 391679)),
    (391692, (13, 391679)),
    (391694, (3, 391691)),
    (391696, (3, 391693)),
    (391698, (5, 391693)),
    (391700, (7, 391693)),
    (391702, (11, 391691)),
    (391704, (11, 391693)),
    (391706, (13, 391693)),
    (391708, (17, 391691)),
    (391710, (17, 391693)),
    (391712, (19, 391693)),
    (391714, (3, 391711)),
    (391716, (5, 391711)),
    (391718, (7, 391711)),
    (391720, (3, 391717)),
    (391722, (5, 391717)),
    (391724, (7, 391717)),
    (391726, (47, 391679)),
    (391728, (11, 391717)),
    (391730, (13, 391717)),
    (391732, (41, 391691)),
    (391734, (17, 391717)),
    (391736, (3, 391733)),
    (391738, (5, 391733)),
    (391740, (7, 391733)),
    (391742, (3, 391739)),
    (391744, (5, 391739)),
    (391746, (7, 391739)),
    (391748, (31, 391717)),
    (391750, (11, 391739)),
    (391752, (13, 391739)),
    (391754, (3, 391751)),
    (391756, (3, 391753)),
    (391758, (5, 391753)),
    (391760, (3, 391757)),
    (391762, (5, 391757)),
    (391764, (7, 391757)),
    (391766, (13, 391753)),
    (391768, (11, 391757)),
    (391770, (13, 391757)),
    (391772, (19, 391753)),
    (391774, (17, 391757)),
    (391776, (19, 391757)),
    (391778, (61, 391717)),
    (391780, (23, 391757)),
    (391782, (29, 391753)),
    (391784, (31, 391753)),
    (391786, (29, 391757)),
    (391788, (31, 391757)),
    (391790, (37, 391753)),
    (391792, (3, 391789)),
    (391794, (5, 391789)),
    (391796, (7, 391789)),
    (391798, (41, 391757)),
    (391800, (11, 391789)),
    (391802, (13, 391789)),
    (391804, (3, 391801)),
    (391806, (5, 391801)),
    (391808, (7, 391801)),
    (391810, (53, 391757)),
    (391812, (11, 391801)),
    (391814, (13, 391801)),
    (391816, (59, 391757)),
    (391818, (17, 391801)),
    (391820, (3, 391817)),
    (391822, (5, 391817)),
    (391824, (7, 391817)),
    (391826, (3, 391823)),
    (391828, (5, 391823)),
    (391830, (7, 391823)),
    (391832, (31, 391801)),
    (391834, (11, 391823)),
    (391836, (13, 391823)),
    (391838, (37, 391801)),
    (391840, (17, 391823)),
    (391842, (19, 391823)),
    (391844, (43, 391801)),
    (391846, (23, 391823)),
    (391848, (31, 391817)),
    (391850, (3, 391847)),
    (391852, (5, 391847)),
    (391854, (7, 391847)),
    (391856, (67, 391789)),
    (391858, (11, 391847)),
    (391860, (13, 391847)),
    (391862, (61, 391801)),
    (391864, (3, 391861)),
    (391866, (5, 391861)),
    (391868, (7, 391861)),
    (391870, (23, 391847)),
    (391872, (11, 391861)),
    (391874, (13, 391861)),
    (391876, (3, 391873)),
    (391878, (5, 391873)),
    (391880, (7, 391873)),
    (391882, (3, 391879)),
    (391884, (5, 391879)),
    (391886, (7, 391879)),
    (391888, (41, 391847)),
    (391890, (11, 391879)),
    (391892, (3, 391889)),
    (391894, (3, 391891)),
    (391896, (5, 391891)),
    (391898, (7, 391891)),
    (391900, (11, 391889)),
    (391902, (11, 391891)),
    (391904, (13, 391891))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk039_h_verified
