/-
AUTOGENERATED (soundness mode): Chunk [694048..694284]
    Source: chunk_069.json  •  SHA256(JSON): d0de925454578f3038772f690f939f5c9658c3f05b02dea504bddc78914f08c0
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk069_r_verified

noncomputable section

def nLo : Nat := 694048
def nHi : Nat := 694284
def dataSHA256 : String := "d0de925454578f3038772f690f939f5c9658c3f05b02dea504bddc78914f08c0"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (694048, (29, 694019)),
    (694050, (11, 694039)),
    (694052, (13, 694039)),
    (694054, (173, 693881)),
    (694056, (17, 694039)),
    (694058, (19, 694039)),
    (694060, (41, 694019)),
    (694062, (23, 694039)),
    (694064, (3, 694061)),
    (694066, (5, 694061)),
    (694068, (7, 694061)),
    (694070, (31, 694039)),
    (694072, (3, 694069)),
    (694074, (5, 694069)),
    (694076, (7, 694069)),
    (694078, (17, 694061)),
    (694080, (11, 694069)),
    (694082, (3, 694079)),
    (694084, (3, 694081)),
    (694086, (5, 694081)),
    (694088, (7, 694081)),
    (694090, (3, 694087)),
    (694092, (5, 694087)),
    (694094, (3, 694091)),
    (694096, (5, 694091)),
    (694098, (7, 694091)),
    (694100, (13, 694087)),
    (694102, (11, 694091)),
    (694104, (13, 694091)),
    (694106, (19, 694087)),
    (694108, (17, 694091)),
    (694110, (19, 694091)),
    (694112, (31, 694081)),
    (694114, (23, 694091)),
    (694116, (29, 694087)),
    (694118, (31, 694087)),
    (694120, (29, 694091)),
    (694122, (31, 694091)),
    (694124, (37, 694087)),
    (694126, (3, 694123)),
    (694128, (5, 694123)),
    (694130, (7, 694123)),
    (694132, (41, 694091)),
    (694134, (11, 694123)),
    (694136, (13, 694123)),
    (694138, (47, 694091)),
    (694140, (17, 694123)),
    (694142, (19, 694123)),
    (694144, (53, 694091)),
    (694146, (23, 694123)),
    (694148, (61, 694087)),
    (694150, (59, 694091)),
    (694152, (29, 694123)),
    (694154, (31, 694123)),
    (694156, (137, 694019)),
    (694158, (67, 694091)),
    (694160, (37, 694123)),
    (694162, (71, 694091)),
    (694164, (41, 694123)),
    (694166, (43, 694123)),
    (694168, (89, 694079)),
    (694170, (47, 694123)),
    (694172, (103, 694069)),
    (694174, (83, 694091)),
    (694176, (53, 694123)),
    (694178, (97, 694081)),
    (694180, (89, 694091)),
    (694182, (59, 694123)),
    (694184, (61, 694123)),
    (694186, (107, 694079)),
    (694188, (97, 694091)),
    (694190, (67, 694123)),
    (694192, (3, 694189)),
    (694194, (5, 694189)),
    (694196, (3, 694193)),
    (694198, (5, 694193)),
    (694200, (7, 694193)),
    (694202, (13, 694189)),
    (694204, (3, 694201)),
    (694206, (5, 694201)),
    (694208, (7, 694201)),
    (694210, (3, 694207)),
    (694212, (5, 694207)),
    (694214, (7, 694207)),
    (694216, (23, 694193)),
    (694218, (11, 694207)),
    (694220, (13, 694207)),
    (694222, (29, 694193)),
    (694224, (17, 694207)),
    (694226, (3, 694223)),
    (694228, (5, 694223)),
    (694230, (7, 694223)),
    (694232, (31, 694201)),
    (694234, (11, 694223)),
    (694236, (13, 694223)),
    (694238, (31, 694207)),
    (694240, (17, 694223)),
    (694242, (19, 694223)),
    (694244, (37, 694207)),
    (694246, (23, 694223)),
    (694248, (41, 694207)),
    (694250, (43, 694207)),
    (694252, (29, 694223)),
    (694254, (31, 694223)),
    (694256, (67, 694189)),
    (694258, (167, 694091)),
    (694260, (37, 694223)),
    (694262, (3, 694259)),
    (694264, (3, 694261)),
    (694266, (5, 694261)),
    (694268, (7, 694261)),
    (694270, (11, 694259)),
    (694272, (11, 694261)),
    (694274, (3, 694271)),
    (694276, (3, 694273)),
    (694278, (5, 694273)),
    (694280, (3, 694277)),
    (694282, (5, 694277)),
    (694284, (7, 694277))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk069_r_verified
