/-
AUTOGENERATED (soundness mode): Chunk [55714..55950]
    Source: chunk_005.json  •  SHA256(JSON): 98e6fe9729f3859ee223f306392e3c84ecce76794dc2c1cd961ddf014ff1fea5
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk005_y_verified

noncomputable section

def nLo : Nat := 55714
def nHi : Nat := 55950
def dataSHA256 : String := "98e6fe9729f3859ee223f306392e3c84ecce76794dc2c1cd961ddf014ff1fea5"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (55714, (3, 55711)),
    (55716, (5, 55711)),
    (55718, (7, 55711)),
    (55720, (3, 55717)),
    (55722, (5, 55717)),
    (55724, (3, 55721)),
    (55726, (5, 55721)),
    (55728, (7, 55721)),
    (55730, (13, 55717)),
    (55732, (11, 55721)),
    (55734, (13, 55721)),
    (55736, (3, 55733)),
    (55738, (5, 55733)),
    (55740, (7, 55733)),
    (55742, (31, 55711)),
    (55744, (11, 55733)),
    (55746, (13, 55733)),
    (55748, (31, 55717)),
    (55750, (17, 55733)),
    (55752, (19, 55733)),
    (55754, (37, 55717)),
    (55756, (23, 55733)),
    (55758, (37, 55721)),
    (55760, (43, 55717)),
    (55762, (29, 55733)),
    (55764, (31, 55733)),
    (55766, (3, 55763)),
    (55768, (5, 55763)),
    (55770, (7, 55763)),
    (55772, (61, 55711)),
    (55774, (11, 55763)),
    (55776, (13, 55763)),
    (55778, (61, 55717)),
    (55780, (17, 55763)),
    (55782, (19, 55763)),
    (55784, (67, 55717)),
    (55786, (23, 55763)),
    (55788, (67, 55721)),
    (55790, (3, 55787)),
    (55792, (5, 55787)),
    (55794, (7, 55787)),
    (55796, (3, 55793)),
    (55798, (5, 55793)),
    (55800, (7, 55793)),
    (55802, (3, 55799)),
    (55804, (5, 55799)),
    (55806, (7, 55799)),
    (55808, (97, 55711)),
    (55810, (3, 55807)),
    (55812, (5, 55807)),
    (55814, (7, 55807)),
    (55816, (3, 55813)),
    (55818, (5, 55813)),
    (55820, (3, 55817)),
    (55822, (3, 55819)),
    (55824, (5, 55819)),
    (55826, (3, 55823)),
    (55828, (5, 55823)),
    (55830, (7, 55823)),
    (55832, (3, 55829)),
    (55834, (5, 55829)),
    (55836, (7, 55829)),
    (55838, (19, 55819)),
    (55840, (3, 55837)),
    (55842, (5, 55837)),
    (55844, (7, 55837)),
    (55846, (3, 55843)),
    (55848, (5, 55843)),
    (55850, (7, 55843)),
    (55852, (3, 55849)),
    (55854, (5, 55849)),
    (55856, (7, 55849)),
    (55858, (29, 55829)),
    (55860, (11, 55849)),
    (55862, (13, 55849)),
    (55864, (41, 55823)),
    (55866, (17, 55849)),
    (55868, (19, 55849)),
    (55870, (41, 55829)),
    (55872, (23, 55849)),
    (55874, (3, 55871)),
    (55876, (5, 55871)),
    (55878, (7, 55871)),
    (55880, (31, 55849)),
    (55882, (11, 55871)),
    (55884, (13, 55871)),
    (55886, (37, 55849)),
    (55888, (17, 55871)),
    (55890, (19, 55871)),
    (55892, (3, 55889)),
    (55894, (5, 55889)),
    (55896, (7, 55889)),
    (55898, (61, 55837)),
    (55900, (3, 55897)),
    (55902, (5, 55897)),
    (55904, (3, 55901)),
    (55906, (3, 55903)),
    (55908, (5, 55903)),
    (55910, (7, 55903)),
    (55912, (11, 55901)),
    (55914, (11, 55903)),
    (55916, (13, 55903)),
    (55918, (17, 55901)),
    (55920, (17, 55903)),
    (55922, (19, 55903)),
    (55924, (3, 55921)),
    (55926, (5, 55921)),
    (55928, (7, 55921)),
    (55930, (3, 55927)),
    (55932, (5, 55927)),
    (55934, (3, 55931)),
    (55936, (3, 55933)),
    (55938, (5, 55933)),
    (55940, (7, 55933)),
    (55942, (11, 55931)),
    (55944, (11, 55933)),
    (55946, (13, 55933)),
    (55948, (17, 55931)),
    (55950, (17, 55933))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk005_y_verified
