/-
AUTOGENERATED (soundness mode): Chunk [177142..177378]
    Source: chunk_017.json  •  SHA256(JSON): eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk017_ae_verified

noncomputable section

def nLo : Nat := 177142
def nHi : Nat := 177378
def dataSHA256 : String := "eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (177142, (11, 177131)),
    (177144, (13, 177131)),
    (177146, (19, 177127)),
    (177148, (17, 177131)),
    (177150, (19, 177131)),
    (177152, (43, 177109)),
    (177154, (23, 177131)),
    (177156, (29, 177127)),
    (177158, (31, 177127)),
    (177160, (29, 177131)),
    (177162, (31, 177131)),
    (177164, (37, 177127)),
    (177166, (53, 177113)),
    (177168, (37, 177131)),
    (177170, (3, 177167)),
    (177172, (5, 177167)),
    (177174, (7, 177167)),
    (177176, (3, 177173)),
    (177178, (5, 177173)),
    (177180, (7, 177173)),
    (177182, (73, 177109)),
    (177184, (11, 177173)),
    (177186, (13, 177173)),
    (177188, (61, 177127)),
    (177190, (17, 177173)),
    (177192, (19, 177173)),
    (177194, (67, 177127)),
    (177196, (23, 177173)),
    (177198, (31, 177167)),
    (177200, (73, 177127)),
    (177202, (29, 177173)),
    (177204, (31, 177173)),
    (177206, (79, 177127)),
    (177208, (41, 177167)),
    (177210, (37, 177173)),
    (177212, (3, 177209)),
    (177214, (3, 177211)),
    (177216, (5, 177211)),
    (177218, (7, 177211)),
    (177220, (3, 177217)),
    (177222, (5, 177217)),
    (177224, (7, 177217)),
    (177226, (3, 177223)),
    (177228, (5, 177223)),
    (177230, (7, 177223)),
    (177232, (23, 177209)),
    (177234, (11, 177223)),
    (177236, (13, 177223)),
    (177238, (29, 177209)),
    (177240, (17, 177223)),
    (177242, (3, 177239)),
    (177244, (5, 177239)),
    (177246, (7, 177239)),
    (177248, (31, 177217)),
    (177250, (11, 177239)),
    (177252, (13, 177239)),
    (177254, (31, 177223)),
    (177256, (17, 177239)),
    (177258, (19, 177239)),
    (177260, (3, 177257)),
    (177262, (5, 177257)),
    (177264, (7, 177257)),
    (177266, (43, 177223)),
    (177268, (11, 177257)),
    (177270, (13, 177257)),
    (177272, (3, 177269)),
    (177274, (5, 177269)),
    (177276, (7, 177269)),
    (177278, (61, 177217)),
    (177280, (11, 177269)),
    (177282, (13, 177269)),
    (177284, (61, 177223)),
    (177286, (3, 177283)),
    (177288, (5, 177283)),
    (177290, (7, 177283)),
    (177292, (23, 177269)),
    (177294, (11, 177283)),
    (177296, (13, 177283)),
    (177298, (29, 177269)),
    (177300, (17, 177283)),
    (177302, (19, 177283)),
    (177304, (3, 177301)),
    (177306, (5, 177301)),
    (177308, (7, 177301)),
    (177310, (41, 177269)),
    (177312, (11, 177301)),
    (177314, (13, 177301)),
    (177316, (47, 177269)),
    (177318, (17, 177301)),
    (177320, (19, 177301)),
    (177322, (3, 177319)),
    (177324, (5, 177319)),
    (177326, (3, 177323)),
    (177328, (5, 177323)),
    (177330, (7, 177323)),
    (177332, (13, 177319)),
    (177334, (11, 177323)),
    (177336, (13, 177323)),
    (177338, (19, 177319)),
    (177340, (3, 177337)),
    (177342, (5, 177337)),
    (177344, (7, 177337)),
    (177346, (23, 177323)),
    (177348, (11, 177337)),
    (177350, (3, 177347)),
    (177352, (5, 177347)),
    (177354, (7, 177347)),
    (177356, (19, 177337)),
    (177358, (11, 177347)),
    (177360, (13, 177347)),
    (177362, (43, 177319)),
    (177364, (17, 177347)),
    (177366, (19, 177347)),
    (177368, (31, 177337)),
    (177370, (23, 177347)),
    (177372, (53, 177319)),
    (177374, (37, 177337)),
    (177376, (29, 177347)),
    (177378, (31, 177347))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk017_ae_verified
