/-
AUTOGENERATED (soundness mode): Chunk [71430..71666]
    Source: chunk_007.json  •  SHA256(JSON): 63db77e46b4ea6bf87d9de9cd5c74a2c5769730ab6807bd0e46262e543bb69fa
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk007_g_verified

noncomputable section

def nLo : Nat := 71430
def nHi : Nat := 71666
def dataSHA256 : String := "63db77e46b4ea6bf87d9de9cd5c74a2c5769730ab6807bd0e46262e543bb69fa"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (71430, (11, 71419)),
    (71432, (3, 71429)),
    (71434, (5, 71429)),
    (71436, (7, 71429)),
    (71438, (19, 71419)),
    (71440, (3, 71437)),
    (71442, (5, 71437)),
    (71444, (7, 71437)),
    (71446, (3, 71443)),
    (71448, (5, 71443)),
    (71450, (7, 71443)),
    (71452, (23, 71429)),
    (71454, (11, 71443)),
    (71456, (3, 71453)),
    (71458, (5, 71453)),
    (71460, (7, 71453)),
    (71462, (19, 71443)),
    (71464, (11, 71453)),
    (71466, (13, 71453)),
    (71468, (31, 71437)),
    (71470, (17, 71453)),
    (71472, (19, 71453)),
    (71474, (3, 71471)),
    (71476, (3, 71473)),
    (71478, (5, 71473)),
    (71480, (7, 71473)),
    (71482, (3, 71479)),
    (71484, (5, 71479)),
    (71486, (3, 71483)),
    (71488, (5, 71483)),
    (71490, (7, 71483)),
    (71492, (13, 71479)),
    (71494, (11, 71483)),
    (71496, (13, 71483)),
    (71498, (19, 71479)),
    (71500, (17, 71483)),
    (71502, (19, 71483)),
    (71504, (31, 71473)),
    (71506, (3, 71503)),
    (71508, (5, 71503)),
    (71510, (7, 71503)),
    (71512, (29, 71483)),
    (71514, (11, 71503)),
    (71516, (13, 71503)),
    (71518, (47, 71471)),
    (71520, (17, 71503)),
    (71522, (19, 71503)),
    (71524, (41, 71483)),
    (71526, (23, 71503)),
    (71528, (109, 71419)),
    (71530, (3, 71527)),
    (71532, (5, 71527)),
    (71534, (7, 71527)),
    (71536, (53, 71483)),
    (71538, (11, 71527)),
    (71540, (3, 71537)),
    (71542, (5, 71537)),
    (71544, (7, 71537)),
    (71546, (19, 71527)),
    (71548, (11, 71537)),
    (71550, (13, 71537)),
    (71552, (3, 71549)),
    (71554, (3, 71551)),
    (71556, (5, 71551)),
    (71558, (7, 71551)),
    (71560, (11, 71549)),
    (71562, (11, 71551)),
    (71564, (13, 71551)),
    (71566, (3, 71563)),
    (71568, (5, 71563)),
    (71570, (7, 71563)),
    (71572, (3, 71569)),
    (71574, (5, 71569)),
    (71576, (7, 71569)),
    (71578, (29, 71549)),
    (71580, (11, 71569)),
    (71582, (13, 71569)),
    (71584, (47, 71537)),
    (71586, (17, 71569)),
    (71588, (19, 71569)),
    (71590, (41, 71549)),
    (71592, (23, 71569)),
    (71594, (31, 71563)),
    (71596, (3, 71593)),
    (71598, (5, 71593)),
    (71600, (3, 71597)),
    (71602, (5, 71597)),
    (71604, (7, 71597)),
    (71606, (13, 71593)),
    (71608, (11, 71597)),
    (71610, (13, 71597)),
    (71612, (19, 71593)),
    (71614, (17, 71597)),
    (71616, (19, 71597)),
    (71618, (67, 71551)),
    (71620, (23, 71597)),
    (71622, (29, 71593)),
    (71624, (31, 71593)),
    (71626, (29, 71597)),
    (71628, (31, 71597)),
    (71630, (37, 71593)),
    (71632, (83, 71549)),
    (71634, (37, 71597)),
    (71636, (3, 71633)),
    (71638, (5, 71633)),
    (71640, (7, 71633)),
    (71642, (73, 71569)),
    (71644, (11, 71633)),
    (71646, (13, 71633)),
    (71648, (79, 71569)),
    (71650, (3, 71647)),
    (71652, (5, 71647)),
    (71654, (7, 71647)),
    (71656, (23, 71633)),
    (71658, (11, 71647)),
    (71660, (13, 71647)),
    (71662, (29, 71633)),
    (71664, (17, 71647)),
    (71666, (3, 71663))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk007_g_verified
