/-
AUTOGENERATED (soundness mode): Chunk [206190..206426]
    Source: chunk_020.json  •  SHA256(JSON): f98289d997d2a6f2ba635d42ab130e17f081ab3f41ea554eba664d5a4caed00d
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk020_aa_verified

noncomputable section

def nLo : Nat := 206190
def nHi : Nat := 206426
def dataSHA256 : String := "f98289d997d2a6f2ba635d42ab130e17f081ab3f41ea554eba664d5a4caed00d"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (206190, (7, 206183)),
    (206192, (13, 206179)),
    (206194, (3, 206191)),
    (206196, (5, 206191)),
    (206198, (7, 206191)),
    (206200, (3, 206197)),
    (206202, (5, 206197)),
    (206204, (7, 206197)),
    (206206, (3, 206203)),
    (206208, (5, 206203)),
    (206210, (7, 206203)),
    (206212, (3, 206209)),
    (206214, (5, 206209)),
    (206216, (7, 206209)),
    (206218, (41, 206177)),
    (206220, (11, 206209)),
    (206222, (13, 206209)),
    (206224, (3, 206221)),
    (206226, (5, 206221)),
    (206228, (7, 206221)),
    (206230, (47, 206183)),
    (206232, (11, 206221)),
    (206234, (13, 206221)),
    (206236, (3, 206233)),
    (206238, (5, 206233)),
    (206240, (3, 206237)),
    (206242, (5, 206237)),
    (206244, (7, 206237)),
    (206246, (13, 206233)),
    (206248, (11, 206237)),
    (206250, (13, 206237)),
    (206252, (3, 206249)),
    (206254, (3, 206251)),
    (206256, (5, 206251)),
    (206258, (7, 206251)),
    (206260, (11, 206249)),
    (206262, (11, 206251)),
    (206264, (13, 206251)),
    (206266, (3, 206263)),
    (206268, (5, 206263)),
    (206270, (7, 206263)),
    (206272, (23, 206249)),
    (206274, (11, 206263)),
    (206276, (3, 206273)),
    (206278, (5, 206273)),
    (206280, (7, 206273)),
    (206282, (3, 206279)),
    (206284, (3, 206281)),
    (206286, (5, 206281)),
    (206288, (7, 206281)),
    (206290, (11, 206279)),
    (206292, (11, 206281)),
    (206294, (3, 206291)),
    (206296, (5, 206291)),
    (206298, (7, 206291)),
    (206300, (19, 206281)),
    (206302, (3, 206299)),
    (206304, (5, 206299)),
    (206306, (3, 206303)),
    (206308, (5, 206303)),
    (206310, (7, 206303)),
    (206312, (13, 206299)),
    (206314, (11, 206303)),
    (206316, (13, 206303)),
    (206318, (19, 206299)),
    (206320, (17, 206303)),
    (206322, (19, 206303)),
    (206324, (43, 206281)),
    (206326, (23, 206303)),
    (206328, (29, 206299)),
    (206330, (31, 206299)),
    (206332, (29, 206303)),
    (206334, (31, 206303)),
    (206336, (37, 206299)),
    (206338, (47, 206291)),
    (206340, (37, 206303)),
    (206342, (43, 206299)),
    (206344, (3, 206341)),
    (206346, (5, 206341)),
    (206348, (7, 206341)),
    (206350, (3, 206347)),
    (206352, (5, 206347)),
    (206354, (3, 206351)),
    (206356, (5, 206351)),
    (206358, (7, 206351)),
    (206360, (13, 206347)),
    (206362, (11, 206351)),
    (206364, (13, 206351)),
    (206366, (19, 206347)),
    (206368, (17, 206351)),
    (206370, (19, 206351)),
    (206372, (3, 206369)),
    (206374, (5, 206369)),
    (206376, (7, 206369)),
    (206378, (31, 206347)),
    (206380, (11, 206369)),
    (206382, (13, 206369)),
    (206384, (37, 206347)),
    (206386, (3, 206383)),
    (206388, (5, 206383)),
    (206390, (7, 206383)),
    (206392, (23, 206369)),
    (206394, (11, 206383)),
    (206396, (13, 206383)),
    (206398, (29, 206369)),
    (206400, (17, 206383)),
    (206402, (3, 206399)),
    (206404, (5, 206399)),
    (206406, (7, 206399)),
    (206408, (61, 206347)),
    (206410, (3, 206407)),
    (206412, (5, 206407)),
    (206414, (3, 206411)),
    (206416, (3, 206413)),
    (206418, (5, 206413)),
    (206420, (7, 206413)),
    (206422, (3, 206419)),
    (206424, (5, 206419)),
    (206426, (7, 206419))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk020_aa_verified
