/-
AUTOGENERATED (soundness mode): Chunk [851668..851904]
    Source: chunk_085.json  •  SHA256(JSON): 83a8dd18f55176f84a81a6f523a2d9d327b8478302636c3193480c11c3b25718
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk085_h_verified

noncomputable section

def nLo : Nat := 851668
def nHi : Nat := 851904
def dataSHA256 : String := "83a8dd18f55176f84a81a6f523a2d9d327b8478302636c3193480c11c3b25718"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (851668, (29, 851639)),
    (851670, (11, 851659)),
    (851672, (13, 851659)),
    (851674, (3, 851671)),
    (851676, (5, 851671)),
    (851678, (7, 851671)),
    (851680, (3, 851677)),
    (851682, (5, 851677)),
    (851684, (7, 851677)),
    (851686, (47, 851639)),
    (851688, (11, 851677)),
    (851690, (13, 851677)),
    (851692, (3, 851689)),
    (851694, (5, 851689)),
    (851696, (7, 851689)),
    (851698, (59, 851639)),
    (851700, (11, 851689)),
    (851702, (13, 851689)),
    (851704, (71, 851633)),
    (851706, (17, 851689)),
    (851708, (19, 851689)),
    (851710, (71, 851639)),
    (851712, (23, 851689)),
    (851714, (37, 851677)),
    (851716, (83, 851633)),
    (851718, (29, 851689)),
    (851720, (31, 851689)),
    (851722, (83, 851639)),
    (851724, (47, 851677)),
    (851726, (3, 851723)),
    (851728, (5, 851723)),
    (851730, (7, 851723)),
    (851732, (43, 851689)),
    (851734, (3, 851731)),
    (851736, (5, 851731)),
    (851738, (7, 851731)),
    (851740, (17, 851723)),
    (851742, (11, 851731)),
    (851744, (13, 851731)),
    (851746, (23, 851723)),
    (851748, (17, 851731)),
    (851750, (19, 851731)),
    (851752, (3, 851749)),
    (851754, (5, 851749)),
    (851756, (7, 851749)),
    (851758, (239, 851519)),
    (851760, (11, 851749)),
    (851762, (13, 851749)),
    (851764, (3, 851761)),
    (851766, (5, 851761)),
    (851768, (7, 851761)),
    (851770, (47, 851723)),
    (851772, (11, 851761)),
    (851774, (13, 851761)),
    (851776, (53, 851723)),
    (851778, (17, 851761)),
    (851780, (19, 851761)),
    (851782, (59, 851723)),
    (851784, (23, 851761)),
    (851786, (37, 851749)),
    (851788, (149, 851639)),
    (851790, (29, 851761)),
    (851792, (31, 851761)),
    (851794, (71, 851723)),
    (851796, (47, 851749)),
    (851798, (37, 851761)),
    (851800, (3, 851797)),
    (851802, (5, 851797)),
    (851804, (3, 851801)),
    (851806, (3, 851803)),
    (851808, (5, 851803)),
    (851810, (7, 851803)),
    (851812, (11, 851801)),
    (851814, (11, 851803)),
    (851816, (3, 851813)),
    (851818, (5, 851813)),
    (851820, (7, 851813)),
    (851822, (19, 851803)),
    (851824, (3, 851821)),
    (851826, (5, 851821)),
    (851828, (7, 851821)),
    (851830, (17, 851813)),
    (851832, (11, 851821)),
    (851834, (3, 851831)),
    (851836, (5, 851831)),
    (851838, (7, 851831)),
    (851840, (19, 851821)),
    (851842, (3, 851839)),
    (851844, (5, 851839)),
    (851846, (3, 851843)),
    (851848, (5, 851843)),
    (851850, (7, 851843)),
    (851852, (13, 851839)),
    (851854, (11, 851843)),
    (851856, (13, 851843)),
    (851858, (19, 851839)),
    (851860, (17, 851843)),
    (851862, (19, 851843)),
    (851864, (43, 851821)),
    (851866, (3, 851863)),
    (851868, (5, 851863)),
    (851870, (7, 851863)),
    (851872, (29, 851843)),
    (851874, (11, 851863)),
    (851876, (13, 851863)),
    (851878, (47, 851831)),
    (851880, (17, 851863)),
    (851882, (19, 851863)),
    (851884, (3, 851881)),
    (851886, (5, 851881)),
    (851888, (7, 851881)),
    (851890, (47, 851843)),
    (851892, (11, 851881)),
    (851894, (3, 851891)),
    (851896, (5, 851891)),
    (851898, (7, 851891)),
    (851900, (19, 851881)),
    (851902, (3, 851899)),
    (851904, (5, 851899))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk085_h_verified
