/-
AUTOGENERATED (soundness mode): Chunk [803334..803570]
    Source: chunk_080.json  •  SHA256(JSON): 7368325e45c25fc7cfdcd2b1de7598ad0c1be39504c96d152647dedf711e5a7f
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk080_o_verified

noncomputable section

def nLo : Nat := 803334
def nHi : Nat := 803570
def dataSHA256 : String := "7368325e45c25fc7cfdcd2b1de7598ad0c1be39504c96d152647dedf711e5a7f"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (803334, (11, 803323)),
    (803336, (3, 803333)),
    (803338, (5, 803333)),
    (803340, (7, 803333)),
    (803342, (19, 803323)),
    (803344, (11, 803333)),
    (803346, (13, 803333)),
    (803348, (37, 803311)),
    (803350, (3, 803347)),
    (803352, (5, 803347)),
    (803354, (7, 803347)),
    (803356, (23, 803333)),
    (803358, (11, 803347)),
    (803360, (13, 803347)),
    (803362, (3, 803359)),
    (803364, (5, 803359)),
    (803366, (7, 803359)),
    (803368, (131, 803237)),
    (803370, (11, 803359)),
    (803372, (13, 803359)),
    (803374, (41, 803333)),
    (803376, (17, 803359)),
    (803378, (19, 803359)),
    (803380, (47, 803333)),
    (803382, (23, 803359)),
    (803384, (37, 803347)),
    (803386, (53, 803333)),
    (803388, (29, 803359)),
    (803390, (31, 803359)),
    (803392, (3, 803389)),
    (803394, (5, 803389)),
    (803396, (3, 803393)),
    (803398, (5, 803393)),
    (803400, (7, 803393)),
    (803402, (3, 803399)),
    (803404, (5, 803399)),
    (803406, (7, 803399)),
    (803408, (19, 803389)),
    (803410, (11, 803399)),
    (803412, (13, 803399)),
    (803414, (67, 803347)),
    (803416, (17, 803399)),
    (803418, (19, 803399)),
    (803420, (3, 803417)),
    (803422, (5, 803417)),
    (803424, (7, 803417)),
    (803426, (37, 803389)),
    (803428, (11, 803417)),
    (803430, (13, 803417)),
    (803432, (43, 803389)),
    (803434, (17, 803417)),
    (803436, (19, 803417)),
    (803438, (79, 803359)),
    (803440, (23, 803417)),
    (803442, (43, 803399)),
    (803444, (3, 803441)),
    (803446, (3, 803443)),
    (803448, (5, 803443)),
    (803450, (3, 803447)),
    (803452, (3, 803449)),
    (803454, (5, 803449)),
    (803456, (7, 803449)),
    (803458, (11, 803447)),
    (803460, (11, 803449)),
    (803462, (13, 803449)),
    (803464, (3, 803461)),
    (803466, (5, 803461)),
    (803468, (7, 803461)),
    (803470, (23, 803447)),
    (803472, (11, 803461)),
    (803474, (13, 803461)),
    (803476, (29, 803447)),
    (803478, (17, 803461)),
    (803480, (19, 803461)),
    (803482, (3, 803479)),
    (803484, (5, 803479)),
    (803486, (3, 803483)),
    (803488, (5, 803483)),
    (803490, (7, 803483)),
    (803492, (13, 803479)),
    (803494, (11, 803483)),
    (803496, (13, 803483)),
    (803498, (19, 803479)),
    (803500, (3, 803497)),
    (803502, (5, 803497)),
    (803504, (3, 803501)),
    (803506, (5, 803501)),
    (803508, (7, 803501)),
    (803510, (13, 803497)),
    (803512, (11, 803501)),
    (803514, (13, 803501)),
    (803516, (3, 803513)),
    (803518, (5, 803513)),
    (803520, (7, 803513)),
    (803522, (3, 803519)),
    (803524, (5, 803519)),
    (803526, (7, 803519)),
    (803528, (31, 803497)),
    (803530, (11, 803519)),
    (803532, (13, 803519)),
    (803534, (37, 803497)),
    (803536, (17, 803519)),
    (803538, (19, 803519)),
    (803540, (43, 803497)),
    (803542, (23, 803519)),
    (803544, (31, 803513)),
    (803546, (67, 803479)),
    (803548, (29, 803519)),
    (803550, (31, 803519)),
    (803552, (3, 803549)),
    (803554, (5, 803549)),
    (803556, (7, 803549)),
    (803558, (61, 803497)),
    (803560, (11, 803549)),
    (803562, (13, 803549)),
    (803564, (67, 803497)),
    (803566, (17, 803549)),
    (803568, (19, 803549)),
    (803570, (73, 803497))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk080_o_verified
