/-
AUTOGENERATED (soundness mode): Chunk [8572..8808]
    Source: chunk_000.json  •  SHA256(JSON): a6a29acdb462de51e9134ab266cdc99e38dc09d82e2cad379a4791829d2b4c20
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
open Goldbach.Base

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk000_ak_verified

noncomputable section

def nLo : Nat := 8572
def nHi : Nat := 8808
def dataSHA256 : String := "a6a29acdb462de51e9134ab266cdc99e38dc09d82e2cad379a4791829d2b4c20"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (8572, (29, 8543)),
    (8574, (11, 8563)),
    (8576, (3, 8573)),
    (8578, (5, 8573)),
    (8580, (7, 8573)),
    (8582, (19, 8563)),
    (8584, (3, 8581)),
    (8586, (5, 8581)),
    (8588, (7, 8581)),
    (8590, (17, 8573)),
    (8592, (11, 8581)),
    (8594, (13, 8581)),
    (8596, (23, 8573)),
    (8598, (17, 8581)),
    (8600, (3, 8597)),
    (8602, (3, 8599)),
    (8604, (5, 8599)),
    (8606, (7, 8599)),
    (8608, (11, 8597)),
    (8610, (11, 8599)),
    (8612, (3, 8609)),
    (8614, (5, 8609)),
    (8616, (7, 8609)),
    (8618, (19, 8599)),
    (8620, (11, 8609)),
    (8622, (13, 8609)),
    (8624, (43, 8581)),
    (8626, (3, 8623)),
    (8628, (5, 8623)),
    (8630, (3, 8627)),
    (8632, (3, 8629)),
    (8634, (5, 8629)),
    (8636, (7, 8629)),
    (8638, (11, 8627)),
    (8640, (11, 8629)),
    (8642, (13, 8629)),
    (8644, (3, 8641)),
    (8646, (5, 8641)),
    (8648, (7, 8641)),
    (8650, (3, 8647)),
    (8652, (5, 8647)),
    (8654, (7, 8647)),
    (8656, (29, 8627)),
    (8658, (11, 8647)),
    (8660, (13, 8647)),
    (8662, (53, 8609)),
    (8664, (17, 8647)),
    (8666, (3, 8663)),
    (8668, (5, 8663)),
    (8670, (7, 8663)),
    (8672, (3, 8669)),
    (8674, (5, 8669)),
    (8676, (7, 8669)),
    (8678, (31, 8647)),
    (8680, (3, 8677)),
    (8682, (5, 8677)),
    (8684, (3, 8681)),
    (8686, (5, 8681)),
    (8688, (7, 8681)),
    (8690, (13, 8677)),
    (8692, (3, 8689)),
    (8694, (5, 8689)),
    (8696, (3, 8693)),
    (8698, (5, 8693)),
    (8700, (7, 8693)),
    (8702, (3, 8699)),
    (8704, (5, 8699)),
    (8706, (7, 8699)),
    (8708, (19, 8689)),
    (8710, (3, 8707)),
    (8712, (5, 8707)),
    (8714, (7, 8707)),
    (8716, (3, 8713)),
    (8718, (5, 8713)),
    (8720, (7, 8713)),
    (8722, (3, 8719)),
    (8724, (5, 8719)),
    (8726, (7, 8719)),
    (8728, (29, 8699)),
    (8730, (11, 8719)),
    (8732, (13, 8719)),
    (8734, (3, 8731)),
    (8736, (5, 8731)),
    (8738, (7, 8731)),
    (8740, (3, 8737)),
    (8742, (5, 8737)),
    (8744, (3, 8741)),
    (8746, (5, 8741)),
    (8748, (7, 8741)),
    (8750, (3, 8747)),
    (8752, (5, 8747)),
    (8754, (7, 8747)),
    (8756, (3, 8753)),
    (8758, (5, 8753)),
    (8760, (7, 8753)),
    (8762, (31, 8731)),
    (8764, (3, 8761)),
    (8766, (5, 8761)),
    (8768, (7, 8761)),
    (8770, (17, 8753)),
    (8772, (11, 8761)),
    (8774, (13, 8761)),
    (8776, (23, 8753)),
    (8778, (17, 8761)),
    (8780, (19, 8761)),
    (8782, (3, 8779)),
    (8784, (5, 8779)),
    (8786, (3, 8783)),
    (8788, (5, 8783)),
    (8790, (7, 8783)),
    (8792, (13, 8779)),
    (8794, (11, 8783)),
    (8796, (13, 8783)),
    (8798, (19, 8779)),
    (8800, (17, 8783)),
    (8802, (19, 8783)),
    (8804, (43, 8761)),
    (8806, (3, 8803)),
    (8808, (5, 8803))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

end

end Goldbach.FiniteBase.Chunks.Chunk000_ak_verified
