/-
AUTOGENERATED (soundness mode): Chunk [34286..34522]
    Source: chunk_003.json  •  SHA256(JSON): aa0b0d345944a61eed39c2656d885fa63910d347d39ef96cec78db7c98646c16
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk003_s_verified

noncomputable section

def nLo : Nat := 34286
def nHi : Nat := 34522
def dataSHA256 : String := "aa0b0d345944a61eed39c2656d885fa63910d347d39ef96cec78db7c98646c16"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (34286, (3, 34283)),
    (34288, (5, 34283)),
    (34290, (7, 34283)),
    (34292, (19, 34273)),
    (34294, (11, 34283)),
    (34296, (13, 34283)),
    (34298, (31, 34267)),
    (34300, (3, 34297)),
    (34302, (5, 34297)),
    (34304, (3, 34301)),
    (34306, (3, 34303)),
    (34308, (5, 34303)),
    (34310, (7, 34303)),
    (34312, (11, 34301)),
    (34314, (11, 34303)),
    (34316, (3, 34313)),
    (34318, (5, 34313)),
    (34320, (7, 34313)),
    (34322, (3, 34319)),
    (34324, (5, 34319)),
    (34326, (7, 34319)),
    (34328, (31, 34297)),
    (34330, (3, 34327)),
    (34332, (5, 34327)),
    (34334, (7, 34327)),
    (34336, (17, 34319)),
    (34338, (11, 34327)),
    (34340, (3, 34337)),
    (34342, (5, 34337)),
    (34344, (7, 34337)),
    (34346, (19, 34327)),
    (34348, (11, 34337)),
    (34350, (13, 34337)),
    (34352, (79, 34273)),
    (34354, (3, 34351)),
    (34356, (5, 34351)),
    (34358, (7, 34351)),
    (34360, (23, 34337)),
    (34362, (11, 34351)),
    (34364, (3, 34361)),
    (34366, (5, 34361)),
    (34368, (7, 34361)),
    (34370, (3, 34367)),
    (34372, (3, 34369)),
    (34374, (5, 34369)),
    (34376, (7, 34369)),
    (34378, (11, 34367)),
    (34380, (11, 34369)),
    (34382, (13, 34369)),
    (34384, (3, 34381)),
    (34386, (5, 34381)),
    (34388, (7, 34381)),
    (34390, (23, 34367)),
    (34392, (11, 34381)),
    (34394, (13, 34381)),
    (34396, (29, 34367)),
    (34398, (17, 34381)),
    (34400, (19, 34381)),
    (34402, (41, 34361)),
    (34404, (23, 34381)),
    (34406, (3, 34403)),
    (34408, (5, 34403)),
    (34410, (7, 34403)),
    (34412, (31, 34381)),
    (34414, (11, 34403)),
    (34416, (13, 34403)),
    (34418, (37, 34381)),
    (34420, (17, 34403)),
    (34422, (19, 34403)),
    (34424, (3, 34421)),
    (34426, (5, 34421)),
    (34428, (7, 34421)),
    (34430, (61, 34369)),
    (34432, (3, 34429)),
    (34434, (5, 34429)),
    (34436, (7, 34429)),
    (34438, (17, 34421)),
    (34440, (11, 34429)),
    (34442, (3, 34439)),
    (34444, (5, 34439)),
    (34446, (7, 34439)),
    (34448, (19, 34429)),
    (34450, (11, 34439)),
    (34452, (13, 34439)),
    (34454, (73, 34381)),
    (34456, (17, 34439)),
    (34458, (19, 34439)),
    (34460, (3, 34457)),
    (34462, (5, 34457)),
    (34464, (7, 34457)),
    (34466, (37, 34429)),
    (34468, (11, 34457)),
    (34470, (13, 34457)),
    (34472, (3, 34469)),
    (34474, (3, 34471)),
    (34476, (5, 34471)),
    (34478, (7, 34471)),
    (34480, (11, 34469)),
    (34482, (11, 34471)),
    (34484, (13, 34471)),
    (34486, (3, 34483)),
    (34488, (5, 34483)),
    (34490, (3, 34487)),
    (34492, (5, 34487)),
    (34494, (7, 34487)),
    (34496, (13, 34483)),
    (34498, (11, 34487)),
    (34500, (13, 34487)),
    (34502, (3, 34499)),
    (34504, (3, 34501)),
    (34506, (5, 34501)),
    (34508, (7, 34501)),
    (34510, (11, 34499)),
    (34512, (11, 34501)),
    (34514, (3, 34511)),
    (34516, (3, 34513)),
    (34518, (5, 34513)),
    (34520, (7, 34513)),
    (34522, (3, 34519))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk003_s_verified
