/-
AUTOGENERATED (soundness mode): Chunk [257380..257616]
    Source: chunk_025.json  •  SHA256(JSON): f249f4e2da073cfe1af142d14170278e708dba4699cb7fda427c8d521f17fadf
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk025_af_verified

noncomputable section

def nLo : Nat := 257380
def nHi : Nat := 257616
def dataSHA256 : String := "f249f4e2da073cfe1af142d14170278e708dba4699cb7fda427c8d521f17fadf"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (257380, (29, 257351)),
    (257382, (11, 257371)),
    (257384, (3, 257381)),
    (257386, (5, 257381)),
    (257388, (7, 257381)),
    (257390, (19, 257371)),
    (257392, (11, 257381)),
    (257394, (13, 257381)),
    (257396, (43, 257353)),
    (257398, (17, 257381)),
    (257400, (19, 257381)),
    (257402, (3, 257399)),
    (257404, (3, 257401)),
    (257406, (5, 257401)),
    (257408, (7, 257401)),
    (257410, (3, 257407)),
    (257412, (5, 257407)),
    (257414, (7, 257407)),
    (257416, (17, 257399)),
    (257418, (11, 257407)),
    (257420, (13, 257407)),
    (257422, (23, 257399)),
    (257424, (17, 257407)),
    (257426, (19, 257407)),
    (257428, (29, 257399)),
    (257430, (23, 257407)),
    (257432, (31, 257401)),
    (257434, (53, 257381)),
    (257436, (29, 257407)),
    (257438, (31, 257407)),
    (257440, (3, 257437)),
    (257442, (5, 257437)),
    (257444, (7, 257437)),
    (257446, (3, 257443)),
    (257448, (5, 257443)),
    (257450, (3, 257447)),
    (257452, (5, 257447)),
    (257454, (7, 257447)),
    (257456, (13, 257443)),
    (257458, (11, 257447)),
    (257460, (13, 257447)),
    (257462, (3, 257459)),
    (257464, (5, 257459)),
    (257466, (7, 257459)),
    (257468, (31, 257437)),
    (257470, (11, 257459)),
    (257472, (13, 257459)),
    (257474, (31, 257443)),
    (257476, (3, 257473)),
    (257478, (5, 257473)),
    (257480, (7, 257473)),
    (257482, (23, 257459)),
    (257484, (11, 257473)),
    (257486, (13, 257473)),
    (257488, (29, 257459)),
    (257490, (17, 257473)),
    (257492, (3, 257489)),
    (257494, (5, 257489)),
    (257496, (7, 257489)),
    (257498, (61, 257437)),
    (257500, (3, 257497)),
    (257502, (5, 257497)),
    (257504, (3, 257501)),
    (257506, (3, 257503)),
    (257508, (5, 257503)),
    (257510, (7, 257503)),
    (257512, (11, 257501)),
    (257514, (11, 257503)),
    (257516, (13, 257503)),
    (257518, (17, 257501)),
    (257520, (17, 257503)),
    (257522, (3, 257519)),
    (257524, (5, 257519)),
    (257526, (7, 257519)),
    (257528, (31, 257497)),
    (257530, (11, 257519)),
    (257532, (13, 257519)),
    (257534, (31, 257503)),
    (257536, (17, 257519)),
    (257538, (19, 257519)),
    (257540, (37, 257503)),
    (257542, (3, 257539)),
    (257544, (5, 257539)),
    (257546, (7, 257539)),
    (257548, (29, 257519)),
    (257550, (11, 257539)),
    (257552, (13, 257539)),
    (257554, (53, 257501)),
    (257556, (17, 257539)),
    (257558, (19, 257539)),
    (257560, (41, 257519)),
    (257562, (23, 257539)),
    (257564, (3, 257561)),
    (257566, (5, 257561)),
    (257568, (7, 257561)),
    (257570, (31, 257539)),
    (257572, (11, 257561)),
    (257574, (13, 257561)),
    (257576, (37, 257539)),
    (257578, (17, 257561)),
    (257580, (19, 257561)),
    (257582, (43, 257539)),
    (257584, (23, 257561)),
    (257586, (47, 257539)),
    (257588, (151, 257437)),
    (257590, (29, 257561)),
    (257592, (31, 257561)),
    (257594, (3, 257591)),
    (257596, (5, 257591)),
    (257598, (7, 257591)),
    (257600, (61, 257539)),
    (257602, (11, 257591)),
    (257604, (13, 257591)),
    (257606, (67, 257539)),
    (257608, (17, 257591)),
    (257610, (19, 257591)),
    (257612, (73, 257539)),
    (257614, (3, 257611)),
    (257616, (5, 257611))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk025_af_verified
