/-
AUTOGENERATED (soundness mode): Chunk [894048..894284]
    Source: chunk_089.json  •  SHA256(JSON): 9348aa9afd6dad771c9cf1f581b4b2f0df9111f563aaa2e2864f722957ab995f
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk089_r_verified

noncomputable section

def nLo : Nat := 894048
def nHi : Nat := 894284
def dataSHA256 : String := "9348aa9afd6dad771c9cf1f581b4b2f0df9111f563aaa2e2864f722957ab995f"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (894048, (11, 894037)),
    (894050, (13, 894037)),
    (894052, (41, 894011)),
    (894054, (17, 894037)),
    (894056, (19, 894037)),
    (894058, (47, 894011)),
    (894060, (23, 894037)),
    (894062, (3, 894059)),
    (894064, (5, 894059)),
    (894066, (7, 894059)),
    (894068, (31, 894037)),
    (894070, (3, 894067)),
    (894072, (5, 894067)),
    (894074, (7, 894067)),
    (894076, (3, 894073)),
    (894078, (5, 894073)),
    (894080, (7, 894073)),
    (894082, (23, 894059)),
    (894084, (11, 894073)),
    (894086, (13, 894073)),
    (894088, (29, 894059)),
    (894090, (17, 894073)),
    (894092, (19, 894073)),
    (894094, (83, 894011)),
    (894096, (23, 894073)),
    (894098, (31, 894067)),
    (894100, (3, 894097)),
    (894102, (5, 894097)),
    (894104, (7, 894097)),
    (894106, (47, 894059)),
    (894108, (11, 894097)),
    (894110, (13, 894097)),
    (894112, (3, 894109)),
    (894114, (5, 894109)),
    (894116, (7, 894109)),
    (894118, (59, 894059)),
    (894120, (11, 894109)),
    (894122, (3, 894119)),
    (894124, (5, 894119)),
    (894126, (7, 894119)),
    (894128, (19, 894109)),
    (894130, (11, 894119)),
    (894132, (13, 894119)),
    (894134, (37, 894097)),
    (894136, (17, 894119)),
    (894138, (19, 894119)),
    (894140, (3, 894137)),
    (894142, (3, 894139)),
    (894144, (5, 894139)),
    (894146, (7, 894139)),
    (894148, (11, 894137)),
    (894150, (11, 894139)),
    (894152, (13, 894139)),
    (894154, (3, 894151)),
    (894156, (5, 894151)),
    (894158, (7, 894151)),
    (894160, (23, 894137)),
    (894162, (11, 894151)),
    (894164, (3, 894161)),
    (894166, (5, 894161)),
    (894168, (7, 894161)),
    (894170, (3, 894167)),
    (894172, (5, 894167)),
    (894174, (7, 894167)),
    (894176, (37, 894139)),
    (894178, (11, 894167)),
    (894180, (13, 894167)),
    (894182, (31, 894151)),
    (894184, (3, 894181)),
    (894186, (5, 894181)),
    (894188, (7, 894181)),
    (894190, (23, 894167)),
    (894192, (11, 894181)),
    (894194, (3, 894191)),
    (894196, (3, 894193)),
    (894198, (5, 894193)),
    (894200, (7, 894193)),
    (894202, (11, 894191)),
    (894204, (11, 894193)),
    (894206, (3, 894203)),
    (894208, (5, 894203)),
    (894210, (7, 894203)),
    (894212, (3, 894209)),
    (894214, (3, 894211)),
    (894216, (5, 894211)),
    (894218, (7, 894211)),
    (894220, (11, 894209)),
    (894222, (11, 894211)),
    (894224, (3, 894221)),
    (894226, (5, 894221)),
    (894228, (7, 894221)),
    (894230, (3, 894227)),
    (894232, (5, 894227)),
    (894234, (7, 894227)),
    (894236, (3, 894233)),
    (894238, (5, 894233)),
    (894240, (7, 894233)),
    (894242, (3, 894239)),
    (894244, (5, 894239)),
    (894246, (7, 894239)),
    (894248, (37, 894211)),
    (894250, (3, 894247)),
    (894252, (5, 894247)),
    (894254, (7, 894247)),
    (894256, (17, 894239)),
    (894258, (11, 894247)),
    (894260, (13, 894247)),
    (894262, (3, 894259)),
    (894264, (5, 894259)),
    (894266, (7, 894259)),
    (894268, (29, 894239)),
    (894270, (11, 894259)),
    (894272, (13, 894259)),
    (894274, (41, 894233)),
    (894276, (17, 894259)),
    (894278, (19, 894259)),
    (894280, (3, 894277)),
    (894282, (5, 894277)),
    (894284, (3, 894281))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk089_r_verified
