/-
AUTOGENERATED (soundness mode): Chunk [676666..676902]
    Source: chunk_067.json  •  SHA256(JSON): 8b0ff1f698230063b40e73d2e55c7562e4466c8fd163a717c2363cf5b70c8ca1
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk067_ac_verified

noncomputable section

def nLo : Nat := 676666
def nHi : Nat := 676902
def dataSHA256 : String := "8b0ff1f698230063b40e73d2e55c7562e4466c8fd163a717c2363cf5b70c8ca1"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (676666, (5, 676661)),
    (676668, (7, 676661)),
    (676670, (73, 676597)),
    (676672, (11, 676661)),
    (676674, (13, 676661)),
    (676676, (79, 676597)),
    (676678, (17, 676661)),
    (676680, (19, 676661)),
    (676682, (3, 676679)),
    (676684, (5, 676679)),
    (676686, (7, 676679)),
    (676688, (277, 676411)),
    (676690, (11, 676679)),
    (676692, (13, 676679)),
    (676694, (97, 676597)),
    (676696, (17, 676679)),
    (676698, (19, 676679)),
    (676700, (103, 676597)),
    (676702, (23, 676679)),
    (676704, (43, 676661)),
    (676706, (3, 676703)),
    (676708, (5, 676703)),
    (676710, (7, 676703)),
    (676712, (139, 676573)),
    (676714, (11, 676703)),
    (676716, (13, 676703)),
    (676718, (307, 676411)),
    (676720, (3, 676717)),
    (676722, (5, 676717)),
    (676724, (3, 676721)),
    (676726, (5, 676721)),
    (676728, (7, 676721)),
    (676730, (3, 676727)),
    (676732, (5, 676727)),
    (676734, (7, 676727)),
    (676736, (3, 676733)),
    (676738, (5, 676733)),
    (676740, (7, 676733)),
    (676742, (331, 676411)),
    (676744, (11, 676733)),
    (676746, (13, 676733)),
    (676748, (31, 676717)),
    (676750, (3, 676747)),
    (676752, (5, 676747)),
    (676754, (3, 676751)),
    (676756, (5, 676751)),
    (676758, (7, 676751)),
    (676760, (13, 676747)),
    (676762, (11, 676751)),
    (676764, (13, 676751)),
    (676766, (3, 676763)),
    (676768, (5, 676763)),
    (676770, (7, 676763)),
    (676772, (199, 676573)),
    (676774, (3, 676771)),
    (676776, (5, 676771)),
    (676778, (7, 676771)),
    (676780, (17, 676763)),
    (676782, (11, 676771)),
    (676784, (13, 676771)),
    (676786, (23, 676763)),
    (676788, (17, 676771)),
    (676790, (19, 676771)),
    (676792, (29, 676763)),
    (676794, (23, 676771)),
    (676796, (79, 676717)),
    (676798, (47, 676751)),
    (676800, (29, 676771)),
    (676802, (31, 676771)),
    (676804, (41, 676763)),
    (676806, (43, 676763)),
    (676808, (37, 676771)),
    (676810, (3, 676807)),
    (676812, (5, 676807)),
    (676814, (7, 676807)),
    (676816, (53, 676763)),
    (676818, (11, 676807)),
    (676820, (13, 676807)),
    (676822, (59, 676763)),
    (676824, (17, 676807)),
    (676826, (19, 676807)),
    (676828, (101, 676727)),
    (676830, (23, 676807)),
    (676832, (3, 676829)),
    (676834, (5, 676829)),
    (676836, (7, 676829)),
    (676838, (31, 676807)),
    (676840, (11, 676829)),
    (676842, (13, 676829)),
    (676844, (37, 676807)),
    (676846, (17, 676829)),
    (676848, (19, 676829)),
    (676850, (43, 676807)),
    (676852, (23, 676829)),
    (676854, (47, 676807)),
    (676856, (109, 676747)),
    (676858, (29, 676829)),
    (676860, (31, 676829)),
    (676862, (3, 676859)),
    (676864, (3, 676861)),
    (676866, (5, 676861)),
    (676868, (7, 676861)),
    (676870, (11, 676859)),
    (676872, (11, 676861)),
    (676874, (13, 676861)),
    (676876, (17, 676859)),
    (676878, (17, 676861)),
    (676880, (19, 676861)),
    (676882, (23, 676859)),
    (676884, (23, 676861)),
    (676886, (3, 676883)),
    (676888, (5, 676883)),
    (676890, (7, 676883)),
    (676892, (31, 676861)),
    (676894, (3, 676891)),
    (676896, (5, 676891)),
    (676898, (7, 676891)),
    (676900, (17, 676883)),
    (676902, (11, 676891))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk067_ac_verified
