/-
AUTOGENERATED (soundness mode): Chunk [75000..75236]
    Source: chunk_007.json  •  SHA256(JSON): 63db77e46b4ea6bf87d9de9cd5c74a2c5769730ab6807bd0e46262e543bb69fa
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk007_v_verified

noncomputable section

def nLo : Nat := 75000
def nHi : Nat := 75236
def dataSHA256 : String := "63db77e46b4ea6bf87d9de9cd5c74a2c5769730ab6807bd0e46262e543bb69fa"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (75000, (41, 74959)),
    (75002, (43, 74959)),
    (75004, (71, 74933)),
    (75006, (47, 74959)),
    (75008, (67, 74941)),
    (75010, (107, 74903)),
    (75012, (53, 74959)),
    (75014, (3, 75011)),
    (75016, (3, 75013)),
    (75018, (5, 75013)),
    (75020, (3, 75017)),
    (75022, (5, 75017)),
    (75024, (7, 75017)),
    (75026, (13, 75013)),
    (75028, (11, 75017)),
    (75030, (13, 75017)),
    (75032, (3, 75029)),
    (75034, (5, 75029)),
    (75036, (7, 75029)),
    (75038, (79, 74959)),
    (75040, (3, 75037)),
    (75042, (5, 75037)),
    (75044, (3, 75041)),
    (75046, (5, 75041)),
    (75048, (7, 75041)),
    (75050, (13, 75037)),
    (75052, (11, 75041)),
    (75054, (13, 75041)),
    (75056, (19, 75037)),
    (75058, (17, 75041)),
    (75060, (19, 75041)),
    (75062, (103, 74959)),
    (75064, (23, 75041)),
    (75066, (29, 75037)),
    (75068, (31, 75037)),
    (75070, (29, 75041)),
    (75072, (31, 75041)),
    (75074, (37, 75037)),
    (75076, (47, 75029)),
    (75078, (37, 75041)),
    (75080, (43, 75037)),
    (75082, (3, 75079)),
    (75084, (5, 75079)),
    (75086, (3, 75083)),
    (75088, (5, 75083)),
    (75090, (7, 75083)),
    (75092, (13, 75079)),
    (75094, (11, 75083)),
    (75096, (13, 75083)),
    (75098, (19, 75079)),
    (75100, (17, 75083)),
    (75102, (19, 75083)),
    (75104, (67, 75037)),
    (75106, (23, 75083)),
    (75108, (29, 75079)),
    (75110, (31, 75079)),
    (75112, (3, 75109)),
    (75114, (5, 75109)),
    (75116, (7, 75109)),
    (75118, (89, 75029)),
    (75120, (11, 75109)),
    (75122, (13, 75109)),
    (75124, (41, 75083)),
    (75126, (17, 75109)),
    (75128, (19, 75109)),
    (75130, (47, 75083)),
    (75132, (23, 75109)),
    (75134, (97, 75037)),
    (75136, (3, 75133)),
    (75138, (5, 75133)),
    (75140, (7, 75133)),
    (75142, (59, 75083)),
    (75144, (11, 75133)),
    (75146, (13, 75133)),
    (75148, (107, 75041)),
    (75150, (17, 75133)),
    (75152, (3, 75149)),
    (75154, (5, 75149)),
    (75156, (7, 75149)),
    (75158, (79, 75079)),
    (75160, (11, 75149)),
    (75162, (13, 75149)),
    (75164, (3, 75161)),
    (75166, (5, 75161)),
    (75168, (7, 75161)),
    (75170, (3, 75167)),
    (75172, (3, 75169)),
    (75174, (5, 75169)),
    (75176, (7, 75169)),
    (75178, (11, 75167)),
    (75180, (11, 75169)),
    (75182, (13, 75169)),
    (75184, (3, 75181)),
    (75186, (5, 75181)),
    (75188, (7, 75181)),
    (75190, (23, 75167)),
    (75192, (11, 75181)),
    (75194, (13, 75181)),
    (75196, (3, 75193)),
    (75198, (5, 75193)),
    (75200, (7, 75193)),
    (75202, (41, 75161)),
    (75204, (11, 75193)),
    (75206, (13, 75193)),
    (75208, (41, 75167)),
    (75210, (17, 75193)),
    (75212, (3, 75209)),
    (75214, (3, 75211)),
    (75216, (5, 75211)),
    (75218, (7, 75211)),
    (75220, (3, 75217)),
    (75222, (5, 75217)),
    (75224, (7, 75217)),
    (75226, (3, 75223)),
    (75228, (5, 75223)),
    (75230, (3, 75227)),
    (75232, (5, 75227)),
    (75234, (7, 75227)),
    (75236, (13, 75223))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk007_v_verified
