/-
AUTOGENERATED (soundness mode): Chunk [654524..654760]
    Source: chunk_065.json  •  SHA256(JSON): c01205f6fa580d2523db26684c1f5fc776d6bd47d68042ec2b08492668ee552f
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk065_t_verified

noncomputable section

def nLo : Nat := 654524
def nHi : Nat := 654760
def dataSHA256 : String := "c01205f6fa580d2523db26684c1f5fc776d6bd47d68042ec2b08492668ee552f"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (654524, (97, 654427)),
    (654526, (17, 654509)),
    (654528, (19, 654509)),
    (654530, (3, 654527)),
    (654532, (3, 654529)),
    (654534, (5, 654529)),
    (654536, (7, 654529)),
    (654538, (11, 654527)),
    (654540, (11, 654529)),
    (654542, (3, 654539)),
    (654544, (3, 654541)),
    (654546, (5, 654541)),
    (654548, (7, 654541)),
    (654550, (11, 654539)),
    (654552, (11, 654541)),
    (654554, (13, 654541)),
    (654556, (3, 654553)),
    (654558, (5, 654553)),
    (654560, (7, 654553)),
    (654562, (23, 654539)),
    (654564, (11, 654553)),
    (654566, (13, 654553)),
    (654568, (29, 654539)),
    (654570, (17, 654553)),
    (654572, (19, 654553)),
    (654574, (3, 654571)),
    (654576, (5, 654571)),
    (654578, (7, 654571)),
    (654580, (41, 654539)),
    (654582, (11, 654571)),
    (654584, (13, 654571)),
    (654586, (47, 654539)),
    (654588, (17, 654571)),
    (654590, (3, 654587)),
    (654592, (5, 654587)),
    (654594, (7, 654587)),
    (654596, (3, 654593)),
    (654598, (5, 654593)),
    (654600, (7, 654593)),
    (654602, (31, 654571)),
    (654604, (3, 654601)),
    (654606, (5, 654601)),
    (654608, (7, 654601)),
    (654610, (17, 654593)),
    (654612, (11, 654601)),
    (654614, (3, 654611)),
    (654616, (3, 654613)),
    (654618, (5, 654613)),
    (654620, (7, 654613)),
    (654622, (11, 654611)),
    (654624, (11, 654613)),
    (654626, (3, 654623)),
    (654628, (5, 654623)),
    (654630, (7, 654623)),
    (654632, (3, 654629)),
    (654634, (5, 654629)),
    (654636, (7, 654629)),
    (654638, (37, 654601)),
    (654640, (11, 654629)),
    (654642, (13, 654629)),
    (654644, (31, 654613)),
    (654646, (17, 654629)),
    (654648, (19, 654629)),
    (654650, (37, 654613)),
    (654652, (23, 654629)),
    (654654, (31, 654623)),
    (654656, (43, 654613)),
    (654658, (29, 654629)),
    (654660, (31, 654629)),
    (654662, (61, 654601)),
    (654664, (41, 654623)),
    (654666, (37, 654629)),
    (654668, (67, 654601)),
    (654670, (41, 654629)),
    (654672, (43, 654629)),
    (654674, (3, 654671)),
    (654676, (5, 654671)),
    (654678, (7, 654671)),
    (654680, (67, 654613)),
    (654682, (3, 654679)),
    (654684, (5, 654679)),
    (654686, (7, 654679)),
    (654688, (17, 654671)),
    (654690, (11, 654679)),
    (654692, (13, 654679)),
    (654694, (23, 654671)),
    (654696, (17, 654679)),
    (654698, (19, 654679)),
    (654700, (3, 654697)),
    (654702, (5, 654697)),
    (654704, (3, 654701)),
    (654706, (5, 654701)),
    (654708, (7, 654701)),
    (654710, (13, 654697)),
    (654712, (11, 654701)),
    (654714, (13, 654701)),
    (654716, (19, 654697)),
    (654718, (17, 654701)),
    (654720, (19, 654701)),
    (654722, (43, 654679)),
    (654724, (23, 654701)),
    (654726, (29, 654697)),
    (654728, (31, 654697)),
    (654730, (3, 654727)),
    (654732, (5, 654727)),
    (654734, (7, 654727)),
    (654736, (107, 654629)),
    (654738, (11, 654727)),
    (654740, (13, 654727)),
    (654742, (3, 654739)),
    (654744, (5, 654739)),
    (654746, (3, 654743)),
    (654748, (5, 654743)),
    (654750, (7, 654743)),
    (654752, (3, 654749)),
    (654754, (5, 654749)),
    (654756, (7, 654749)),
    (654758, (19, 654739)),
    (654760, (11, 654749))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk065_t_verified
