/-
AUTOGENERATED (soundness mode): Chunk [468570..468806]
    Source: chunk_046.json  •  SHA256(JSON): 0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk046_ak_verified

noncomputable section

def nLo : Nat := 468570
def nHi : Nat := 468806
def dataSHA256 : String := "0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (468570, (13, 468557)),
    (468572, (73, 468499)),
    (468574, (17, 468557)),
    (468576, (19, 468557)),
    (468578, (79, 468499)),
    (468580, (3, 468577)),
    (468582, (5, 468577)),
    (468584, (3, 468581)),
    (468586, (5, 468581)),
    (468588, (7, 468581)),
    (468590, (13, 468577)),
    (468592, (11, 468581)),
    (468594, (13, 468581)),
    (468596, (3, 468593)),
    (468598, (5, 468593)),
    (468600, (7, 468593)),
    (468602, (3, 468599)),
    (468604, (5, 468599)),
    (468606, (7, 468599)),
    (468608, (31, 468577)),
    (468610, (11, 468599)),
    (468612, (13, 468599)),
    (468614, (37, 468577)),
    (468616, (3, 468613)),
    (468618, (5, 468613)),
    (468620, (7, 468613)),
    (468622, (3, 468619)),
    (468624, (5, 468619)),
    (468626, (3, 468623)),
    (468628, (5, 468623)),
    (468630, (7, 468623)),
    (468632, (13, 468619)),
    (468634, (11, 468623)),
    (468636, (13, 468623)),
    (468638, (19, 468619)),
    (468640, (17, 468623)),
    (468642, (19, 468623)),
    (468644, (3, 468641)),
    (468646, (5, 468641)),
    (468648, (7, 468641)),
    (468650, (3, 468647)),
    (468652, (5, 468647)),
    (468654, (7, 468647)),
    (468656, (3, 468653)),
    (468658, (5, 468653)),
    (468660, (7, 468653)),
    (468662, (43, 468619)),
    (468664, (3, 468661)),
    (468666, (5, 468661)),
    (468668, (7, 468661)),
    (468670, (3, 468667)),
    (468672, (5, 468667)),
    (468674, (7, 468667)),
    (468676, (23, 468653)),
    (468678, (11, 468667)),
    (468680, (13, 468667)),
    (468682, (29, 468653)),
    (468684, (17, 468667)),
    (468686, (3, 468683)),
    (468688, (5, 468683)),
    (468690, (7, 468683)),
    (468692, (31, 468661)),
    (468694, (3, 468691)),
    (468696, (5, 468691)),
    (468698, (7, 468691)),
    (468700, (3, 468697)),
    (468702, (5, 468697)),
    (468704, (7, 468697)),
    (468706, (3, 468703)),
    (468708, (5, 468703)),
    (468710, (7, 468703)),
    (468712, (3, 468709)),
    (468714, (5, 468709)),
    (468716, (7, 468709)),
    (468718, (71, 468647)),
    (468720, (11, 468709)),
    (468722, (3, 468719)),
    (468724, (5, 468719)),
    (468726, (7, 468719)),
    (468728, (19, 468709)),
    (468730, (11, 468719)),
    (468732, (13, 468719)),
    (468734, (31, 468703)),
    (468736, (17, 468719)),
    (468738, (19, 468719)),
    (468740, (3, 468737)),
    (468742, (3, 468739)),
    (468744, (5, 468739)),
    (468746, (7, 468739)),
    (468748, (11, 468737)),
    (468750, (11, 468739)),
    (468752, (13, 468739)),
    (468754, (17, 468737)),
    (468756, (17, 468739)),
    (468758, (19, 468739)),
    (468760, (23, 468737)),
    (468762, (23, 468739)),
    (468764, (3, 468761)),
    (468766, (5, 468761)),
    (468768, (7, 468761)),
    (468770, (31, 468739)),
    (468772, (11, 468761)),
    (468774, (13, 468761)),
    (468776, (3, 468773)),
    (468778, (5, 468773)),
    (468780, (7, 468773)),
    (468782, (43, 468739)),
    (468784, (3, 468781)),
    (468786, (5, 468781)),
    (468788, (7, 468781)),
    (468790, (17, 468773)),
    (468792, (11, 468781)),
    (468794, (13, 468781)),
    (468796, (23, 468773)),
    (468798, (17, 468781)),
    (468800, (19, 468781)),
    (468802, (29, 468773)),
    (468804, (23, 468781)),
    (468806, (3, 468803))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk046_ak_verified
