/-
AUTOGENERATED (soundness mode): Chunk [667618..667854]
    Source: chunk_066.json  •  SHA256(JSON): cb6e64899a951d5d7365a8802758b2670a5de3aa0ff86c0ce4bdb64939ae6d44
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk066_ag_verified

noncomputable section

def nLo : Nat := 667618
def nHi : Nat := 667854
def dataSHA256 : String := "cb6e64899a951d5d7365a8802758b2670a5de3aa0ff86c0ce4bdb64939ae6d44"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (667618, (41, 667577)),
    (667620, (43, 667577)),
    (667622, (61, 667561)),
    (667624, (47, 667577)),
    (667626, (67, 667559)),
    (667628, (67, 667561)),
    (667630, (53, 667577)),
    (667632, (71, 667561)),
    (667634, (3, 667631)),
    (667636, (5, 667631)),
    (667638, (7, 667631)),
    (667640, (79, 667561)),
    (667642, (11, 667631)),
    (667644, (13, 667631)),
    (667646, (3, 667643)),
    (667648, (5, 667643)),
    (667650, (7, 667643)),
    (667652, (3, 667649)),
    (667654, (5, 667649)),
    (667656, (7, 667649)),
    (667658, (97, 667561)),
    (667660, (3, 667657)),
    (667662, (5, 667657)),
    (667664, (7, 667657)),
    (667666, (17, 667649)),
    (667668, (11, 667657)),
    (667670, (13, 667657)),
    (667672, (23, 667649)),
    (667674, (17, 667657)),
    (667676, (3, 667673)),
    (667678, (5, 667673)),
    (667680, (7, 667673)),
    (667682, (151, 667531)),
    (667684, (11, 667673)),
    (667686, (13, 667673)),
    (667688, (31, 667657)),
    (667690, (3, 667687)),
    (667692, (5, 667687)),
    (667694, (3, 667691)),
    (667696, (5, 667691)),
    (667698, (7, 667691)),
    (667700, (3, 667697)),
    (667702, (3, 667699)),
    (667704, (5, 667699)),
    (667706, (7, 667699)),
    (667708, (11, 667697)),
    (667710, (11, 667699)),
    (667712, (13, 667699)),
    (667714, (17, 667697)),
    (667716, (17, 667699)),
    (667718, (19, 667699)),
    (667720, (23, 667697)),
    (667722, (23, 667699)),
    (667724, (37, 667687)),
    (667726, (29, 667697)),
    (667728, (29, 667699)),
    (667730, (3, 667727)),
    (667732, (5, 667727)),
    (667734, (7, 667727)),
    (667736, (37, 667699)),
    (667738, (11, 667727)),
    (667740, (13, 667727)),
    (667742, (43, 667699)),
    (667744, (3, 667741)),
    (667746, (5, 667741)),
    (667748, (7, 667741)),
    (667750, (23, 667727)),
    (667752, (11, 667741)),
    (667754, (13, 667741)),
    (667756, (3, 667753)),
    (667758, (5, 667753)),
    (667760, (7, 667753)),
    (667762, (71, 667691)),
    (667764, (11, 667753)),
    (667766, (13, 667753)),
    (667768, (41, 667727)),
    (667770, (17, 667753)),
    (667772, (3, 667769)),
    (667774, (5, 667769)),
    (667776, (7, 667769)),
    (667778, (37, 667741)),
    (667780, (11, 667769)),
    (667782, (13, 667769)),
    (667784, (3, 667781)),
    (667786, (5, 667781)),
    (667788, (7, 667781)),
    (667790, (37, 667753)),
    (667792, (11, 667781)),
    (667794, (13, 667781)),
    (667796, (43, 667753)),
    (667798, (17, 667781)),
    (667800, (19, 667781)),
    (667802, (61, 667741)),
    (667804, (3, 667801)),
    (667806, (5, 667801)),
    (667808, (7, 667801)),
    (667810, (29, 667781)),
    (667812, (11, 667801)),
    (667814, (13, 667801)),
    (667816, (47, 667769)),
    (667818, (17, 667801)),
    (667820, (3, 667817)),
    (667822, (3, 667819)),
    (667824, (5, 667819)),
    (667826, (7, 667819)),
    (667828, (11, 667817)),
    (667830, (11, 667819)),
    (667832, (3, 667829)),
    (667834, (5, 667829)),
    (667836, (7, 667829)),
    (667838, (19, 667819)),
    (667840, (3, 667837)),
    (667842, (5, 667837)),
    (667844, (7, 667837)),
    (667846, (17, 667829)),
    (667848, (11, 667837)),
    (667850, (13, 667837)),
    (667852, (23, 667829)),
    (667854, (17, 667837))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk066_ag_verified
