/-
AUTOGENERATED (soundness mode): Chunk [338094..338330]
    Source: chunk_033.json  •  SHA256(JSON): c928ea0fe693ba876701a71f304c546ab87fdb7441284ddcd3103d4d1c58b4ec
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk033_ai_verified

noncomputable section

def nLo : Nat := 338094
def nHi : Nat := 338330
def dataSHA256 : String := "c928ea0fe693ba876701a71f304c546ab87fdb7441284ddcd3103d4d1c58b4ec"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (338094, (61, 338033)),
    (338096, (79, 338017)),
    (338098, (71, 338027)),
    (338100, (67, 338033)),
    (338102, (103, 337999)),
    (338104, (71, 338033)),
    (338106, (73, 338033)),
    (338108, (109, 337999)),
    (338110, (83, 338027)),
    (338112, (79, 338033)),
    (338114, (97, 338017)),
    (338116, (83, 338033)),
    (338118, (101, 338017)),
    (338120, (103, 338017)),
    (338122, (3, 338119)),
    (338124, (5, 338119)),
    (338126, (7, 338119)),
    (338128, (101, 338027)),
    (338130, (11, 338119)),
    (338132, (13, 338119)),
    (338134, (101, 338033)),
    (338136, (17, 338119)),
    (338138, (19, 338119)),
    (338140, (3, 338137)),
    (338142, (5, 338137)),
    (338144, (3, 338141)),
    (338146, (5, 338141)),
    (338148, (7, 338141)),
    (338150, (13, 338137)),
    (338152, (11, 338141)),
    (338154, (13, 338141)),
    (338156, (3, 338153)),
    (338158, (5, 338153)),
    (338160, (7, 338153)),
    (338162, (3, 338159)),
    (338164, (3, 338161)),
    (338166, (5, 338161)),
    (338168, (7, 338161)),
    (338170, (3, 338167)),
    (338172, (5, 338167)),
    (338174, (3, 338171)),
    (338176, (5, 338171)),
    (338178, (7, 338171)),
    (338180, (13, 338167)),
    (338182, (11, 338171)),
    (338184, (13, 338171)),
    (338186, (3, 338183)),
    (338188, (5, 338183)),
    (338190, (7, 338183)),
    (338192, (31, 338161)),
    (338194, (11, 338183)),
    (338196, (13, 338183)),
    (338198, (31, 338167)),
    (338200, (3, 338197)),
    (338202, (5, 338197)),
    (338204, (7, 338197)),
    (338206, (3, 338203)),
    (338208, (5, 338203)),
    (338210, (3, 338207)),
    (338212, (5, 338207)),
    (338214, (7, 338207)),
    (338216, (3, 338213)),
    (338218, (5, 338213)),
    (338220, (7, 338213)),
    (338222, (19, 338203)),
    (338224, (11, 338213)),
    (338226, (13, 338213)),
    (338228, (31, 338197)),
    (338230, (17, 338213)),
    (338232, (19, 338213)),
    (338234, (3, 338231)),
    (338236, (5, 338231)),
    (338238, (7, 338231)),
    (338240, (3, 338237)),
    (338242, (5, 338237)),
    (338244, (7, 338237)),
    (338246, (43, 338203)),
    (338248, (11, 338237)),
    (338250, (13, 338237)),
    (338252, (283, 337969)),
    (338254, (3, 338251)),
    (338256, (5, 338251)),
    (338258, (7, 338251)),
    (338260, (23, 338237)),
    (338262, (11, 338251)),
    (338264, (13, 338251)),
    (338266, (3, 338263)),
    (338268, (5, 338263)),
    (338270, (3, 338267)),
    (338272, (3, 338269)),
    (338274, (5, 338269)),
    (338276, (7, 338269)),
    (338278, (11, 338267)),
    (338280, (11, 338269)),
    (338282, (3, 338279)),
    (338284, (5, 338279)),
    (338286, (7, 338279)),
    (338288, (19, 338269)),
    (338290, (3, 338287)),
    (338292, (5, 338287)),
    (338294, (7, 338287)),
    (338296, (3, 338293)),
    (338298, (5, 338293)),
    (338300, (3, 338297)),
    (338302, (5, 338297)),
    (338304, (7, 338297)),
    (338306, (13, 338293)),
    (338308, (11, 338297)),
    (338310, (13, 338297)),
    (338312, (3, 338309)),
    (338314, (5, 338309)),
    (338316, (7, 338309)),
    (338318, (31, 338287)),
    (338320, (11, 338309)),
    (338322, (13, 338309)),
    (338324, (3, 338321)),
    (338326, (3, 338323)),
    (338328, (5, 338323)),
    (338330, (7, 338323))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk033_ai_verified
