/-
AUTOGENERATED (soundness mode): Chunk [468332..468568]
    Source: chunk_046.json  •  SHA256(JSON): 0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk046_aj_verified

noncomputable section

def nLo : Nat := 468332
def nHi : Nat := 468568
def dataSHA256 : String := "0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (468332, (13, 468319)),
    (468334, (11, 468323)),
    (468336, (13, 468323)),
    (468338, (19, 468319)),
    (468340, (17, 468323)),
    (468342, (19, 468323)),
    (468344, (67, 468277)),
    (468346, (23, 468323)),
    (468348, (29, 468319)),
    (468350, (31, 468319)),
    (468352, (29, 468323)),
    (468354, (31, 468323)),
    (468356, (3, 468353)),
    (468358, (5, 468353)),
    (468360, (7, 468353)),
    (468362, (3, 468359)),
    (468364, (5, 468359)),
    (468366, (7, 468359)),
    (468368, (79, 468289)),
    (468370, (11, 468359)),
    (468372, (13, 468359)),
    (468374, (3, 468371)),
    (468376, (5, 468371)),
    (468378, (7, 468371)),
    (468380, (61, 468319)),
    (468382, (11, 468371)),
    (468384, (13, 468371)),
    (468386, (67, 468319)),
    (468388, (17, 468371)),
    (468390, (19, 468371)),
    (468392, (3, 468389)),
    (468394, (5, 468389)),
    (468396, (7, 468389)),
    (468398, (79, 468319)),
    (468400, (11, 468389)),
    (468402, (13, 468389)),
    (468404, (127, 468277)),
    (468406, (17, 468389)),
    (468408, (19, 468389)),
    (468410, (139, 468271)),
    (468412, (23, 468389)),
    (468414, (43, 468371)),
    (468416, (97, 468319)),
    (468418, (29, 468389)),
    (468420, (31, 468389)),
    (468422, (103, 468319)),
    (468424, (3, 468421)),
    (468426, (5, 468421)),
    (468428, (7, 468421)),
    (468430, (41, 468389)),
    (468432, (11, 468421)),
    (468434, (13, 468421)),
    (468436, (47, 468389)),
    (468438, (17, 468421)),
    (468440, (19, 468421)),
    (468442, (3, 468439)),
    (468444, (5, 468439)),
    (468446, (7, 468439)),
    (468448, (59, 468389)),
    (468450, (11, 468439)),
    (468452, (13, 468439)),
    (468454, (3, 468451)),
    (468456, (5, 468451)),
    (468458, (7, 468451)),
    (468460, (71, 468389)),
    (468462, (11, 468451)),
    (468464, (13, 468451)),
    (468466, (3, 468463)),
    (468468, (5, 468463)),
    (468470, (7, 468463)),
    (468472, (83, 468389)),
    (468474, (11, 468463)),
    (468476, (3, 468473)),
    (468478, (5, 468473)),
    (468480, (7, 468473)),
    (468482, (19, 468463)),
    (468484, (11, 468473)),
    (468486, (13, 468473)),
    (468488, (37, 468451)),
    (468490, (17, 468473)),
    (468492, (19, 468473)),
    (468494, (3, 468491)),
    (468496, (3, 468493)),
    (468498, (5, 468493)),
    (468500, (7, 468493)),
    (468502, (3, 468499)),
    (468504, (5, 468499)),
    (468506, (7, 468499)),
    (468508, (17, 468491)),
    (468510, (11, 468499)),
    (468512, (3, 468509)),
    (468514, (5, 468509)),
    (468516, (7, 468509)),
    (468518, (19, 468499)),
    (468520, (11, 468509)),
    (468522, (13, 468509)),
    (468524, (31, 468493)),
    (468526, (17, 468509)),
    (468528, (19, 468509)),
    (468530, (3, 468527)),
    (468532, (5, 468527)),
    (468534, (7, 468527)),
    (468536, (37, 468499)),
    (468538, (11, 468527)),
    (468540, (13, 468527)),
    (468542, (43, 468499)),
    (468544, (17, 468527)),
    (468546, (19, 468527)),
    (468548, (97, 468451)),
    (468550, (23, 468527)),
    (468552, (43, 468509)),
    (468554, (3, 468551)),
    (468556, (5, 468551)),
    (468558, (7, 468551)),
    (468560, (3, 468557)),
    (468562, (5, 468557)),
    (468564, (7, 468557)),
    (468566, (67, 468499)),
    (468568, (11, 468557))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk046_aj_verified
