/-
AUTOGENERATED (soundness mode): Chunk [91192..91428]
    Source: chunk_009.json  •  SHA256(JSON): 0e78883f4e68e887cae4dc0c368998c92867bfbc6995620242fa8053446b10d4
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk009_f_verified

noncomputable section

def nLo : Nat := 91192
def nHi : Nat := 91428
def dataSHA256 : String := "0e78883f4e68e887cae4dc0c368998c92867bfbc6995620242fa8053446b10d4"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (91192, (29, 91163)),
    (91194, (11, 91183)),
    (91196, (3, 91193)),
    (91198, (5, 91193)),
    (91200, (7, 91193)),
    (91202, (3, 91199)),
    (91204, (5, 91199)),
    (91206, (7, 91199)),
    (91208, (67, 91141)),
    (91210, (11, 91199)),
    (91212, (13, 91199)),
    (91214, (31, 91183)),
    (91216, (17, 91199)),
    (91218, (19, 91199)),
    (91220, (37, 91183)),
    (91222, (23, 91199)),
    (91224, (31, 91193)),
    (91226, (43, 91183)),
    (91228, (29, 91199)),
    (91230, (31, 91199)),
    (91232, (3, 91229)),
    (91234, (5, 91229)),
    (91236, (7, 91229)),
    (91238, (79, 91159)),
    (91240, (3, 91237)),
    (91242, (5, 91237)),
    (91244, (7, 91237)),
    (91246, (3, 91243)),
    (91248, (5, 91243)),
    (91250, (7, 91243)),
    (91252, (3, 91249)),
    (91254, (5, 91249)),
    (91256, (3, 91253)),
    (91258, (5, 91253)),
    (91260, (7, 91253)),
    (91262, (13, 91249)),
    (91264, (11, 91253)),
    (91266, (13, 91253)),
    (91268, (19, 91249)),
    (91270, (17, 91253)),
    (91272, (19, 91253)),
    (91274, (31, 91243)),
    (91276, (23, 91253)),
    (91278, (29, 91249)),
    (91280, (31, 91249)),
    (91282, (29, 91253)),
    (91284, (31, 91253)),
    (91286, (3, 91283)),
    (91288, (5, 91283)),
    (91290, (7, 91283)),
    (91292, (43, 91249)),
    (91294, (3, 91291)),
    (91296, (5, 91291)),
    (91298, (7, 91291)),
    (91300, (3, 91297)),
    (91302, (5, 91297)),
    (91304, (7, 91297)),
    (91306, (3, 91303)),
    (91308, (5, 91303)),
    (91310, (7, 91303)),
    (91312, (3, 91309)),
    (91314, (5, 91309)),
    (91316, (7, 91309)),
    (91318, (89, 91229)),
    (91320, (11, 91309)),
    (91322, (13, 91309)),
    (91324, (41, 91283)),
    (91326, (17, 91309)),
    (91328, (19, 91309)),
    (91330, (47, 91283)),
    (91332, (23, 91309)),
    (91334, (3, 91331)),
    (91336, (5, 91331)),
    (91338, (7, 91331)),
    (91340, (31, 91309)),
    (91342, (11, 91331)),
    (91344, (13, 91331)),
    (91346, (37, 91309)),
    (91348, (17, 91331)),
    (91350, (19, 91331)),
    (91352, (43, 91309)),
    (91354, (23, 91331)),
    (91356, (47, 91309)),
    (91358, (61, 91297)),
    (91360, (29, 91331)),
    (91362, (31, 91331)),
    (91364, (61, 91303)),
    (91366, (83, 91283)),
    (91368, (37, 91331)),
    (91370, (3, 91367)),
    (91372, (3, 91369)),
    (91374, (5, 91369)),
    (91376, (3, 91373)),
    (91378, (5, 91373)),
    (91380, (7, 91373)),
    (91382, (13, 91369)),
    (91384, (3, 91381)),
    (91386, (5, 91381)),
    (91388, (7, 91381)),
    (91390, (3, 91387)),
    (91392, (5, 91387)),
    (91394, (7, 91387)),
    (91396, (3, 91393)),
    (91398, (5, 91393)),
    (91400, (3, 91397)),
    (91402, (5, 91397)),
    (91404, (7, 91397)),
    (91406, (13, 91393)),
    (91408, (11, 91397)),
    (91410, (13, 91397)),
    (91412, (19, 91393)),
    (91414, (3, 91411)),
    (91416, (5, 91411)),
    (91418, (7, 91411)),
    (91420, (23, 91397)),
    (91422, (11, 91411)),
    (91424, (13, 91411)),
    (91426, (3, 91423)),
    (91428, (5, 91423))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk009_f_verified
