/-
AUTOGENERATED (soundness mode): Chunk [10716..10952]
    Source: chunk_001.json  •  SHA256(JSON): 8d258a0b6848d2a48410ecf140829c3397d41e92ad9654236410c899854f0c14
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk001_d_verified

noncomputable section

def nLo : Nat := 10716
def nHi : Nat := 10952
def dataSHA256 : String := "8d258a0b6848d2a48410ecf140829c3397d41e92ad9654236410c899854f0c14"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (10716, (5, 10711)),
    (10718, (7, 10711)),
    (10720, (11, 10709)),
    (10722, (11, 10711)),
    (10724, (13, 10711)),
    (10726, (3, 10723)),
    (10728, (5, 10723)),
    (10730, (7, 10723)),
    (10732, (3, 10729)),
    (10734, (5, 10729)),
    (10736, (3, 10733)),
    (10738, (5, 10733)),
    (10740, (7, 10733)),
    (10742, (3, 10739)),
    (10744, (5, 10739)),
    (10746, (7, 10739)),
    (10748, (19, 10729)),
    (10750, (11, 10739)),
    (10752, (13, 10739)),
    (10754, (31, 10723)),
    (10756, (3, 10753)),
    (10758, (5, 10753)),
    (10760, (7, 10753)),
    (10762, (23, 10739)),
    (10764, (11, 10753)),
    (10766, (13, 10753)),
    (10768, (29, 10739)),
    (10770, (17, 10753)),
    (10772, (19, 10753)),
    (10774, (3, 10771)),
    (10776, (5, 10771)),
    (10778, (7, 10771)),
    (10780, (41, 10739)),
    (10782, (11, 10771)),
    (10784, (3, 10781)),
    (10786, (5, 10781)),
    (10788, (7, 10781)),
    (10790, (19, 10771)),
    (10792, (3, 10789)),
    (10794, (5, 10789)),
    (10796, (7, 10789)),
    (10798, (17, 10781)),
    (10800, (11, 10789)),
    (10802, (3, 10799)),
    (10804, (5, 10799)),
    (10806, (7, 10799)),
    (10808, (19, 10789)),
    (10810, (11, 10799)),
    (10812, (13, 10799)),
    (10814, (43, 10771)),
    (10816, (17, 10799)),
    (10818, (19, 10799)),
    (10820, (31, 10789)),
    (10822, (23, 10799)),
    (10824, (43, 10781)),
    (10826, (37, 10789)),
    (10828, (29, 10799)),
    (10830, (31, 10799)),
    (10832, (43, 10789)),
    (10834, (3, 10831)),
    (10836, (5, 10831)),
    (10838, (7, 10831)),
    (10840, (3, 10837)),
    (10842, (5, 10837)),
    (10844, (7, 10837)),
    (10846, (47, 10799)),
    (10848, (11, 10837)),
    (10850, (3, 10847)),
    (10852, (5, 10847)),
    (10854, (7, 10847)),
    (10856, (3, 10853)),
    (10858, (5, 10853)),
    (10860, (7, 10853)),
    (10862, (3, 10859)),
    (10864, (3, 10861)),
    (10866, (5, 10861)),
    (10868, (7, 10861)),
    (10870, (3, 10867)),
    (10872, (5, 10867)),
    (10874, (7, 10867)),
    (10876, (17, 10859)),
    (10878, (11, 10867)),
    (10880, (13, 10867)),
    (10882, (23, 10859)),
    (10884, (17, 10867)),
    (10886, (3, 10883)),
    (10888, (5, 10883)),
    (10890, (7, 10883)),
    (10892, (3, 10889)),
    (10894, (3, 10891)),
    (10896, (5, 10891)),
    (10898, (7, 10891)),
    (10900, (11, 10889)),
    (10902, (11, 10891)),
    (10904, (13, 10891)),
    (10906, (3, 10903)),
    (10908, (5, 10903)),
    (10910, (7, 10903)),
    (10912, (3, 10909)),
    (10914, (5, 10909)),
    (10916, (7, 10909)),
    (10918, (29, 10889)),
    (10920, (11, 10909)),
    (10922, (13, 10909)),
    (10924, (41, 10883)),
    (10926, (17, 10909)),
    (10928, (19, 10909)),
    (10930, (41, 10889)),
    (10932, (23, 10909)),
    (10934, (31, 10903)),
    (10936, (47, 10889)),
    (10938, (29, 10909)),
    (10940, (3, 10937)),
    (10942, (3, 10939)),
    (10944, (5, 10939)),
    (10946, (7, 10939)),
    (10948, (11, 10937)),
    (10950, (11, 10939)),
    (10952, (3, 10949))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk001_d_verified
