/-
AUTOGENERATED (soundness mode): Chunk [742382..742618]
    Source: chunk_074.json  •  SHA256(JSON): 9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk074_k_verified

noncomputable section

def nLo : Nat := 742382
def nHi : Nat := 742618
def dataSHA256 : String := "9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (742382, (13, 742369)),
    (742384, (3, 742381)),
    (742386, (5, 742381)),
    (742388, (7, 742381)),
    (742390, (83, 742307)),
    (742392, (11, 742381)),
    (742394, (13, 742381)),
    (742396, (3, 742393)),
    (742398, (5, 742393)),
    (742400, (7, 742393)),
    (742402, (113, 742289)),
    (742404, (11, 742393)),
    (742406, (13, 742393)),
    (742408, (101, 742307)),
    (742410, (17, 742393)),
    (742412, (3, 742409)),
    (742414, (5, 742409)),
    (742416, (7, 742409)),
    (742418, (37, 742381)),
    (742420, (11, 742409)),
    (742422, (13, 742409)),
    (742424, (31, 742393)),
    (742426, (17, 742409)),
    (742428, (19, 742409)),
    (742430, (37, 742393)),
    (742432, (23, 742409)),
    (742434, (41, 742393)),
    (742436, (43, 742393)),
    (742438, (29, 742409)),
    (742440, (31, 742409)),
    (742442, (3, 742439)),
    (742444, (5, 742439)),
    (742446, (7, 742439)),
    (742448, (67, 742381)),
    (742450, (11, 742439)),
    (742452, (13, 742439)),
    (742454, (61, 742393)),
    (742456, (17, 742439)),
    (742458, (19, 742439)),
    (742460, (3, 742457)),
    (742462, (5, 742457)),
    (742464, (7, 742457)),
    (742466, (73, 742393)),
    (742468, (11, 742457)),
    (742470, (13, 742457)),
    (742472, (79, 742393)),
    (742474, (17, 742457)),
    (742476, (19, 742457)),
    (742478, (97, 742381)),
    (742480, (23, 742457)),
    (742482, (43, 742439)),
    (742484, (103, 742381)),
    (742486, (29, 742457)),
    (742488, (31, 742457)),
    (742490, (97, 742393)),
    (742492, (53, 742439)),
    (742494, (37, 742457)),
    (742496, (103, 742393)),
    (742498, (41, 742457)),
    (742500, (43, 742457)),
    (742502, (3, 742499)),
    (742504, (5, 742499)),
    (742506, (7, 742499)),
    (742508, (127, 742381)),
    (742510, (3, 742507)),
    (742512, (5, 742507)),
    (742514, (7, 742507)),
    (742516, (3, 742513)),
    (742518, (5, 742513)),
    (742520, (7, 742513)),
    (742522, (3, 742519)),
    (742524, (5, 742519)),
    (742526, (7, 742519)),
    (742528, (29, 742499)),
    (742530, (11, 742519)),
    (742532, (13, 742519)),
    (742534, (3, 742531)),
    (742536, (5, 742531)),
    (742538, (7, 742531)),
    (742540, (3, 742537)),
    (742542, (5, 742537)),
    (742544, (3, 742541)),
    (742546, (5, 742541)),
    (742548, (7, 742541)),
    (742550, (13, 742537)),
    (742552, (3, 742549)),
    (742554, (5, 742549)),
    (742556, (7, 742549)),
    (742558, (17, 742541)),
    (742560, (11, 742549)),
    (742562, (3, 742559)),
    (742564, (5, 742559)),
    (742566, (7, 742559)),
    (742568, (19, 742549)),
    (742570, (11, 742559)),
    (742572, (13, 742559)),
    (742574, (37, 742537)),
    (742576, (17, 742559)),
    (742578, (19, 742559)),
    (742580, (31, 742549)),
    (742582, (3, 742579)),
    (742584, (5, 742579)),
    (742586, (7, 742579)),
    (742588, (29, 742559)),
    (742590, (11, 742579)),
    (742592, (13, 742579)),
    (742594, (3, 742591)),
    (742596, (5, 742591)),
    (742598, (7, 742591)),
    (742600, (41, 742559)),
    (742602, (11, 742591)),
    (742604, (13, 742591)),
    (742606, (47, 742559)),
    (742608, (17, 742591)),
    (742610, (3, 742607)),
    (742612, (5, 742607)),
    (742614, (7, 742607)),
    (742616, (37, 742579)),
    (742618, (11, 742607))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk074_k_verified
