/-
AUTOGENERATED (soundness mode): Chunk [377142..377378]
    Source: chunk_037.json  •  SHA256(JSON): 44cf0d3c40461630bf7e1192c53eace010c440fc91029e14ce44cbc0344638d0
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk037_ae_verified

noncomputable section

def nLo : Nat := 377142
def nHi : Nat := 377378
def dataSHA256 : String := "44cf0d3c40461630bf7e1192c53eace010c440fc91029e14ce44cbc0344638d0"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (377142, (5, 377137)),
    (377144, (7, 377137)),
    (377146, (17, 377129)),
    (377148, (11, 377137)),
    (377150, (3, 377147)),
    (377152, (5, 377147)),
    (377154, (7, 377147)),
    (377156, (19, 377137)),
    (377158, (11, 377147)),
    (377160, (13, 377147)),
    (377162, (103, 377059)),
    (377164, (17, 377147)),
    (377166, (19, 377147)),
    (377168, (31, 377137)),
    (377170, (23, 377147)),
    (377172, (43, 377129)),
    (377174, (3, 377171)),
    (377176, (3, 377173)),
    (377178, (5, 377173)),
    (377180, (7, 377173)),
    (377182, (11, 377171)),
    (377184, (11, 377173)),
    (377186, (3, 377183)),
    (377188, (5, 377183)),
    (377190, (7, 377183)),
    (377192, (19, 377173)),
    (377194, (11, 377183)),
    (377196, (13, 377183)),
    (377198, (61, 377137)),
    (377200, (3, 377197)),
    (377202, (5, 377197)),
    (377204, (7, 377197)),
    (377206, (23, 377183)),
    (377208, (11, 377197)),
    (377210, (13, 377197)),
    (377212, (29, 377183)),
    (377214, (17, 377197)),
    (377216, (19, 377197)),
    (377218, (47, 377171)),
    (377220, (23, 377197)),
    (377222, (3, 377219)),
    (377224, (5, 377219)),
    (377226, (7, 377219)),
    (377228, (31, 377197)),
    (377230, (11, 377219)),
    (377232, (13, 377219)),
    (377234, (3, 377231)),
    (377236, (5, 377231)),
    (377238, (7, 377231)),
    (377240, (43, 377197)),
    (377242, (11, 377231)),
    (377244, (13, 377231)),
    (377246, (73, 377173)),
    (377248, (17, 377231)),
    (377250, (19, 377231)),
    (377252, (79, 377173)),
    (377254, (23, 377231)),
    (377256, (37, 377219)),
    (377258, (61, 377197)),
    (377260, (3, 377257)),
    (377262, (5, 377257)),
    (377264, (7, 377257)),
    (377266, (3, 377263)),
    (377268, (5, 377263)),
    (377270, (7, 377263)),
    (377272, (41, 377231)),
    (377274, (11, 377263)),
    (377276, (13, 377263)),
    (377278, (47, 377231)),
    (377280, (17, 377263)),
    (377282, (19, 377263)),
    (377284, (53, 377231)),
    (377286, (23, 377263)),
    (377288, (31, 377257)),
    (377290, (3, 377287)),
    (377292, (5, 377287)),
    (377294, (3, 377291)),
    (377296, (5, 377291)),
    (377298, (7, 377291)),
    (377300, (3, 377297)),
    (377302, (5, 377297)),
    (377304, (7, 377297)),
    (377306, (19, 377287)),
    (377308, (11, 377297)),
    (377310, (13, 377297)),
    (377312, (139, 377173)),
    (377314, (17, 377297)),
    (377316, (19, 377297)),
    (377318, (31, 377287)),
    (377320, (23, 377297)),
    (377322, (31, 377291)),
    (377324, (37, 377287)),
    (377326, (29, 377297)),
    (377328, (31, 377297)),
    (377330, (3, 377327)),
    (377332, (3, 377329)),
    (377334, (5, 377329)),
    (377336, (7, 377329)),
    (377338, (11, 377327)),
    (377340, (11, 377329)),
    (377342, (3, 377339)),
    (377344, (5, 377339)),
    (377346, (7, 377339)),
    (377348, (19, 377329)),
    (377350, (3, 377347)),
    (377352, (5, 377347)),
    (377354, (7, 377347)),
    (377356, (3, 377353)),
    (377358, (5, 377353)),
    (377360, (7, 377353)),
    (377362, (23, 377339)),
    (377364, (11, 377353)),
    (377366, (13, 377353)),
    (377368, (29, 377339)),
    (377370, (17, 377353)),
    (377372, (3, 377369)),
    (377374, (3, 377371)),
    (377376, (5, 377371)),
    (377378, (7, 377371))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk037_ae_verified
