/-
AUTOGENERATED (soundness mode): Chunk [45952..46188]
    Source: chunk_004.json  •  SHA256(JSON): e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk004_z_verified

noncomputable section

def nLo : Nat := 45952
def nHi : Nat := 46188
def dataSHA256 : String := "e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (45952, (3, 45949)),
    (45954, (5, 45949)),
    (45956, (3, 45953)),
    (45958, (5, 45953)),
    (45960, (7, 45953)),
    (45962, (3, 45959)),
    (45964, (5, 45959)),
    (45966, (7, 45959)),
    (45968, (19, 45949)),
    (45970, (11, 45959)),
    (45972, (13, 45959)),
    (45974, (3, 45971)),
    (45976, (5, 45971)),
    (45978, (7, 45971)),
    (45980, (31, 45949)),
    (45982, (3, 45979)),
    (45984, (5, 45979)),
    (45986, (7, 45979)),
    (45988, (17, 45971)),
    (45990, (11, 45979)),
    (45992, (3, 45989)),
    (45994, (5, 45989)),
    (45996, (7, 45989)),
    (45998, (19, 45979)),
    (46000, (11, 45989)),
    (46002, (13, 45989)),
    (46004, (61, 45943)),
    (46006, (17, 45989)),
    (46008, (19, 45989)),
    (46010, (31, 45979)),
    (46012, (23, 45989)),
    (46014, (43, 45971)),
    (46016, (37, 45979)),
    (46018, (29, 45989)),
    (46020, (31, 45989)),
    (46022, (43, 45979)),
    (46024, (3, 46021)),
    (46026, (5, 46021)),
    (46028, (7, 46021)),
    (46030, (3, 46027)),
    (46032, (5, 46027)),
    (46034, (7, 46027)),
    (46036, (47, 45989)),
    (46038, (11, 46027)),
    (46040, (13, 46027)),
    (46042, (53, 45989)),
    (46044, (17, 46027)),
    (46046, (19, 46027)),
    (46048, (59, 45989)),
    (46050, (23, 46027)),
    (46052, (3, 46049)),
    (46054, (3, 46051)),
    (46056, (5, 46051)),
    (46058, (7, 46051)),
    (46060, (11, 46049)),
    (46062, (11, 46051)),
    (46064, (3, 46061)),
    (46066, (5, 46061)),
    (46068, (7, 46061)),
    (46070, (19, 46051)),
    (46072, (11, 46061)),
    (46074, (13, 46061)),
    (46076, (3, 46073)),
    (46078, (5, 46073)),
    (46080, (7, 46073)),
    (46082, (31, 46051)),
    (46084, (11, 46073)),
    (46086, (13, 46073)),
    (46088, (37, 46051)),
    (46090, (17, 46073)),
    (46092, (19, 46073)),
    (46094, (3, 46091)),
    (46096, (3, 46093)),
    (46098, (5, 46093)),
    (46100, (7, 46093)),
    (46102, (3, 46099)),
    (46104, (5, 46099)),
    (46106, (3, 46103)),
    (46108, (5, 46103)),
    (46110, (7, 46103)),
    (46112, (13, 46099)),
    (46114, (11, 46103)),
    (46116, (13, 46103)),
    (46118, (19, 46099)),
    (46120, (17, 46103)),
    (46122, (19, 46103)),
    (46124, (31, 46093)),
    (46126, (23, 46103)),
    (46128, (29, 46099)),
    (46130, (31, 46099)),
    (46132, (29, 46103)),
    (46134, (31, 46103)),
    (46136, (3, 46133)),
    (46138, (5, 46133)),
    (46140, (7, 46133)),
    (46142, (43, 46099)),
    (46144, (3, 46141)),
    (46146, (5, 46141)),
    (46148, (7, 46141)),
    (46150, (3, 46147)),
    (46152, (5, 46147)),
    (46154, (7, 46147)),
    (46156, (3, 46153)),
    (46158, (5, 46153)),
    (46160, (7, 46153)),
    (46162, (29, 46133)),
    (46164, (11, 46153)),
    (46166, (13, 46153)),
    (46168, (107, 46061)),
    (46170, (17, 46153)),
    (46172, (19, 46153)),
    (46174, (3, 46171)),
    (46176, (5, 46171)),
    (46178, (7, 46171)),
    (46180, (47, 46133)),
    (46182, (11, 46171)),
    (46184, (3, 46181)),
    (46186, (3, 46183)),
    (46188, (5, 46183))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk004_z_verified
