/-
AUTOGENERATED (soundness mode): Chunk [640240..640476]
    Source: chunk_064.json  •  SHA256(JSON): 6255ff4756acd7c8780f5b3f9bdcd0881c52817ed76436e41e9c5c576da55c15
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk064_b_verified

noncomputable section

def nLo : Nat := 640240
def nHi : Nat := 640476
def dataSHA256 : String := "6255ff4756acd7c8780f5b3f9bdcd0881c52817ed76436e41e9c5c576da55c15"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (640240, (11, 640229)),
    (640242, (11, 640231)),
    (640244, (13, 640231)),
    (640246, (17, 640229)),
    (640248, (17, 640231)),
    (640250, (3, 640247)),
    (640252, (3, 640249)),
    (640254, (5, 640249)),
    (640256, (7, 640249)),
    (640258, (11, 640247)),
    (640260, (11, 640249)),
    (640262, (3, 640259)),
    (640264, (3, 640261)),
    (640266, (5, 640261)),
    (640268, (7, 640261)),
    (640270, (3, 640267)),
    (640272, (5, 640267)),
    (640274, (7, 640267)),
    (640276, (17, 640259)),
    (640278, (11, 640267)),
    (640280, (13, 640267)),
    (640282, (3, 640279)),
    (640284, (5, 640279)),
    (640286, (7, 640279)),
    (640288, (29, 640259)),
    (640290, (11, 640279)),
    (640292, (13, 640279)),
    (640294, (47, 640247)),
    (640296, (17, 640279)),
    (640298, (19, 640279)),
    (640300, (41, 640259)),
    (640302, (23, 640279)),
    (640304, (37, 640267)),
    (640306, (3, 640303)),
    (640308, (5, 640303)),
    (640310, (3, 640307)),
    (640312, (5, 640307)),
    (640314, (7, 640307)),
    (640316, (13, 640303)),
    (640318, (11, 640307)),
    (640320, (13, 640307)),
    (640322, (19, 640303)),
    (640324, (17, 640307)),
    (640326, (19, 640307)),
    (640328, (61, 640267)),
    (640330, (23, 640307)),
    (640332, (29, 640303)),
    (640334, (31, 640303)),
    (640336, (3, 640333)),
    (640338, (5, 640333)),
    (640340, (7, 640333)),
    (640342, (83, 640259)),
    (640344, (11, 640333)),
    (640346, (13, 640333)),
    (640348, (41, 640307)),
    (640350, (17, 640333)),
    (640352, (19, 640333)),
    (640354, (47, 640307)),
    (640356, (23, 640333)),
    (640358, (79, 640279)),
    (640360, (53, 640307)),
    (640362, (29, 640333)),
    (640364, (31, 640333)),
    (640366, (3, 640363)),
    (640368, (5, 640363)),
    (640370, (7, 640363)),
    (640372, (3, 640369)),
    (640374, (5, 640369)),
    (640376, (7, 640369)),
    (640378, (71, 640307)),
    (640380, (11, 640369)),
    (640382, (13, 640369)),
    (640384, (137, 640247)),
    (640386, (17, 640369)),
    (640388, (19, 640369)),
    (640390, (83, 640307)),
    (640392, (23, 640369)),
    (640394, (31, 640363)),
    (640396, (89, 640307)),
    (640398, (29, 640369)),
    (640400, (31, 640369)),
    (640402, (173, 640229)),
    (640404, (41, 640363)),
    (640406, (37, 640369)),
    (640408, (101, 640307)),
    (640410, (41, 640369)),
    (640412, (43, 640369)),
    (640414, (3, 640411)),
    (640416, (5, 640411)),
    (640418, (7, 640411)),
    (640420, (113, 640307)),
    (640422, (11, 640411)),
    (640424, (3, 640421)),
    (640426, (5, 640421)),
    (640428, (7, 640421)),
    (640430, (19, 640411)),
    (640432, (11, 640421)),
    (640434, (13, 640421)),
    (640436, (67, 640369)),
    (640438, (17, 640421)),
    (640440, (19, 640421)),
    (640442, (31, 640411)),
    (640444, (23, 640421)),
    (640446, (83, 640363)),
    (640448, (37, 640411)),
    (640450, (29, 640421)),
    (640452, (31, 640421)),
    (640454, (43, 640411)),
    (640456, (149, 640307)),
    (640458, (37, 640421)),
    (640460, (3, 640457)),
    (640462, (5, 640457)),
    (640464, (7, 640457)),
    (640466, (3, 640463)),
    (640468, (5, 640463)),
    (640470, (7, 640463)),
    (640472, (61, 640411)),
    (640474, (11, 640463)),
    (640476, (13, 640463))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk064_b_verified
