/-
AUTOGENERATED (soundness mode): Chunk [460954..461190]
    Source: chunk_046.json  •  SHA256(JSON): 0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk046_e_verified

noncomputable section

def nLo : Nat := 460954
def nHi : Nat := 461190
def dataSHA256 : String := "0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (460954, (3, 460951)),
    (460956, (5, 460951)),
    (460958, (7, 460951)),
    (460960, (11, 460949)),
    (460962, (11, 460951)),
    (460964, (13, 460951)),
    (460966, (17, 460949)),
    (460968, (17, 460951)),
    (460970, (19, 460951)),
    (460972, (3, 460969)),
    (460974, (5, 460969)),
    (460976, (3, 460973)),
    (460978, (5, 460973)),
    (460980, (7, 460973)),
    (460982, (3, 460979)),
    (460984, (3, 460981)),
    (460986, (5, 460981)),
    (460988, (7, 460981)),
    (460990, (3, 460987)),
    (460992, (5, 460987)),
    (460994, (3, 460991)),
    (460996, (5, 460991)),
    (460998, (7, 460991)),
    (461000, (13, 460987)),
    (461002, (11, 460991)),
    (461004, (13, 460991)),
    (461006, (19, 460987)),
    (461008, (17, 460991)),
    (461010, (19, 460991)),
    (461012, (3, 461009)),
    (461014, (3, 461011)),
    (461016, (5, 461011)),
    (461018, (7, 461011)),
    (461020, (3, 461017)),
    (461022, (5, 461017)),
    (461024, (7, 461017)),
    (461026, (17, 461009)),
    (461028, (11, 461017)),
    (461030, (13, 461017)),
    (461032, (23, 461009)),
    (461034, (17, 461017)),
    (461036, (19, 461017)),
    (461038, (29, 461009)),
    (461040, (23, 461017)),
    (461042, (31, 461011)),
    (461044, (53, 460991)),
    (461046, (29, 461017)),
    (461048, (31, 461017)),
    (461050, (41, 461009)),
    (461052, (41, 461011)),
    (461054, (3, 461051)),
    (461056, (3, 461053)),
    (461058, (5, 461053)),
    (461060, (7, 461053)),
    (461062, (3, 461059)),
    (461064, (5, 461059)),
    (461066, (7, 461059)),
    (461068, (17, 461051)),
    (461070, (11, 461059)),
    (461072, (13, 461059)),
    (461074, (23, 461051)),
    (461076, (17, 461059)),
    (461078, (19, 461059)),
    (461080, (29, 461051)),
    (461082, (23, 461059)),
    (461084, (31, 461053)),
    (461086, (107, 460979)),
    (461088, (29, 461059)),
    (461090, (31, 461059)),
    (461092, (41, 461051)),
    (461094, (41, 461053)),
    (461096, (3, 461093)),
    (461098, (5, 461093)),
    (461100, (7, 461093)),
    (461102, (43, 461059)),
    (461104, (3, 461101)),
    (461106, (5, 461101)),
    (461108, (7, 461101)),
    (461110, (17, 461093)),
    (461112, (11, 461101)),
    (461114, (13, 461101)),
    (461116, (23, 461093)),
    (461118, (17, 461101)),
    (461120, (19, 461101)),
    (461122, (3, 461119)),
    (461124, (5, 461119)),
    (461126, (7, 461119)),
    (461128, (137, 460991)),
    (461130, (11, 461119)),
    (461132, (13, 461119)),
    (461134, (41, 461093)),
    (461136, (17, 461119)),
    (461138, (19, 461119)),
    (461140, (47, 461093)),
    (461142, (23, 461119)),
    (461144, (43, 461101)),
    (461146, (3, 461143)),
    (461148, (5, 461143)),
    (461150, (3, 461147)),
    (461152, (5, 461147)),
    (461154, (7, 461147)),
    (461156, (13, 461143)),
    (461158, (11, 461147)),
    (461160, (13, 461147)),
    (461162, (19, 461143)),
    (461164, (17, 461147)),
    (461166, (19, 461147)),
    (461168, (67, 461101)),
    (461170, (23, 461147)),
    (461172, (29, 461143)),
    (461174, (3, 461171)),
    (461176, (5, 461171)),
    (461178, (7, 461171)),
    (461180, (37, 461143)),
    (461182, (11, 461171)),
    (461184, (13, 461171)),
    (461186, (3, 461183)),
    (461188, (5, 461183)),
    (461190, (7, 461183))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk046_e_verified
