/-
AUTOGENERATED (soundness mode): Chunk [841668..841904]
    Source: chunk_084.json  •  SHA256(JSON): 93e7e3ec9043fe247a3edd8d0c0e8b20b30e7e6b0a6b54bdbcfdfe0d8dc736ff
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk084_h_verified

noncomputable section

def nLo : Nat := 841668
def nHi : Nat := 841904
def dataSHA256 : String := "93e7e3ec9043fe247a3edd8d0c0e8b20b30e7e6b0a6b54bdbcfdfe0d8dc736ff"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (841668, (5, 841663)),
    (841670, (7, 841663)),
    (841672, (11, 841661)),
    (841674, (11, 841663)),
    (841676, (13, 841663)),
    (841678, (17, 841661)),
    (841680, (17, 841663)),
    (841682, (19, 841663)),
    (841684, (23, 841661)),
    (841686, (23, 841663)),
    (841688, (37, 841651)),
    (841690, (29, 841661)),
    (841692, (29, 841663)),
    (841694, (3, 841691)),
    (841696, (5, 841691)),
    (841698, (7, 841691)),
    (841700, (3, 841697)),
    (841702, (5, 841697)),
    (841704, (7, 841697)),
    (841706, (43, 841663)),
    (841708, (11, 841697)),
    (841710, (13, 841697)),
    (841712, (61, 841651)),
    (841714, (17, 841697)),
    (841716, (19, 841697)),
    (841718, (67, 841651)),
    (841720, (23, 841697)),
    (841722, (31, 841691)),
    (841724, (61, 841663)),
    (841726, (29, 841697)),
    (841728, (31, 841697)),
    (841730, (3, 841727)),
    (841732, (5, 841727)),
    (841734, (7, 841727)),
    (841736, (73, 841663)),
    (841738, (11, 841727)),
    (841740, (13, 841727)),
    (841742, (79, 841663)),
    (841744, (3, 841741)),
    (841746, (5, 841741)),
    (841748, (7, 841741)),
    (841750, (23, 841727)),
    (841752, (11, 841741)),
    (841754, (3, 841751)),
    (841756, (5, 841751)),
    (841758, (7, 841751)),
    (841760, (19, 841741)),
    (841762, (11, 841751)),
    (841764, (13, 841751)),
    (841766, (103, 841663)),
    (841768, (17, 841751)),
    (841770, (19, 841751)),
    (841772, (31, 841741)),
    (841774, (23, 841751)),
    (841776, (79, 841697)),
    (841778, (37, 841741)),
    (841780, (29, 841751)),
    (841782, (31, 841751)),
    (841784, (43, 841741)),
    (841786, (59, 841727)),
    (841788, (37, 841751)),
    (841790, (127, 841663)),
    (841792, (41, 841751)),
    (841794, (43, 841751)),
    (841796, (3, 841793)),
    (841798, (5, 841793)),
    (841800, (7, 841793)),
    (841802, (61, 841741)),
    (841804, (3, 841801)),
    (841806, (5, 841801)),
    (841808, (7, 841801)),
    (841810, (17, 841793)),
    (841812, (11, 841801)),
    (841814, (13, 841801)),
    (841816, (23, 841793)),
    (841818, (17, 841801)),
    (841820, (19, 841801)),
    (841822, (29, 841793)),
    (841824, (23, 841801)),
    (841826, (163, 841663)),
    (841828, (101, 841727)),
    (841830, (29, 841801)),
    (841832, (31, 841801)),
    (841834, (41, 841793)),
    (841836, (43, 841793)),
    (841838, (37, 841801)),
    (841840, (47, 841793)),
    (841842, (41, 841801)),
    (841844, (43, 841801)),
    (841846, (53, 841793)),
    (841848, (47, 841801)),
    (841850, (109, 841741)),
    (841852, (3, 841849)),
    (841854, (5, 841849)),
    (841856, (7, 841849)),
    (841858, (107, 841751)),
    (841860, (11, 841849)),
    (841862, (3, 841859)),
    (841864, (5, 841859)),
    (841866, (7, 841859)),
    (841868, (19, 841849)),
    (841870, (11, 841859)),
    (841872, (13, 841859)),
    (841874, (73, 841801)),
    (841876, (3, 841873)),
    (841878, (5, 841873)),
    (841880, (7, 841873)),
    (841882, (3, 841879)),
    (841884, (5, 841879)),
    (841886, (7, 841879)),
    (841888, (29, 841859)),
    (841890, (11, 841879)),
    (841892, (3, 841889)),
    (841894, (5, 841889)),
    (841896, (7, 841889)),
    (841898, (19, 841879)),
    (841900, (11, 841889)),
    (841902, (13, 841889)),
    (841904, (31, 841873))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk084_h_verified
