/-
AUTOGENERATED (soundness mode): Chunk [591430..591666]
    Source: chunk_059.json  •  SHA256(JSON): 159fc8bad1a16ac0c1ea98c5ef2ee3071b1e865e2a286482c5c354acf434bb42
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk059_g_verified

noncomputable section

def nLo : Nat := 591430
def nHi : Nat := 591666
def dataSHA256 : String := "159fc8bad1a16ac0c1ea98c5ef2ee3071b1e865e2a286482c5c354acf434bb42"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (591430, (23, 591407)),
    (591432, (11, 591421)),
    (591434, (3, 591431)),
    (591436, (5, 591431)),
    (591438, (7, 591431)),
    (591440, (19, 591421)),
    (591442, (11, 591431)),
    (591444, (13, 591431)),
    (591446, (3, 591443)),
    (591448, (5, 591443)),
    (591450, (7, 591443)),
    (591452, (31, 591421)),
    (591454, (11, 591443)),
    (591456, (13, 591443)),
    (591458, (37, 591421)),
    (591460, (3, 591457)),
    (591462, (5, 591457)),
    (591464, (7, 591457)),
    (591466, (23, 591443)),
    (591468, (11, 591457)),
    (591470, (13, 591457)),
    (591472, (3, 591469)),
    (591474, (5, 591469)),
    (591476, (7, 591469)),
    (591478, (47, 591431)),
    (591480, (11, 591469)),
    (591482, (13, 591469)),
    (591484, (41, 591443)),
    (591486, (17, 591469)),
    (591488, (19, 591469)),
    (591490, (47, 591443)),
    (591492, (23, 591469)),
    (591494, (37, 591457)),
    (591496, (53, 591443)),
    (591498, (29, 591469)),
    (591500, (31, 591469)),
    (591502, (3, 591499)),
    (591504, (5, 591499)),
    (591506, (7, 591499)),
    (591508, (101, 591407)),
    (591510, (11, 591499)),
    (591512, (3, 591509)),
    (591514, (5, 591509)),
    (591516, (7, 591509)),
    (591518, (19, 591499)),
    (591520, (11, 591509)),
    (591522, (13, 591509)),
    (591524, (67, 591457)),
    (591526, (3, 591523)),
    (591528, (5, 591523)),
    (591530, (7, 591523)),
    (591532, (23, 591509)),
    (591534, (11, 591523)),
    (591536, (13, 591523)),
    (591538, (29, 591509)),
    (591540, (17, 591523)),
    (591542, (19, 591523)),
    (591544, (101, 591443)),
    (591546, (23, 591523)),
    (591548, (79, 591469)),
    (591550, (41, 591509)),
    (591552, (29, 591523)),
    (591554, (31, 591523)),
    (591556, (3, 591553)),
    (591558, (5, 591553)),
    (591560, (7, 591553)),
    (591562, (3, 591559)),
    (591564, (5, 591559)),
    (591566, (7, 591559)),
    (591568, (59, 591509)),
    (591570, (11, 591559)),
    (591572, (13, 591559)),
    (591574, (131, 591443)),
    (591576, (17, 591559)),
    (591578, (19, 591559)),
    (591580, (71, 591509)),
    (591582, (23, 591559)),
    (591584, (3, 591581)),
    (591586, (5, 591581)),
    (591588, (7, 591581)),
    (591590, (31, 591559)),
    (591592, (11, 591581)),
    (591594, (13, 591581)),
    (591596, (37, 591559)),
    (591598, (17, 591581)),
    (591600, (19, 591581)),
    (591602, (3, 591599)),
    (591604, (3, 591601)),
    (591606, (5, 591601)),
    (591608, (7, 591601)),
    (591610, (11, 591599)),
    (591612, (11, 591601)),
    (591614, (3, 591611)),
    (591616, (5, 591611)),
    (591618, (7, 591611)),
    (591620, (19, 591601)),
    (591622, (11, 591611)),
    (591624, (13, 591611)),
    (591626, (3, 591623)),
    (591628, (5, 591623)),
    (591630, (7, 591623)),
    (591632, (31, 591601)),
    (591634, (11, 591623)),
    (591636, (13, 591623)),
    (591638, (37, 591601)),
    (591640, (17, 591623)),
    (591642, (19, 591623)),
    (591644, (43, 591601)),
    (591646, (23, 591623)),
    (591648, (37, 591611)),
    (591650, (97, 591553)),
    (591652, (3, 591649)),
    (591654, (5, 591649)),
    (591656, (3, 591653)),
    (591658, (5, 591653)),
    (591660, (7, 591653)),
    (591662, (3, 591659)),
    (591664, (5, 591659)),
    (591666, (7, 591659))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk059_g_verified
