/-
AUTOGENERATED (soundness mode): Chunk [317856..318092]
    Source: chunk_031.json  •  SHA256(JSON): 2619e76715d1c3d4d56fec7ed4ae1dc88e4b069bfe501e0797b70b47dbc1cfe8
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk031_ah_verified

noncomputable section

def nLo : Nat := 317856
def nHi : Nat := 318092
def dataSHA256 : String := "2619e76715d1c3d4d56fec7ed4ae1dc88e4b069bfe501e0797b70b47dbc1cfe8"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (317856, (17, 317839)),
    (317858, (19, 317839)),
    (317860, (3, 317857)),
    (317862, (5, 317857)),
    (317864, (7, 317857)),
    (317866, (83, 317783)),
    (317868, (11, 317857)),
    (317870, (13, 317857)),
    (317872, (41, 317831)),
    (317874, (17, 317857)),
    (317876, (19, 317857)),
    (317878, (47, 317831)),
    (317880, (23, 317857)),
    (317882, (43, 317839)),
    (317884, (53, 317831)),
    (317886, (29, 317857)),
    (317888, (31, 317857)),
    (317890, (3, 317887)),
    (317892, (5, 317887)),
    (317894, (7, 317887)),
    (317896, (107, 317789)),
    (317898, (11, 317887)),
    (317900, (13, 317887)),
    (317902, (71, 317831)),
    (317904, (17, 317887)),
    (317906, (3, 317903)),
    (317908, (5, 317903)),
    (317910, (7, 317903)),
    (317912, (73, 317839)),
    (317914, (11, 317903)),
    (317916, (13, 317903)),
    (317918, (31, 317887)),
    (317920, (17, 317903)),
    (317922, (19, 317903)),
    (317924, (3, 317921)),
    (317926, (3, 317923)),
    (317928, (5, 317923)),
    (317930, (7, 317923)),
    (317932, (11, 317921)),
    (317934, (11, 317923)),
    (317936, (13, 317923)),
    (317938, (17, 317921)),
    (317940, (17, 317923)),
    (317942, (19, 317923)),
    (317944, (23, 317921)),
    (317946, (23, 317923)),
    (317948, (61, 317887)),
    (317950, (29, 317921)),
    (317952, (29, 317923)),
    (317954, (31, 317923)),
    (317956, (53, 317903)),
    (317958, (37, 317921)),
    (317960, (3, 317957)),
    (317962, (3, 317959)),
    (317964, (5, 317959)),
    (317966, (3, 317963)),
    (317968, (5, 317963)),
    (317970, (7, 317963)),
    (317972, (3, 317969)),
    (317974, (3, 317971)),
    (317976, (5, 317971)),
    (317978, (7, 317971)),
    (317980, (11, 317969)),
    (317982, (11, 317971)),
    (317984, (13, 317971)),
    (317986, (3, 317983)),
    (317988, (5, 317983)),
    (317990, (3, 317987)),
    (317992, (5, 317987)),
    (317994, (7, 317987)),
    (317996, (13, 317983)),
    (317998, (11, 317987)),
    (318000, (13, 317987)),
    (318002, (19, 317983)),
    (318004, (3, 318001)),
    (318006, (5, 318001)),
    (318008, (7, 318001)),
    (318010, (3, 318007)),
    (318012, (5, 318007)),
    (318014, (7, 318007)),
    (318016, (29, 317987)),
    (318018, (11, 318007)),
    (318020, (13, 318007)),
    (318022, (53, 317969)),
    (318024, (17, 318007)),
    (318026, (3, 318023)),
    (318028, (5, 318023)),
    (318030, (7, 318023)),
    (318032, (31, 318001)),
    (318034, (11, 318023)),
    (318036, (13, 318023)),
    (318038, (31, 318007)),
    (318040, (17, 318023)),
    (318042, (19, 318023)),
    (318044, (37, 318007)),
    (318046, (23, 318023)),
    (318048, (41, 318007)),
    (318050, (43, 318007)),
    (318052, (29, 318023)),
    (318054, (31, 318023)),
    (318056, (73, 317983)),
    (318058, (71, 317987)),
    (318060, (37, 318023)),
    (318062, (61, 318001)),
    (318064, (41, 318023)),
    (318066, (43, 318023)),
    (318068, (61, 318007)),
    (318070, (47, 318023)),
    (318072, (71, 318001)),
    (318074, (67, 318007)),
    (318076, (53, 318023)),
    (318078, (71, 318007)),
    (318080, (3, 318077)),
    (318082, (5, 318077)),
    (318084, (7, 318077)),
    (318086, (79, 318007)),
    (318088, (11, 318077)),
    (318090, (13, 318077)),
    (318092, (109, 317983))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk031_ah_verified
