/-
AUTOGENERATED (soundness mode): Chunk [11192..11428]
    Source: chunk_001.json  •  SHA256(JSON): 8d258a0b6848d2a48410ecf140829c3397d41e92ad9654236410c899854f0c14
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk001_f_verified

noncomputable section

def nLo : Nat := 11192
def nHi : Nat := 11428
def dataSHA256 : String := "8d258a0b6848d2a48410ecf140829c3397d41e92ad9654236410c899854f0c14"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (11192, (19, 11173)),
    (11194, (17, 11177)),
    (11196, (19, 11177)),
    (11198, (37, 11161)),
    (11200, (3, 11197)),
    (11202, (5, 11197)),
    (11204, (7, 11197)),
    (11206, (29, 11177)),
    (11208, (11, 11197)),
    (11210, (13, 11197)),
    (11212, (41, 11171)),
    (11214, (17, 11197)),
    (11216, (3, 11213)),
    (11218, (5, 11213)),
    (11220, (7, 11213)),
    (11222, (61, 11161)),
    (11224, (11, 11213)),
    (11226, (13, 11213)),
    (11228, (31, 11197)),
    (11230, (17, 11213)),
    (11232, (19, 11213)),
    (11234, (37, 11197)),
    (11236, (23, 11213)),
    (11238, (41, 11197)),
    (11240, (43, 11197)),
    (11242, (3, 11239)),
    (11244, (5, 11239)),
    (11246, (3, 11243)),
    (11248, (5, 11243)),
    (11250, (7, 11243)),
    (11252, (13, 11239)),
    (11254, (3, 11251)),
    (11256, (5, 11251)),
    (11258, (7, 11251)),
    (11260, (3, 11257)),
    (11262, (5, 11257)),
    (11264, (3, 11261)),
    (11266, (5, 11261)),
    (11268, (7, 11261)),
    (11270, (13, 11257)),
    (11272, (11, 11261)),
    (11274, (13, 11261)),
    (11276, (3, 11273)),
    (11278, (5, 11273)),
    (11280, (7, 11273)),
    (11282, (3, 11279)),
    (11284, (5, 11279)),
    (11286, (7, 11279)),
    (11288, (31, 11257)),
    (11290, (3, 11287)),
    (11292, (5, 11287)),
    (11294, (7, 11287)),
    (11296, (17, 11279)),
    (11298, (11, 11287)),
    (11300, (13, 11287)),
    (11302, (3, 11299)),
    (11304, (5, 11299)),
    (11306, (7, 11299)),
    (11308, (29, 11279)),
    (11310, (11, 11299)),
    (11312, (13, 11299)),
    (11314, (3, 11311)),
    (11316, (5, 11311)),
    (11318, (7, 11311)),
    (11320, (3, 11317)),
    (11322, (5, 11317)),
    (11324, (3, 11321)),
    (11326, (5, 11321)),
    (11328, (7, 11321)),
    (11330, (13, 11317)),
    (11332, (3, 11329)),
    (11334, (5, 11329)),
    (11336, (7, 11329)),
    (11338, (17, 11321)),
    (11340, (11, 11329)),
    (11342, (13, 11329)),
    (11344, (23, 11321)),
    (11346, (17, 11329)),
    (11348, (19, 11329)),
    (11350, (29, 11321)),
    (11352, (23, 11329)),
    (11354, (3, 11351)),
    (11356, (3, 11353)),
    (11358, (5, 11353)),
    (11360, (7, 11353)),
    (11362, (11, 11351)),
    (11364, (11, 11353)),
    (11366, (13, 11353)),
    (11368, (17, 11351)),
    (11370, (17, 11353)),
    (11372, (3, 11369)),
    (11374, (5, 11369)),
    (11376, (7, 11369)),
    (11378, (61, 11317)),
    (11380, (11, 11369)),
    (11382, (13, 11369)),
    (11384, (31, 11353)),
    (11386, (3, 11383)),
    (11388, (5, 11383)),
    (11390, (7, 11383)),
    (11392, (23, 11369)),
    (11394, (11, 11383)),
    (11396, (3, 11393)),
    (11398, (5, 11393)),
    (11400, (7, 11393)),
    (11402, (3, 11399)),
    (11404, (5, 11399)),
    (11406, (7, 11399)),
    (11408, (79, 11329)),
    (11410, (11, 11399)),
    (11412, (13, 11399)),
    (11414, (3, 11411)),
    (11416, (5, 11411)),
    (11418, (7, 11411)),
    (11420, (37, 11383)),
    (11422, (11, 11411)),
    (11424, (13, 11411)),
    (11426, (3, 11423)),
    (11428, (5, 11423))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk001_f_verified
