/-
AUTOGENERATED (soundness mode): Chunk [339284..339520]
    Source: chunk_033.json  •  SHA256(JSON): c928ea0fe693ba876701a71f304c546ab87fdb7441284ddcd3103d4d1c58b4ec
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk033_an_verified

noncomputable section

def nLo : Nat := 339284
def nHi : Nat := 339520
def dataSHA256 : String := "c928ea0fe693ba876701a71f304c546ab87fdb7441284ddcd3103d4d1c58b4ec"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (339284, (37, 339247)),
    (339286, (23, 339263)),
    (339288, (31, 339257)),
    (339290, (43, 339247)),
    (339292, (3, 339289)),
    (339294, (5, 339289)),
    (339296, (7, 339289)),
    (339298, (41, 339257)),
    (339300, (11, 339289)),
    (339302, (13, 339289)),
    (339304, (41, 339263)),
    (339306, (17, 339289)),
    (339308, (19, 339289)),
    (339310, (3, 339307)),
    (339312, (5, 339307)),
    (339314, (7, 339307)),
    (339316, (53, 339263)),
    (339318, (11, 339307)),
    (339320, (13, 339307)),
    (339322, (59, 339263)),
    (339324, (17, 339307)),
    (339326, (3, 339323)),
    (339328, (5, 339323)),
    (339330, (7, 339323)),
    (339332, (43, 339289)),
    (339334, (3, 339331)),
    (339336, (5, 339331)),
    (339338, (7, 339331)),
    (339340, (17, 339323)),
    (339342, (11, 339331)),
    (339344, (3, 339341)),
    (339346, (5, 339341)),
    (339348, (7, 339341)),
    (339350, (19, 339331)),
    (339352, (11, 339341)),
    (339354, (13, 339341)),
    (339356, (67, 339289)),
    (339358, (17, 339341)),
    (339360, (19, 339341)),
    (339362, (31, 339331)),
    (339364, (23, 339341)),
    (339366, (43, 339323)),
    (339368, (37, 339331)),
    (339370, (29, 339341)),
    (339372, (31, 339341)),
    (339374, (43, 339331)),
    (339376, (3, 339373)),
    (339378, (5, 339373)),
    (339380, (7, 339373)),
    (339382, (41, 339341)),
    (339384, (11, 339373)),
    (339386, (13, 339373)),
    (339388, (47, 339341)),
    (339390, (17, 339373)),
    (339392, (3, 339389)),
    (339394, (5, 339389)),
    (339396, (7, 339389)),
    (339398, (67, 339331)),
    (339400, (11, 339389)),
    (339402, (13, 339389)),
    (339404, (31, 339373)),
    (339406, (17, 339389)),
    (339408, (19, 339389)),
    (339410, (37, 339373)),
    (339412, (23, 339389)),
    (339414, (41, 339373)),
    (339416, (3, 339413)),
    (339418, (5, 339413)),
    (339420, (7, 339413)),
    (339422, (199, 339223)),
    (339424, (11, 339413)),
    (339426, (13, 339413)),
    (339428, (97, 339331)),
    (339430, (17, 339413)),
    (339432, (19, 339413)),
    (339434, (61, 339373)),
    (339436, (3, 339433)),
    (339438, (5, 339433)),
    (339440, (7, 339433)),
    (339442, (29, 339413)),
    (339444, (11, 339433)),
    (339446, (13, 339433)),
    (339448, (59, 339389)),
    (339450, (17, 339433)),
    (339452, (19, 339433)),
    (339454, (41, 339413)),
    (339456, (23, 339433)),
    (339458, (127, 339331)),
    (339460, (47, 339413)),
    (339462, (29, 339433)),
    (339464, (31, 339433)),
    (339466, (53, 339413)),
    (339468, (79, 339389)),
    (339470, (3, 339467)),
    (339472, (5, 339467)),
    (339474, (7, 339467)),
    (339476, (43, 339433)),
    (339478, (11, 339467)),
    (339480, (13, 339467)),
    (339482, (109, 339373)),
    (339484, (17, 339467)),
    (339486, (19, 339467)),
    (339488, (157, 339331)),
    (339490, (23, 339467)),
    (339492, (59, 339433)),
    (339494, (3, 339491)),
    (339496, (5, 339491)),
    (339498, (7, 339491)),
    (339500, (67, 339433)),
    (339502, (11, 339491)),
    (339504, (13, 339491)),
    (339506, (73, 339433)),
    (339508, (17, 339491)),
    (339510, (19, 339491)),
    (339512, (79, 339433)),
    (339514, (23, 339491)),
    (339516, (83, 339433)),
    (339518, (211, 339307)),
    (339520, (3, 339517))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk033_an_verified
