/-
AUTOGENERATED (soundness mode): Chunk [299522..299758]
    Source: chunk_029.json  •  SHA256(JSON): de7dd53f13071a968ee73359bff62faf3edbe00b0afdcf7b83c0d5d837117ed9
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk029_ao_verified

noncomputable section

def nLo : Nat := 299522
def nHi : Nat := 299758
def dataSHA256 : String := "de7dd53f13071a968ee73359bff62faf3edbe00b0afdcf7b83c0d5d837117ed9"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (299522, (43, 299479)),
    (299524, (3, 299521)),
    (299526, (5, 299521)),
    (299528, (7, 299521)),
    (299530, (3, 299527)),
    (299532, (5, 299527)),
    (299534, (7, 299527)),
    (299536, (23, 299513)),
    (299538, (11, 299527)),
    (299540, (13, 299527)),
    (299542, (3, 299539)),
    (299544, (5, 299539)),
    (299546, (7, 299539)),
    (299548, (47, 299501)),
    (299550, (11, 299539)),
    (299552, (13, 299539)),
    (299554, (41, 299513)),
    (299556, (17, 299539)),
    (299558, (19, 299539)),
    (299560, (47, 299513)),
    (299562, (23, 299539)),
    (299564, (37, 299527)),
    (299566, (53, 299513)),
    (299568, (29, 299539)),
    (299570, (3, 299567)),
    (299572, (3, 299569)),
    (299574, (5, 299569)),
    (299576, (7, 299569)),
    (299578, (11, 299567)),
    (299580, (11, 299569)),
    (299582, (13, 299569)),
    (299584, (17, 299567)),
    (299586, (17, 299569)),
    (299588, (19, 299569)),
    (299590, (23, 299567)),
    (299592, (23, 299569)),
    (299594, (67, 299527)),
    (299596, (29, 299567)),
    (299598, (29, 299569)),
    (299600, (31, 299569)),
    (299602, (89, 299513)),
    (299604, (37, 299567)),
    (299606, (3, 299603)),
    (299608, (5, 299603)),
    (299610, (7, 299603)),
    (299612, (43, 299569)),
    (299614, (11, 299603)),
    (299616, (13, 299603)),
    (299618, (79, 299539)),
    (299620, (3, 299617)),
    (299622, (5, 299617)),
    (299624, (7, 299617)),
    (299626, (3, 299623)),
    (299628, (5, 299623)),
    (299630, (7, 299623)),
    (299632, (29, 299603)),
    (299634, (11, 299623)),
    (299636, (13, 299623)),
    (299638, (71, 299567)),
    (299640, (17, 299623)),
    (299642, (19, 299623)),
    (299644, (41, 299603)),
    (299646, (23, 299623)),
    (299648, (31, 299617)),
    (299650, (47, 299603)),
    (299652, (29, 299623)),
    (299654, (31, 299623)),
    (299656, (3, 299653)),
    (299658, (5, 299653)),
    (299660, (7, 299653)),
    (299662, (59, 299603)),
    (299664, (11, 299653)),
    (299666, (13, 299653)),
    (299668, (101, 299567)),
    (299670, (17, 299653)),
    (299672, (19, 299653)),
    (299674, (3, 299671)),
    (299676, (5, 299671)),
    (299678, (7, 299671)),
    (299680, (113, 299567)),
    (299682, (11, 299671)),
    (299684, (3, 299681)),
    (299686, (3, 299683)),
    (299688, (5, 299683)),
    (299690, (7, 299683)),
    (299692, (11, 299681)),
    (299694, (11, 299683)),
    (299696, (13, 299683)),
    (299698, (17, 299681)),
    (299700, (17, 299683)),
    (299702, (3, 299699)),
    (299704, (3, 299701)),
    (299706, (5, 299701)),
    (299708, (7, 299701)),
    (299710, (11, 299699)),
    (299712, (11, 299701)),
    (299714, (3, 299711)),
    (299716, (5, 299711)),
    (299718, (7, 299711)),
    (299720, (19, 299701)),
    (299722, (11, 299711)),
    (299724, (13, 299711)),
    (299726, (3, 299723)),
    (299728, (5, 299723)),
    (299730, (7, 299723)),
    (299732, (31, 299701)),
    (299734, (3, 299731)),
    (299736, (5, 299731)),
    (299738, (7, 299731)),
    (299740, (17, 299723)),
    (299742, (11, 299731)),
    (299744, (13, 299731)),
    (299746, (3, 299743)),
    (299748, (5, 299743)),
    (299750, (7, 299743)),
    (299752, (3, 299749)),
    (299754, (5, 299749)),
    (299756, (7, 299749)),
    (299758, (47, 299711))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk029_ao_verified
