/-
AUTOGENERATED (soundness mode): Chunk [367618..367854]
    Source: chunk_036.json  •  SHA256(JSON): cec62811816fec71b90953121afff5aa4d4db2845aace19e8485549fc94be1a4
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk036_ag_verified

noncomputable section

def nLo : Nat := 367618
def nHi : Nat := 367854
def dataSHA256 : String := "cec62811816fec71b90953121afff5aa4d4db2845aace19e8485549fc94be1a4"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (367618, (5, 367613)),
    (367620, (7, 367613)),
    (367622, (19, 367603)),
    (367624, (3, 367621)),
    (367626, (5, 367621)),
    (367628, (7, 367621)),
    (367630, (17, 367613)),
    (367632, (11, 367621)),
    (367634, (13, 367621)),
    (367636, (23, 367613)),
    (367638, (17, 367621)),
    (367640, (3, 367637)),
    (367642, (5, 367637)),
    (367644, (7, 367637)),
    (367646, (43, 367603)),
    (367648, (11, 367637)),
    (367650, (13, 367637)),
    (367652, (3, 367649)),
    (367654, (3, 367651)),
    (367656, (5, 367651)),
    (367658, (7, 367651)),
    (367660, (11, 367649)),
    (367662, (11, 367651)),
    (367664, (13, 367651)),
    (367666, (3, 367663)),
    (367668, (5, 367663)),
    (367670, (7, 367663)),
    (367672, (23, 367649)),
    (367674, (11, 367663)),
    (367676, (3, 367673)),
    (367678, (5, 367673)),
    (367680, (7, 367673)),
    (367682, (19, 367663)),
    (367684, (11, 367673)),
    (367686, (13, 367673)),
    (367688, (37, 367651)),
    (367690, (3, 367687)),
    (367692, (5, 367687)),
    (367694, (7, 367687)),
    (367696, (23, 367673)),
    (367698, (11, 367687)),
    (367700, (13, 367687)),
    (367702, (3, 367699)),
    (367704, (5, 367699)),
    (367706, (7, 367699)),
    (367708, (59, 367649)),
    (367710, (11, 367699)),
    (367712, (13, 367699)),
    (367714, (3, 367711)),
    (367716, (5, 367711)),
    (367718, (7, 367711)),
    (367720, (47, 367673)),
    (367722, (11, 367711)),
    (367724, (3, 367721)),
    (367726, (5, 367721)),
    (367728, (7, 367721)),
    (367730, (19, 367711)),
    (367732, (11, 367721)),
    (367734, (13, 367721)),
    (367736, (3, 367733)),
    (367738, (5, 367733)),
    (367740, (7, 367733)),
    (367742, (3, 367739)),
    (367744, (5, 367739)),
    (367746, (7, 367739)),
    (367748, (37, 367711)),
    (367750, (11, 367739)),
    (367752, (13, 367739)),
    (367754, (3, 367751)),
    (367756, (5, 367751)),
    (367758, (7, 367751)),
    (367760, (61, 367699)),
    (367762, (11, 367751)),
    (367764, (13, 367751)),
    (367766, (67, 367699)),
    (367768, (17, 367751)),
    (367770, (19, 367751)),
    (367772, (61, 367711)),
    (367774, (3, 367771)),
    (367776, (5, 367771)),
    (367778, (7, 367771)),
    (367780, (3, 367777)),
    (367782, (5, 367777)),
    (367784, (3, 367781)),
    (367786, (5, 367781)),
    (367788, (7, 367781)),
    (367790, (13, 367777)),
    (367792, (3, 367789)),
    (367794, (5, 367789)),
    (367796, (7, 367789)),
    (367798, (17, 367781)),
    (367800, (11, 367789)),
    (367802, (13, 367789)),
    (367804, (23, 367781)),
    (367806, (17, 367789)),
    (367808, (19, 367789)),
    (367810, (29, 367781)),
    (367812, (23, 367789)),
    (367814, (37, 367777)),
    (367816, (83, 367733)),
    (367818, (29, 367789)),
    (367820, (31, 367789)),
    (367822, (3, 367819)),
    (367824, (5, 367819)),
    (367826, (3, 367823)),
    (367828, (5, 367823)),
    (367830, (7, 367823)),
    (367832, (13, 367819)),
    (367834, (3, 367831)),
    (367836, (5, 367831)),
    (367838, (7, 367831)),
    (367840, (17, 367823)),
    (367842, (11, 367831)),
    (367844, (3, 367841)),
    (367846, (5, 367841)),
    (367848, (7, 367841)),
    (367850, (19, 367831)),
    (367852, (3, 367849)),
    (367854, (5, 367849))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk036_ag_verified
