/-
AUTOGENERATED (soundness mode): Chunk [748808..749044]
    Source: chunk_074.json  •  SHA256(JSON): 9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk074_al_verified

noncomputable section

def nLo : Nat := 748808
def nHi : Nat := 749044
def dataSHA256 : String := "9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (748808, (7, 748801)),
    (748810, (3, 748807)),
    (748812, (5, 748807)),
    (748814, (7, 748807)),
    (748816, (53, 748763)),
    (748818, (11, 748807)),
    (748820, (3, 748817)),
    (748822, (3, 748819)),
    (748824, (5, 748819)),
    (748826, (3, 748823)),
    (748828, (5, 748823)),
    (748830, (7, 748823)),
    (748832, (3, 748829)),
    (748834, (3, 748831)),
    (748836, (5, 748831)),
    (748838, (7, 748831)),
    (748840, (11, 748829)),
    (748842, (11, 748831)),
    (748844, (13, 748831)),
    (748846, (17, 748829)),
    (748848, (17, 748831)),
    (748850, (19, 748831)),
    (748852, (3, 748849)),
    (748854, (5, 748849)),
    (748856, (7, 748849)),
    (748858, (29, 748829)),
    (748860, (11, 748849)),
    (748862, (13, 748849)),
    (748864, (3, 748861)),
    (748866, (5, 748861)),
    (748868, (7, 748861)),
    (748870, (41, 748829)),
    (748872, (11, 748861)),
    (748874, (3, 748871)),
    (748876, (5, 748871)),
    (748878, (7, 748871)),
    (748880, (3, 748877)),
    (748882, (5, 748877)),
    (748884, (7, 748877)),
    (748886, (3, 748883)),
    (748888, (5, 748883)),
    (748890, (7, 748883)),
    (748892, (3, 748889)),
    (748894, (5, 748889)),
    (748896, (7, 748889)),
    (748898, (37, 748861)),
    (748900, (11, 748889)),
    (748902, (13, 748889)),
    (748904, (43, 748861)),
    (748906, (17, 748889)),
    (748908, (19, 748889)),
    (748910, (61, 748849)),
    (748912, (23, 748889)),
    (748914, (31, 748883)),
    (748916, (67, 748849)),
    (748918, (29, 748889)),
    (748920, (31, 748889)),
    (748922, (61, 748861)),
    (748924, (3, 748921)),
    (748926, (5, 748921)),
    (748928, (7, 748921)),
    (748930, (41, 748889)),
    (748932, (11, 748921)),
    (748934, (13, 748921)),
    (748936, (3, 748933)),
    (748938, (5, 748933)),
    (748940, (7, 748933)),
    (748942, (53, 748889)),
    (748944, (11, 748933)),
    (748946, (13, 748933)),
    (748948, (59, 748889)),
    (748950, (17, 748933)),
    (748952, (19, 748933)),
    (748954, (71, 748883)),
    (748956, (23, 748933)),
    (748958, (37, 748921)),
    (748960, (71, 748889)),
    (748962, (29, 748933)),
    (748964, (31, 748933)),
    (748966, (3, 748963)),
    (748968, (5, 748963)),
    (748970, (7, 748963)),
    (748972, (83, 748889)),
    (748974, (11, 748963)),
    (748976, (3, 748973)),
    (748978, (5, 748973)),
    (748980, (7, 748973)),
    (748982, (19, 748963)),
    (748984, (3, 748981)),
    (748986, (5, 748981)),
    (748988, (7, 748981)),
    (748990, (3, 748987)),
    (748992, (5, 748987)),
    (748994, (7, 748987)),
    (748996, (23, 748973)),
    (748998, (11, 748987)),
    (749000, (13, 748987)),
    (749002, (29, 748973)),
    (749004, (17, 748987)),
    (749006, (19, 748987)),
    (749008, (131, 748877)),
    (749010, (23, 748987)),
    (749012, (31, 748981)),
    (749014, (3, 749011)),
    (749016, (5, 749011)),
    (749018, (7, 749011)),
    (749020, (47, 748973)),
    (749022, (11, 749011)),
    (749024, (13, 749011)),
    (749026, (53, 748973)),
    (749028, (17, 749011)),
    (749030, (3, 749027)),
    (749032, (5, 749027)),
    (749034, (7, 749027)),
    (749036, (73, 748963)),
    (749038, (11, 749027)),
    (749040, (13, 749027)),
    (749042, (31, 749011)),
    (749044, (17, 749027))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk074_al_verified
