/-
AUTOGENERATED (soundness mode): Chunk [177380..177616]
    Source: chunk_017.json  •  SHA256(JSON): eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk017_af_verified

noncomputable section

def nLo : Nat := 177380
def nHi : Nat := 177616
def dataSHA256 : String := "eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (177380, (43, 177337)),
    (177382, (3, 177379)),
    (177384, (5, 177379)),
    (177386, (3, 177383)),
    (177388, (5, 177383)),
    (177390, (7, 177383)),
    (177392, (13, 177379)),
    (177394, (11, 177383)),
    (177396, (13, 177383)),
    (177398, (19, 177379)),
    (177400, (17, 177383)),
    (177402, (19, 177383)),
    (177404, (67, 177337)),
    (177406, (23, 177383)),
    (177408, (29, 177379)),
    (177410, (31, 177379)),
    (177412, (3, 177409)),
    (177414, (5, 177409)),
    (177416, (7, 177409)),
    (177418, (71, 177347)),
    (177420, (11, 177409)),
    (177422, (13, 177409)),
    (177424, (3, 177421)),
    (177426, (5, 177421)),
    (177428, (7, 177421)),
    (177430, (3, 177427)),
    (177432, (5, 177427)),
    (177434, (3, 177431)),
    (177436, (3, 177433)),
    (177438, (5, 177433)),
    (177440, (7, 177433)),
    (177442, (11, 177431)),
    (177444, (11, 177433)),
    (177446, (13, 177433)),
    (177448, (17, 177431)),
    (177450, (17, 177433)),
    (177452, (19, 177433)),
    (177454, (23, 177431)),
    (177456, (23, 177433)),
    (177458, (31, 177427)),
    (177460, (29, 177431)),
    (177462, (29, 177433)),
    (177464, (31, 177433)),
    (177466, (83, 177383)),
    (177468, (37, 177431)),
    (177470, (3, 177467)),
    (177472, (5, 177467)),
    (177474, (7, 177467)),
    (177476, (3, 177473)),
    (177478, (5, 177473)),
    (177480, (7, 177473)),
    (177482, (61, 177421)),
    (177484, (3, 177481)),
    (177486, (5, 177481)),
    (177488, (7, 177481)),
    (177490, (3, 177487)),
    (177492, (5, 177487)),
    (177494, (7, 177487)),
    (177496, (3, 177493)),
    (177498, (5, 177493)),
    (177500, (7, 177493)),
    (177502, (29, 177473)),
    (177504, (11, 177493)),
    (177506, (13, 177493)),
    (177508, (41, 177467)),
    (177510, (17, 177493)),
    (177512, (19, 177493)),
    (177514, (3, 177511)),
    (177516, (5, 177511)),
    (177518, (7, 177511)),
    (177520, (47, 177473)),
    (177522, (11, 177511)),
    (177524, (13, 177511)),
    (177526, (53, 177473)),
    (177528, (17, 177511)),
    (177530, (19, 177511)),
    (177532, (59, 177473)),
    (177534, (23, 177511)),
    (177536, (3, 177533)),
    (177538, (5, 177533)),
    (177540, (7, 177533)),
    (177542, (3, 177539)),
    (177544, (5, 177539)),
    (177546, (7, 177539)),
    (177548, (37, 177511)),
    (177550, (11, 177539)),
    (177552, (13, 177539)),
    (177554, (43, 177511)),
    (177556, (3, 177553)),
    (177558, (5, 177553)),
    (177560, (7, 177553)),
    (177562, (23, 177539)),
    (177564, (11, 177553)),
    (177566, (13, 177553)),
    (177568, (29, 177539)),
    (177570, (17, 177553)),
    (177572, (19, 177553)),
    (177574, (41, 177533)),
    (177576, (23, 177553)),
    (177578, (67, 177511)),
    (177580, (41, 177539)),
    (177582, (29, 177553)),
    (177584, (31, 177553)),
    (177586, (47, 177539)),
    (177588, (101, 177487)),
    (177590, (37, 177553)),
    (177592, (3, 177589)),
    (177594, (5, 177589)),
    (177596, (7, 177589)),
    (177598, (59, 177539)),
    (177600, (11, 177589)),
    (177602, (13, 177589)),
    (177604, (3, 177601)),
    (177606, (5, 177601)),
    (177608, (7, 177601)),
    (177610, (71, 177539)),
    (177612, (11, 177601)),
    (177614, (13, 177601)),
    (177616, (83, 177533))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk017_af_verified
