/-
AUTOGENERATED (soundness mode): Chunk [202858..203094]
    Source: chunk_020.json  •  SHA256(JSON): f98289d997d2a6f2ba635d42ab130e17f081ab3f41ea554eba664d5a4caed00d
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk020_m_verified

noncomputable section

def nLo : Nat := 202858
def nHi : Nat := 203094
def dataSHA256 : String := "f98289d997d2a6f2ba635d42ab130e17f081ab3f41ea554eba664d5a4caed00d"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (202858, (17, 202841)),
    (202860, (19, 202841)),
    (202862, (3, 202859)),
    (202864, (5, 202859)),
    (202866, (7, 202859)),
    (202868, (139, 202729)),
    (202870, (11, 202859)),
    (202872, (13, 202859)),
    (202874, (97, 202777)),
    (202876, (17, 202859)),
    (202878, (19, 202859)),
    (202880, (3, 202877)),
    (202882, (3, 202879)),
    (202884, (5, 202879)),
    (202886, (7, 202879)),
    (202888, (11, 202877)),
    (202890, (11, 202879)),
    (202892, (3, 202889)),
    (202894, (5, 202889)),
    (202896, (7, 202889)),
    (202898, (19, 202879)),
    (202900, (11, 202889)),
    (202902, (13, 202889)),
    (202904, (127, 202777)),
    (202906, (17, 202889)),
    (202908, (19, 202889)),
    (202910, (3, 202907)),
    (202912, (5, 202907)),
    (202914, (7, 202907)),
    (202916, (37, 202879)),
    (202918, (11, 202907)),
    (202920, (13, 202907)),
    (202922, (43, 202879)),
    (202924, (3, 202921)),
    (202926, (5, 202921)),
    (202928, (7, 202921)),
    (202930, (23, 202907)),
    (202932, (11, 202921)),
    (202934, (3, 202931)),
    (202936, (3, 202933)),
    (202938, (5, 202933)),
    (202940, (7, 202933)),
    (202942, (11, 202931)),
    (202944, (11, 202933)),
    (202946, (13, 202933)),
    (202948, (17, 202931)),
    (202950, (17, 202933)),
    (202952, (3, 202949)),
    (202954, (5, 202949)),
    (202956, (7, 202949)),
    (202958, (37, 202921)),
    (202960, (11, 202949)),
    (202962, (13, 202949)),
    (202964, (31, 202933)),
    (202966, (17, 202949)),
    (202968, (19, 202949)),
    (202970, (3, 202967)),
    (202972, (5, 202967)),
    (202974, (7, 202967)),
    (202976, (3, 202973)),
    (202978, (5, 202973)),
    (202980, (7, 202973)),
    (202982, (61, 202921)),
    (202984, (3, 202981)),
    (202986, (5, 202981)),
    (202988, (7, 202981)),
    (202990, (3, 202987)),
    (202992, (5, 202987)),
    (202994, (7, 202987)),
    (202996, (23, 202973)),
    (202998, (11, 202987)),
    (203000, (13, 202987)),
    (203002, (3, 202999)),
    (203004, (5, 202999)),
    (203006, (7, 202999)),
    (203008, (41, 202967)),
    (203010, (11, 202999)),
    (203012, (13, 202999)),
    (203014, (3, 203011)),
    (203016, (5, 203011)),
    (203018, (7, 203011)),
    (203020, (3, 203017)),
    (203022, (5, 203017)),
    (203024, (7, 203017)),
    (203026, (3, 203023)),
    (203028, (5, 203023)),
    (203030, (7, 203023)),
    (203032, (59, 202973)),
    (203034, (11, 203023)),
    (203036, (13, 203023)),
    (203038, (71, 202967)),
    (203040, (17, 203023)),
    (203042, (3, 203039)),
    (203044, (5, 203039)),
    (203046, (7, 203039)),
    (203048, (31, 203017)),
    (203050, (11, 203039)),
    (203052, (13, 203039)),
    (203054, (3, 203051)),
    (203056, (5, 203051)),
    (203058, (7, 203051)),
    (203060, (3, 203057)),
    (203062, (5, 203057)),
    (203064, (7, 203057)),
    (203066, (43, 203023)),
    (203068, (11, 203057)),
    (203070, (13, 203057)),
    (203072, (61, 203011)),
    (203074, (17, 203057)),
    (203076, (19, 203057)),
    (203078, (61, 203017)),
    (203080, (23, 203057)),
    (203082, (31, 203051)),
    (203084, (61, 203023)),
    (203086, (29, 203057)),
    (203088, (31, 203057)),
    (203090, (67, 203023)),
    (203092, (41, 203051)),
    (203094, (37, 203057))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk020_m_verified
