/-
AUTOGENERATED (soundness mode): Chunk [139046..139282]
    Source: chunk_013.json  •  SHA256(JSON): 57ac00799ab751879610d350cbee1ec19f3cbe1691ad8a713bafe4b5023b8873
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk013_am_verified

noncomputable section

def nLo : Nat := 139046
def nHi : Nat := 139282
def dataSHA256 : String := "57ac00799ab751879610d350cbee1ec19f3cbe1691ad8a713bafe4b5023b8873"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (139046, (13, 139033)),
    (139048, (71, 138977)),
    (139050, (17, 139033)),
    (139052, (19, 139033)),
    (139054, (131, 138923)),
    (139056, (23, 139033)),
    (139058, (37, 139021)),
    (139060, (83, 138977)),
    (139062, (29, 139033)),
    (139064, (31, 139033)),
    (139066, (89, 138977)),
    (139068, (47, 139021)),
    (139070, (3, 139067)),
    (139072, (5, 139067)),
    (139074, (7, 139067)),
    (139076, (43, 139033)),
    (139078, (11, 139067)),
    (139080, (13, 139067)),
    (139082, (3, 139079)),
    (139084, (5, 139079)),
    (139086, (7, 139079)),
    (139088, (67, 139021)),
    (139090, (11, 139079)),
    (139092, (13, 139079)),
    (139094, (3, 139091)),
    (139096, (5, 139091)),
    (139098, (7, 139091)),
    (139100, (67, 139033)),
    (139102, (11, 139091)),
    (139104, (13, 139091)),
    (139106, (73, 139033)),
    (139108, (17, 139091)),
    (139110, (19, 139091)),
    (139112, (3, 139109)),
    (139114, (5, 139109)),
    (139116, (7, 139109)),
    (139118, (97, 139021)),
    (139120, (11, 139109)),
    (139122, (13, 139109)),
    (139124, (3, 139121)),
    (139126, (3, 139123)),
    (139128, (5, 139123)),
    (139130, (7, 139123)),
    (139132, (11, 139121)),
    (139134, (11, 139123)),
    (139136, (3, 139133)),
    (139138, (5, 139133)),
    (139140, (7, 139133)),
    (139142, (19, 139123)),
    (139144, (11, 139133)),
    (139146, (13, 139133)),
    (139148, (127, 139021)),
    (139150, (17, 139133)),
    (139152, (19, 139133)),
    (139154, (31, 139123)),
    (139156, (23, 139133)),
    (139158, (37, 139121)),
    (139160, (37, 139123)),
    (139162, (29, 139133)),
    (139164, (31, 139133)),
    (139166, (43, 139123)),
    (139168, (47, 139121)),
    (139170, (37, 139133)),
    (139172, (3, 139169)),
    (139174, (5, 139169)),
    (139176, (7, 139169)),
    (139178, (157, 139021)),
    (139180, (3, 139177)),
    (139182, (5, 139177)),
    (139184, (7, 139177)),
    (139186, (17, 139169)),
    (139188, (11, 139177)),
    (139190, (3, 139187)),
    (139192, (5, 139187)),
    (139194, (7, 139187)),
    (139196, (19, 139177)),
    (139198, (11, 139187)),
    (139200, (13, 139187)),
    (139202, (3, 139199)),
    (139204, (3, 139201)),
    (139206, (5, 139201)),
    (139208, (7, 139201)),
    (139210, (11, 139199)),
    (139212, (11, 139201)),
    (139214, (13, 139201)),
    (139216, (17, 139199)),
    (139218, (17, 139201)),
    (139220, (19, 139201)),
    (139222, (23, 139199)),
    (139224, (23, 139201)),
    (139226, (103, 139123)),
    (139228, (29, 139199)),
    (139230, (29, 139201)),
    (139232, (31, 139201)),
    (139234, (47, 139187)),
    (139236, (37, 139199)),
    (139238, (37, 139201)),
    (139240, (41, 139199)),
    (139242, (41, 139201)),
    (139244, (3, 139241)),
    (139246, (5, 139241)),
    (139248, (7, 139241)),
    (139250, (73, 139177)),
    (139252, (11, 139241)),
    (139254, (13, 139241)),
    (139256, (79, 139177)),
    (139258, (17, 139241)),
    (139260, (19, 139241)),
    (139262, (61, 139201)),
    (139264, (23, 139241)),
    (139266, (67, 139199)),
    (139268, (67, 139201)),
    (139270, (3, 139267)),
    (139272, (5, 139267)),
    (139274, (7, 139267)),
    (139276, (3, 139273)),
    (139278, (5, 139273)),
    (139280, (7, 139273)),
    (139282, (41, 139241))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk013_am_verified
