/-
AUTOGENERATED (soundness mode): Chunk [148332..148568]
    Source: chunk_014.json  •  SHA256(JSON): 8cf9aa3c89e6604102affccee9fa9b31090d48f211531979d52fd0ccc16c2c01
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk014_aj_verified

noncomputable section

def nLo : Nat := 148332
def nHi : Nat := 148568
def dataSHA256 : String := "8cf9aa3c89e6604102affccee9fa9b31090d48f211531979d52fd0ccc16c2c01"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (148332, (29, 148303)),
    (148334, (3, 148331)),
    (148336, (5, 148331)),
    (148338, (7, 148331)),
    (148340, (37, 148303)),
    (148342, (3, 148339)),
    (148344, (5, 148339)),
    (148346, (7, 148339)),
    (148348, (17, 148331)),
    (148350, (11, 148339)),
    (148352, (13, 148339)),
    (148354, (23, 148331)),
    (148356, (17, 148339)),
    (148358, (19, 148339)),
    (148360, (29, 148331)),
    (148362, (23, 148339)),
    (148364, (3, 148361)),
    (148366, (5, 148361)),
    (148368, (7, 148361)),
    (148370, (3, 148367)),
    (148372, (5, 148367)),
    (148374, (7, 148367)),
    (148376, (37, 148339)),
    (148378, (11, 148367)),
    (148380, (13, 148367)),
    (148382, (43, 148339)),
    (148384, (3, 148381)),
    (148386, (5, 148381)),
    (148388, (7, 148381)),
    (148390, (3, 148387)),
    (148392, (5, 148387)),
    (148394, (7, 148387)),
    (148396, (29, 148367)),
    (148398, (11, 148387)),
    (148400, (13, 148387)),
    (148402, (3, 148399)),
    (148404, (5, 148399)),
    (148406, (3, 148403)),
    (148408, (5, 148403)),
    (148410, (7, 148403)),
    (148412, (13, 148399)),
    (148414, (3, 148411)),
    (148416, (5, 148411)),
    (148418, (7, 148411)),
    (148420, (17, 148403)),
    (148422, (11, 148411)),
    (148424, (13, 148411)),
    (148426, (23, 148403)),
    (148428, (17, 148411)),
    (148430, (19, 148411)),
    (148432, (3, 148429)),
    (148434, (5, 148429)),
    (148436, (7, 148429)),
    (148438, (71, 148367)),
    (148440, (11, 148429)),
    (148442, (3, 148439)),
    (148444, (5, 148439)),
    (148446, (7, 148439)),
    (148448, (19, 148429)),
    (148450, (11, 148439)),
    (148452, (13, 148439)),
    (148454, (43, 148411)),
    (148456, (17, 148439)),
    (148458, (19, 148439)),
    (148460, (3, 148457)),
    (148462, (5, 148457)),
    (148464, (7, 148457)),
    (148466, (37, 148429)),
    (148468, (11, 148457)),
    (148470, (13, 148457)),
    (148472, (3, 148469)),
    (148474, (3, 148471)),
    (148476, (5, 148471)),
    (148478, (7, 148471)),
    (148480, (11, 148469)),
    (148482, (11, 148471)),
    (148484, (13, 148471)),
    (148486, (3, 148483)),
    (148488, (5, 148483)),
    (148490, (7, 148483)),
    (148492, (23, 148469)),
    (148494, (11, 148483)),
    (148496, (13, 148483)),
    (148498, (29, 148469)),
    (148500, (17, 148483)),
    (148502, (19, 148483)),
    (148504, (3, 148501)),
    (148506, (5, 148501)),
    (148508, (7, 148501)),
    (148510, (41, 148469)),
    (148512, (11, 148501)),
    (148514, (13, 148501)),
    (148516, (3, 148513)),
    (148518, (5, 148513)),
    (148520, (3, 148517)),
    (148522, (5, 148517)),
    (148524, (7, 148517)),
    (148526, (13, 148513)),
    (148528, (11, 148517)),
    (148530, (13, 148517)),
    (148532, (19, 148513)),
    (148534, (3, 148531)),
    (148536, (5, 148531)),
    (148538, (7, 148531)),
    (148540, (3, 148537)),
    (148542, (5, 148537)),
    (148544, (7, 148537)),
    (148546, (29, 148517)),
    (148548, (11, 148537)),
    (148550, (13, 148537)),
    (148552, (3, 148549)),
    (148554, (5, 148549)),
    (148556, (7, 148549)),
    (148558, (41, 148517)),
    (148560, (11, 148549)),
    (148562, (13, 148549)),
    (148564, (47, 148517)),
    (148566, (17, 148549)),
    (148568, (19, 148549))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk014_aj_verified
