/-
AUTOGENERATED (soundness mode): Chunk [993334..993570]
    Source: chunk_099.json  •  SHA256(JSON): d1699433e1b31f7dfebabd87bebd097528f2426284ff0bde636abad94d2688ae
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk099_o_verified

noncomputable section

def nLo : Nat := 993334
def nHi : Nat := 993570
def dataSHA256 : String := "d1699433e1b31f7dfebabd87bebd097528f2426284ff0bde636abad94d2688ae"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (993334, (11, 993323)),
    (993336, (13, 993323)),
    (993338, (19, 993319)),
    (993340, (17, 993323)),
    (993342, (19, 993323)),
    (993344, (3, 993341)),
    (993346, (5, 993341)),
    (993348, (7, 993341)),
    (993350, (31, 993319)),
    (993352, (11, 993341)),
    (993354, (13, 993341)),
    (993356, (37, 993319)),
    (993358, (17, 993341)),
    (993360, (19, 993341)),
    (993362, (43, 993319)),
    (993364, (23, 993341)),
    (993366, (43, 993323)),
    (993368, (127, 993241)),
    (993370, (3, 993367)),
    (993372, (5, 993367)),
    (993374, (7, 993367)),
    (993376, (53, 993323)),
    (993378, (11, 993367)),
    (993380, (13, 993367)),
    (993382, (41, 993341)),
    (993384, (17, 993367)),
    (993386, (19, 993367)),
    (993388, (47, 993341)),
    (993390, (23, 993367)),
    (993392, (73, 993319)),
    (993394, (53, 993341)),
    (993396, (29, 993367)),
    (993398, (31, 993367)),
    (993400, (3, 993397)),
    (993402, (5, 993397)),
    (993404, (3, 993401)),
    (993406, (5, 993401)),
    (993408, (7, 993401)),
    (993410, (3, 993407)),
    (993412, (5, 993407)),
    (993414, (7, 993407)),
    (993416, (19, 993397)),
    (993418, (11, 993407)),
    (993420, (13, 993407)),
    (993422, (103, 993319)),
    (993424, (17, 993407)),
    (993426, (19, 993407)),
    (993428, (31, 993397)),
    (993430, (23, 993407)),
    (993432, (31, 993401)),
    (993434, (3, 993431)),
    (993436, (5, 993431)),
    (993438, (7, 993431)),
    (993440, (3, 993437)),
    (993442, (5, 993437)),
    (993444, (7, 993437)),
    (993446, (79, 993367)),
    (993448, (11, 993437)),
    (993450, (13, 993437)),
    (993452, (199, 993253)),
    (993454, (3, 993451)),
    (993456, (5, 993451)),
    (993458, (7, 993451)),
    (993460, (23, 993437)),
    (993462, (11, 993451)),
    (993464, (13, 993451)),
    (993466, (29, 993437)),
    (993468, (17, 993451)),
    (993470, (3, 993467)),
    (993472, (5, 993467)),
    (993474, (7, 993467)),
    (993476, (79, 993397)),
    (993478, (11, 993467)),
    (993480, (13, 993467)),
    (993482, (3, 993479)),
    (993484, (3, 993481)),
    (993486, (5, 993481)),
    (993488, (7, 993481)),
    (993490, (11, 993479)),
    (993492, (11, 993481)),
    (993494, (13, 993481)),
    (993496, (3, 993493)),
    (993498, (5, 993493)),
    (993500, (7, 993493)),
    (993502, (23, 993479)),
    (993504, (11, 993493)),
    (993506, (13, 993493)),
    (993508, (29, 993479)),
    (993510, (17, 993493)),
    (993512, (19, 993493)),
    (993514, (47, 993467)),
    (993516, (23, 993493)),
    (993518, (37, 993481)),
    (993520, (41, 993479)),
    (993522, (29, 993493)),
    (993524, (31, 993493)),
    (993526, (47, 993479)),
    (993528, (47, 993481)),
    (993530, (3, 993527)),
    (993532, (5, 993527)),
    (993534, (7, 993527)),
    (993536, (43, 993493)),
    (993538, (11, 993527)),
    (993540, (13, 993527)),
    (993542, (61, 993481)),
    (993544, (3, 993541)),
    (993546, (5, 993541)),
    (993548, (7, 993541)),
    (993550, (23, 993527)),
    (993552, (11, 993541)),
    (993554, (13, 993541)),
    (993556, (29, 993527)),
    (993558, (17, 993541)),
    (993560, (3, 993557)),
    (993562, (5, 993557)),
    (993564, (7, 993557)),
    (993566, (73, 993493)),
    (993568, (11, 993557)),
    (993570, (13, 993557))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk099_o_verified
