/-
AUTOGENERATED (soundness mode): Chunk [184286..184522]
    Source: chunk_018.json  •  SHA256(JSON): 7c5e37ef0c1ebbfd2434a467de0765c02c008e2d45704c2920035243df0dc585
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk018_s_verified

noncomputable section

def nLo : Nat := 184286
def nHi : Nat := 184522
def dataSHA256 : String := "7c5e37ef0c1ebbfd2434a467de0765c02c008e2d45704c2920035243df0dc585"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (184286, (7, 184279)),
    (184288, (17, 184271)),
    (184290, (11, 184279)),
    (184292, (13, 184279)),
    (184294, (3, 184291)),
    (184296, (5, 184291)),
    (184298, (7, 184291)),
    (184300, (29, 184271)),
    (184302, (11, 184291)),
    (184304, (13, 184291)),
    (184306, (47, 184259)),
    (184308, (17, 184291)),
    (184310, (19, 184291)),
    (184312, (3, 184309)),
    (184314, (5, 184309)),
    (184316, (7, 184309)),
    (184318, (47, 184271)),
    (184320, (11, 184309)),
    (184322, (13, 184309)),
    (184324, (3, 184321)),
    (184326, (5, 184321)),
    (184328, (7, 184321)),
    (184330, (59, 184271)),
    (184332, (11, 184321)),
    (184334, (13, 184321)),
    (184336, (3, 184333)),
    (184338, (5, 184333)),
    (184340, (3, 184337)),
    (184342, (5, 184337)),
    (184344, (7, 184337)),
    (184346, (13, 184333)),
    (184348, (11, 184337)),
    (184350, (13, 184337)),
    (184352, (19, 184333)),
    (184354, (3, 184351)),
    (184356, (5, 184351)),
    (184358, (7, 184351)),
    (184360, (23, 184337)),
    (184362, (11, 184351)),
    (184364, (13, 184351)),
    (184366, (29, 184337)),
    (184368, (17, 184351)),
    (184370, (19, 184351)),
    (184372, (3, 184369)),
    (184374, (5, 184369)),
    (184376, (7, 184369)),
    (184378, (41, 184337)),
    (184380, (11, 184369)),
    (184382, (13, 184369)),
    (184384, (47, 184337)),
    (184386, (17, 184369)),
    (184388, (19, 184369)),
    (184390, (53, 184337)),
    (184392, (23, 184369)),
    (184394, (43, 184351)),
    (184396, (59, 184337)),
    (184398, (29, 184369)),
    (184400, (31, 184369)),
    (184402, (131, 184271)),
    (184404, (53, 184351)),
    (184406, (37, 184369)),
    (184408, (71, 184337)),
    (184410, (41, 184369)),
    (184412, (3, 184409)),
    (184414, (5, 184409)),
    (184416, (7, 184409)),
    (184418, (67, 184351)),
    (184420, (3, 184417)),
    (184422, (5, 184417)),
    (184424, (7, 184417)),
    (184426, (17, 184409)),
    (184428, (11, 184417)),
    (184430, (13, 184417)),
    (184432, (23, 184409)),
    (184434, (17, 184417)),
    (184436, (19, 184417)),
    (184438, (29, 184409)),
    (184440, (23, 184417)),
    (184442, (73, 184369)),
    (184444, (3, 184441)),
    (184446, (5, 184441)),
    (184448, (7, 184441)),
    (184450, (3, 184447)),
    (184452, (5, 184447)),
    (184454, (7, 184447)),
    (184456, (47, 184409)),
    (184458, (11, 184447)),
    (184460, (13, 184447)),
    (184462, (53, 184409)),
    (184464, (17, 184447)),
    (184466, (3, 184463)),
    (184468, (5, 184463)),
    (184470, (7, 184463)),
    (184472, (31, 184441)),
    (184474, (11, 184463)),
    (184476, (13, 184463)),
    (184478, (31, 184447)),
    (184480, (3, 184477)),
    (184482, (5, 184477)),
    (184484, (7, 184477)),
    (184486, (23, 184463)),
    (184488, (11, 184477)),
    (184490, (3, 184487)),
    (184492, (3, 184489)),
    (184494, (5, 184489)),
    (184496, (7, 184489)),
    (184498, (11, 184487)),
    (184500, (11, 184489)),
    (184502, (13, 184489)),
    (184504, (17, 184487)),
    (184506, (17, 184489)),
    (184508, (19, 184489)),
    (184510, (23, 184487)),
    (184512, (23, 184489)),
    (184514, (3, 184511)),
    (184516, (5, 184511)),
    (184518, (7, 184511)),
    (184520, (3, 184517)),
    (184522, (5, 184517))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk018_s_verified
