/-
AUTOGENERATED (soundness mode): Chunk [990478..990714]
    Source: chunk_099.json  •  SHA256(JSON): d1699433e1b31f7dfebabd87bebd097528f2426284ff0bde636abad94d2688ae
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk099_c_verified

noncomputable section

def nLo : Nat := 990478
def nHi : Nat := 990714
def dataSHA256 : String := "d1699433e1b31f7dfebabd87bebd097528f2426284ff0bde636abad94d2688ae"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (990478, (89, 990389)),
    (990480, (11, 990469)),
    (990482, (13, 990469)),
    (990484, (101, 990383)),
    (990486, (17, 990469)),
    (990488, (19, 990469)),
    (990490, (3, 990487)),
    (990492, (5, 990487)),
    (990494, (7, 990487)),
    (990496, (107, 990389)),
    (990498, (11, 990487)),
    (990500, (3, 990497)),
    (990502, (5, 990497)),
    (990504, (7, 990497)),
    (990506, (3, 990503)),
    (990508, (5, 990503)),
    (990510, (7, 990503)),
    (990512, (43, 990469)),
    (990514, (3, 990511)),
    (990516, (5, 990511)),
    (990518, (7, 990511)),
    (990520, (17, 990503)),
    (990522, (11, 990511)),
    (990524, (13, 990511)),
    (990526, (3, 990523)),
    (990528, (5, 990523)),
    (990530, (7, 990523)),
    (990532, (3, 990529)),
    (990534, (5, 990529)),
    (990536, (7, 990529)),
    (990538, (41, 990497)),
    (990540, (11, 990529)),
    (990542, (13, 990529)),
    (990544, (41, 990503)),
    (990546, (17, 990529)),
    (990548, (19, 990529)),
    (990550, (3, 990547)),
    (990552, (5, 990547)),
    (990554, (7, 990547)),
    (990556, (53, 990503)),
    (990558, (11, 990547)),
    (990560, (13, 990547)),
    (990562, (3, 990559)),
    (990564, (5, 990559)),
    (990566, (7, 990559)),
    (990568, (71, 990497)),
    (990570, (11, 990559)),
    (990572, (13, 990559)),
    (990574, (71, 990503)),
    (990576, (17, 990559)),
    (990578, (19, 990559)),
    (990580, (83, 990497)),
    (990582, (23, 990559)),
    (990584, (37, 990547)),
    (990586, (83, 990503)),
    (990588, (29, 990559)),
    (990590, (31, 990559)),
    (990592, (3, 990589)),
    (990594, (5, 990589)),
    (990596, (3, 990593)),
    (990598, (5, 990593)),
    (990600, (7, 990593)),
    (990602, (3, 990599)),
    (990604, (5, 990599)),
    (990606, (7, 990599)),
    (990608, (19, 990589)),
    (990610, (11, 990599)),
    (990612, (13, 990599)),
    (990614, (67, 990547)),
    (990616, (17, 990599)),
    (990618, (19, 990599)),
    (990620, (31, 990589)),
    (990622, (23, 990599)),
    (990624, (31, 990593)),
    (990626, (37, 990589)),
    (990628, (29, 990599)),
    (990630, (31, 990599)),
    (990632, (43, 990589)),
    (990634, (3, 990631)),
    (990636, (5, 990631)),
    (990638, (7, 990631)),
    (990640, (3, 990637)),
    (990642, (5, 990637)),
    (990644, (7, 990637)),
    (990646, (3, 990643)),
    (990648, (5, 990643)),
    (990650, (7, 990643)),
    (990652, (53, 990599)),
    (990654, (11, 990643)),
    (990656, (13, 990643)),
    (990658, (59, 990599)),
    (990660, (17, 990643)),
    (990662, (19, 990643)),
    (990664, (71, 990593)),
    (990666, (23, 990643)),
    (990668, (31, 990637)),
    (990670, (71, 990599)),
    (990672, (29, 990643)),
    (990674, (31, 990643)),
    (990676, (3, 990673)),
    (990678, (5, 990673)),
    (990680, (7, 990673)),
    (990682, (83, 990599)),
    (990684, (11, 990673)),
    (990686, (13, 990673)),
    (990688, (89, 990599)),
    (990690, (17, 990673)),
    (990692, (19, 990673)),
    (990694, (101, 990593)),
    (990696, (23, 990673)),
    (990698, (61, 990637)),
    (990700, (101, 990599)),
    (990702, (29, 990673)),
    (990704, (31, 990673)),
    (990706, (107, 990599)),
    (990708, (71, 990637)),
    (990710, (3, 990707)),
    (990712, (5, 990707)),
    (990714, (7, 990707))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk099_c_verified
