/-
AUTOGENERATED (soundness mode): Chunk [390002..390238]
    Source: chunk_039.json  •  SHA256(JSON): 483b26fd3755bedc6017fe0a4b6016e215b79fa2ddc72bf3bb60de1318685369
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk039_a_verified

noncomputable section

def nLo : Nat := 390002
def nHi : Nat := 390238
def dataSHA256 : String := "483b26fd3755bedc6017fe0a4b6016e215b79fa2ddc72bf3bb60de1318685369"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (390002, (3, 389999)),
    (390004, (3, 390001)),
    (390006, (5, 390001)),
    (390008, (7, 390001)),
    (390010, (11, 389999)),
    (390012, (11, 390001)),
    (390014, (13, 390001)),
    (390016, (17, 389999)),
    (390018, (17, 390001)),
    (390020, (19, 390001)),
    (390022, (23, 389999)),
    (390024, (23, 390001)),
    (390026, (37, 389989)),
    (390028, (29, 389999)),
    (390030, (29, 390001)),
    (390032, (31, 390001)),
    (390034, (53, 389981)),
    (390036, (37, 389999)),
    (390038, (37, 390001)),
    (390040, (41, 389999)),
    (390042, (41, 390001)),
    (390044, (43, 390001)),
    (390046, (3, 390043)),
    (390048, (5, 390043)),
    (390050, (7, 390043)),
    (390052, (53, 389999)),
    (390054, (11, 390043)),
    (390056, (13, 390043)),
    (390058, (59, 389999)),
    (390060, (17, 390043)),
    (390062, (19, 390043)),
    (390064, (83, 389981)),
    (390066, (23, 390043)),
    (390068, (67, 390001)),
    (390070, (3, 390067)),
    (390072, (5, 390067)),
    (390074, (7, 390067)),
    (390076, (149, 389927)),
    (390078, (11, 390067)),
    (390080, (3, 390077)),
    (390082, (5, 390077)),
    (390084, (7, 390077)),
    (390086, (3, 390083)),
    (390088, (5, 390083)),
    (390090, (7, 390083)),
    (390092, (103, 389989)),
    (390094, (11, 390083)),
    (390096, (13, 390083)),
    (390098, (31, 390067)),
    (390100, (3, 390097)),
    (390102, (5, 390097)),
    (390104, (3, 390101)),
    (390106, (5, 390101)),
    (390108, (7, 390101)),
    (390110, (3, 390107)),
    (390112, (3, 390109)),
    (390114, (5, 390109)),
    (390116, (3, 390113)),
    (390118, (5, 390113)),
    (390120, (7, 390113)),
    (390122, (3, 390119)),
    (390124, (5, 390119)),
    (390126, (7, 390119)),
    (390128, (19, 390109)),
    (390130, (11, 390119)),
    (390132, (13, 390119)),
    (390134, (37, 390097)),
    (390136, (17, 390119)),
    (390138, (19, 390119)),
    (390140, (31, 390109)),
    (390142, (23, 390119)),
    (390144, (31, 390113)),
    (390146, (37, 390109)),
    (390148, (29, 390119)),
    (390150, (31, 390119)),
    (390152, (43, 390109)),
    (390154, (3, 390151)),
    (390156, (5, 390151)),
    (390158, (7, 390151)),
    (390160, (3, 390157)),
    (390162, (5, 390157)),
    (390164, (3, 390161)),
    (390166, (5, 390161)),
    (390168, (7, 390161)),
    (390170, (13, 390157)),
    (390172, (11, 390161)),
    (390174, (13, 390161)),
    (390176, (19, 390157)),
    (390178, (17, 390161)),
    (390180, (19, 390161)),
    (390182, (31, 390151)),
    (390184, (23, 390161)),
    (390186, (29, 390157)),
    (390188, (31, 390157)),
    (390190, (29, 390161)),
    (390192, (31, 390161)),
    (390194, (3, 390191)),
    (390196, (3, 390193)),
    (390198, (5, 390193)),
    (390200, (7, 390193)),
    (390202, (3, 390199)),
    (390204, (5, 390199)),
    (390206, (7, 390199)),
    (390208, (17, 390191)),
    (390210, (11, 390199)),
    (390212, (3, 390209)),
    (390214, (3, 390211)),
    (390216, (5, 390211)),
    (390218, (7, 390211)),
    (390220, (11, 390209)),
    (390222, (11, 390211)),
    (390224, (13, 390211)),
    (390226, (3, 390223)),
    (390228, (5, 390223)),
    (390230, (7, 390223)),
    (390232, (23, 390209)),
    (390234, (11, 390223)),
    (390236, (13, 390223)),
    (390238, (29, 390209))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk039_a_verified
