/-
AUTOGENERATED (soundness mode): Chunk [326904..327140]
    Source: chunk_032.json  •  SHA256(JSON): 2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk032_ad_verified

noncomputable section

def nLo : Nat := 326904
def nHi : Nat := 327140
def dataSHA256 : String := "2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (326904, (23, 326881)),
    (326906, (3, 326903)),
    (326908, (5, 326903)),
    (326910, (7, 326903)),
    (326912, (31, 326881)),
    (326914, (11, 326903)),
    (326916, (13, 326903)),
    (326918, (37, 326881)),
    (326920, (17, 326903)),
    (326922, (19, 326903)),
    (326924, (43, 326881)),
    (326926, (3, 326923)),
    (326928, (5, 326923)),
    (326930, (7, 326923)),
    (326932, (29, 326903)),
    (326934, (11, 326923)),
    (326936, (13, 326923)),
    (326938, (71, 326867)),
    (326940, (17, 326923)),
    (326942, (3, 326939)),
    (326944, (3, 326941)),
    (326946, (5, 326941)),
    (326948, (7, 326941)),
    (326950, (3, 326947)),
    (326952, (5, 326947)),
    (326954, (3, 326951)),
    (326956, (5, 326951)),
    (326958, (7, 326951)),
    (326960, (13, 326947)),
    (326962, (11, 326951)),
    (326964, (13, 326951)),
    (326966, (19, 326947)),
    (326968, (17, 326951)),
    (326970, (19, 326951)),
    (326972, (31, 326941)),
    (326974, (23, 326951)),
    (326976, (29, 326947)),
    (326978, (31, 326947)),
    (326980, (29, 326951)),
    (326982, (31, 326951)),
    (326984, (37, 326947)),
    (326986, (3, 326983)),
    (326988, (5, 326983)),
    (326990, (7, 326983)),
    (326992, (41, 326951)),
    (326994, (11, 326983)),
    (326996, (3, 326993)),
    (326998, (5, 326993)),
    (327000, (7, 326993)),
    (327002, (3, 326999)),
    (327004, (3, 327001)),
    (327006, (5, 327001)),
    (327008, (7, 327001)),
    (327010, (3, 327007)),
    (327012, (5, 327007)),
    (327014, (3, 327011)),
    (327016, (5, 327011)),
    (327018, (7, 327011)),
    (327020, (3, 327017)),
    (327022, (5, 327017)),
    (327024, (7, 327017)),
    (327026, (3, 327023)),
    (327028, (5, 327023)),
    (327030, (7, 327023)),
    (327032, (31, 327001)),
    (327034, (11, 327023)),
    (327036, (13, 327023)),
    (327038, (31, 327007)),
    (327040, (17, 327023)),
    (327042, (19, 327023)),
    (327044, (37, 327007)),
    (327046, (23, 327023)),
    (327048, (31, 327017)),
    (327050, (43, 327007)),
    (327052, (29, 327023)),
    (327054, (31, 327023)),
    (327056, (73, 326983)),
    (327058, (41, 327017)),
    (327060, (37, 327023)),
    (327062, (3, 327059)),
    (327064, (5, 327059)),
    (327066, (7, 327059)),
    (327068, (61, 327007)),
    (327070, (11, 327059)),
    (327072, (13, 327059)),
    (327074, (3, 327071)),
    (327076, (5, 327071)),
    (327078, (7, 327071)),
    (327080, (73, 327007)),
    (327082, (3, 327079)),
    (327084, (5, 327079)),
    (327086, (7, 327079)),
    (327088, (17, 327071)),
    (327090, (11, 327079)),
    (327092, (13, 327079)),
    (327094, (23, 327071)),
    (327096, (17, 327079)),
    (327098, (19, 327079)),
    (327100, (29, 327071)),
    (327102, (23, 327079)),
    (327104, (97, 327007)),
    (327106, (47, 327059)),
    (327108, (29, 327079)),
    (327110, (31, 327079)),
    (327112, (41, 327071)),
    (327114, (43, 327071)),
    (327116, (37, 327079)),
    (327118, (47, 327071)),
    (327120, (41, 327079)),
    (327122, (43, 327079)),
    (327124, (53, 327071)),
    (327126, (47, 327079)),
    (327128, (127, 327001)),
    (327130, (3, 327127)),
    (327132, (5, 327127)),
    (327134, (7, 327127)),
    (327136, (3, 327133)),
    (327138, (5, 327133)),
    (327140, (7, 327133))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk032_ad_verified
