/-
AUTOGENERATED (soundness mode): Chunk [917380..917616]
    Source: chunk_091.json  •  SHA256(JSON): 0aa6120a4bd9910c4b652c97d25a3180eb2d1cb3b878de3af11deb4add6f3fc7
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk091_af_verified

noncomputable section

def nLo : Nat := 917380
def nHi : Nat := 917616
def dataSHA256 : String := "0aa6120a4bd9910c4b652c97d25a3180eb2d1cb3b878de3af11deb4add6f3fc7"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (917380, (17, 917363)),
    (917382, (19, 917363)),
    (917384, (3, 917381)),
    (917386, (5, 917381)),
    (917388, (7, 917381)),
    (917390, (37, 917353)),
    (917392, (11, 917381)),
    (917394, (13, 917381)),
    (917396, (43, 917353)),
    (917398, (17, 917381)),
    (917400, (19, 917381)),
    (917402, (151, 917251)),
    (917404, (23, 917381)),
    (917406, (43, 917363)),
    (917408, (127, 917281)),
    (917410, (3, 917407)),
    (917412, (5, 917407)),
    (917414, (7, 917407)),
    (917416, (53, 917363)),
    (917418, (11, 917407)),
    (917420, (13, 917407)),
    (917422, (41, 917381)),
    (917424, (17, 917407)),
    (917426, (19, 917407)),
    (917428, (47, 917381)),
    (917430, (23, 917407)),
    (917432, (79, 917353)),
    (917434, (53, 917381)),
    (917436, (29, 917407)),
    (917438, (31, 917407)),
    (917440, (59, 917381)),
    (917442, (61, 917381)),
    (917444, (37, 917407)),
    (917446, (3, 917443)),
    (917448, (5, 917443)),
    (917450, (7, 917443)),
    (917452, (71, 917381)),
    (917454, (11, 917443)),
    (917456, (13, 917443)),
    (917458, (131, 917327)),
    (917460, (17, 917443)),
    (917462, (3, 917459)),
    (917464, (3, 917461)),
    (917466, (5, 917461)),
    (917468, (7, 917461)),
    (917470, (11, 917459)),
    (917472, (11, 917461)),
    (917474, (3, 917471)),
    (917476, (5, 917471)),
    (917478, (7, 917471)),
    (917480, (19, 917461)),
    (917482, (11, 917471)),
    (917484, (13, 917471)),
    (917486, (43, 917443)),
    (917488, (17, 917471)),
    (917490, (19, 917471)),
    (917492, (31, 917461)),
    (917494, (23, 917471)),
    (917496, (37, 917459)),
    (917498, (37, 917461)),
    (917500, (29, 917471)),
    (917502, (31, 917471)),
    (917504, (43, 917461)),
    (917506, (3, 917503)),
    (917508, (5, 917503)),
    (917510, (7, 917503)),
    (917512, (41, 917471)),
    (917514, (11, 917503)),
    (917516, (3, 917513)),
    (917518, (5, 917513)),
    (917520, (7, 917513)),
    (917522, (3, 917519)),
    (917524, (5, 917519)),
    (917526, (7, 917519)),
    (917528, (67, 917461)),
    (917530, (11, 917519)),
    (917532, (13, 917519)),
    (917534, (31, 917503)),
    (917536, (17, 917519)),
    (917538, (19, 917519)),
    (917540, (37, 917503)),
    (917542, (23, 917519)),
    (917544, (31, 917513)),
    (917546, (43, 917503)),
    (917548, (29, 917519)),
    (917550, (31, 917519)),
    (917552, (3, 917549)),
    (917554, (5, 917549)),
    (917556, (7, 917549)),
    (917558, (97, 917461)),
    (917560, (3, 917557)),
    (917562, (5, 917557)),
    (917564, (7, 917557)),
    (917566, (17, 917549)),
    (917568, (11, 917557)),
    (917570, (13, 917557)),
    (917572, (23, 917549)),
    (917574, (17, 917557)),
    (917576, (3, 917573)),
    (917578, (5, 917573)),
    (917580, (7, 917573)),
    (917582, (79, 917503)),
    (917584, (11, 917573)),
    (917586, (13, 917573)),
    (917588, (31, 917557)),
    (917590, (17, 917573)),
    (917592, (19, 917573)),
    (917594, (3, 917591)),
    (917596, (3, 917593)),
    (917598, (5, 917593)),
    (917600, (7, 917593)),
    (917602, (11, 917591)),
    (917604, (11, 917593)),
    (917606, (13, 917593)),
    (917608, (17, 917591)),
    (917610, (17, 917593)),
    (917612, (19, 917593)),
    (917614, (3, 917611)),
    (917616, (5, 917611))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk091_af_verified
