/-
AUTOGENERATED (soundness mode): Chunk [44524..44760]
    Source: chunk_004.json  •  SHA256(JSON): e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk004_t_verified

noncomputable section

def nLo : Nat := 44524
def nHi : Nat := 44760
def dataSHA256 : String := "e68e644e04da20389867f4813517fc3c3f2902543ab919599818085cd2cf8ec5"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (44524, (5, 44519)),
    (44526, (7, 44519)),
    (44528, (31, 44497)),
    (44530, (11, 44519)),
    (44532, (13, 44519)),
    (44534, (3, 44531)),
    (44536, (3, 44533)),
    (44538, (5, 44533)),
    (44540, (3, 44537)),
    (44542, (5, 44537)),
    (44544, (7, 44537)),
    (44546, (3, 44543)),
    (44548, (5, 44543)),
    (44550, (7, 44543)),
    (44552, (3, 44549)),
    (44554, (5, 44549)),
    (44556, (7, 44549)),
    (44558, (61, 44497)),
    (44560, (11, 44549)),
    (44562, (13, 44549)),
    (44564, (31, 44533)),
    (44566, (3, 44563)),
    (44568, (5, 44563)),
    (44570, (7, 44563)),
    (44572, (23, 44549)),
    (44574, (11, 44563)),
    (44576, (13, 44563)),
    (44578, (29, 44549)),
    (44580, (17, 44563)),
    (44582, (3, 44579)),
    (44584, (5, 44579)),
    (44586, (7, 44579)),
    (44588, (97, 44491)),
    (44590, (3, 44587)),
    (44592, (5, 44587)),
    (44594, (7, 44587)),
    (44596, (17, 44579)),
    (44598, (11, 44587)),
    (44600, (13, 44587)),
    (44602, (23, 44579)),
    (44604, (17, 44587)),
    (44606, (19, 44587)),
    (44608, (29, 44579)),
    (44610, (23, 44587)),
    (44612, (79, 44533)),
    (44614, (71, 44543)),
    (44616, (29, 44587)),
    (44618, (31, 44587)),
    (44620, (3, 44617)),
    (44622, (5, 44617)),
    (44624, (3, 44621)),
    (44626, (3, 44623)),
    (44628, (5, 44623)),
    (44630, (7, 44623)),
    (44632, (11, 44621)),
    (44634, (11, 44623)),
    (44636, (3, 44633)),
    (44638, (5, 44633)),
    (44640, (7, 44633)),
    (44642, (19, 44623)),
    (44644, (3, 44641)),
    (44646, (5, 44641)),
    (44648, (7, 44641)),
    (44650, (3, 44647)),
    (44652, (5, 44647)),
    (44654, (3, 44651)),
    (44656, (5, 44651)),
    (44658, (7, 44651)),
    (44660, (3, 44657)),
    (44662, (5, 44657)),
    (44664, (7, 44657)),
    (44666, (19, 44647)),
    (44668, (11, 44657)),
    (44670, (13, 44657)),
    (44672, (31, 44641)),
    (44674, (17, 44657)),
    (44676, (19, 44657)),
    (44678, (31, 44647)),
    (44680, (23, 44657)),
    (44682, (31, 44651)),
    (44684, (37, 44647)),
    (44686, (3, 44683)),
    (44688, (5, 44683)),
    (44690, (3, 44687)),
    (44692, (5, 44687)),
    (44694, (7, 44687)),
    (44696, (13, 44683)),
    (44698, (11, 44687)),
    (44700, (13, 44687)),
    (44702, (3, 44699)),
    (44704, (3, 44701)),
    (44706, (5, 44701)),
    (44708, (7, 44701)),
    (44710, (11, 44699)),
    (44712, (11, 44701)),
    (44714, (3, 44711)),
    (44716, (5, 44711)),
    (44718, (7, 44711)),
    (44720, (19, 44701)),
    (44722, (11, 44711)),
    (44724, (13, 44711)),
    (44726, (43, 44683)),
    (44728, (17, 44711)),
    (44730, (19, 44711)),
    (44732, (3, 44729)),
    (44734, (5, 44729)),
    (44736, (7, 44729)),
    (44738, (37, 44701)),
    (44740, (11, 44729)),
    (44742, (13, 44729)),
    (44744, (3, 44741)),
    (44746, (5, 44741)),
    (44748, (7, 44741)),
    (44750, (67, 44683)),
    (44752, (11, 44741)),
    (44754, (13, 44741)),
    (44756, (3, 44753)),
    (44758, (5, 44753)),
    (44760, (7, 44753))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk004_t_verified
