/-
AUTOGENERATED (soundness mode): Chunk [448570..448806]
    Source: chunk_044.json  •  SHA256(JSON): fab3a2a0d9e6b8e22e08b422d83f150b1047585c6855884ed1992872fe8c0dfd
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk044_ak_verified

noncomputable section

def nLo : Nat := 448570
def nHi : Nat := 448806
def dataSHA256 : String := "fab3a2a0d9e6b8e22e08b422d83f150b1047585c6855884ed1992872fe8c0dfd"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (448570, (149, 448421)),
    (448572, (11, 448561)),
    (448574, (13, 448561)),
    (448576, (179, 448397)),
    (448578, (17, 448561)),
    (448580, (19, 448561)),
    (448582, (131, 448451)),
    (448584, (23, 448561)),
    (448586, (67, 448519)),
    (448588, (137, 448451)),
    (448590, (29, 448561)),
    (448592, (31, 448561)),
    (448594, (173, 448421)),
    (448596, (199, 448397)),
    (448598, (37, 448561)),
    (448600, (3, 448597)),
    (448602, (5, 448597)),
    (448604, (7, 448597)),
    (448606, (227, 448379)),
    (448608, (11, 448597)),
    (448610, (3, 448607)),
    (448612, (5, 448607)),
    (448614, (7, 448607)),
    (448616, (19, 448597)),
    (448618, (11, 448607)),
    (448620, (13, 448607)),
    (448622, (61, 448561)),
    (448624, (17, 448607)),
    (448626, (19, 448607)),
    (448628, (31, 448597)),
    (448630, (3, 448627)),
    (448632, (5, 448627)),
    (448634, (3, 448631)),
    (448636, (3, 448633)),
    (448638, (5, 448633)),
    (448640, (7, 448633)),
    (448642, (11, 448631)),
    (448644, (11, 448633)),
    (448646, (13, 448633)),
    (448648, (17, 448631)),
    (448650, (17, 448633)),
    (448652, (19, 448633)),
    (448654, (23, 448631)),
    (448656, (23, 448633)),
    (448658, (31, 448627)),
    (448660, (29, 448631)),
    (448662, (29, 448633)),
    (448664, (31, 448633)),
    (448666, (59, 448607)),
    (448668, (37, 448631)),
    (448670, (3, 448667)),
    (448672, (5, 448667)),
    (448674, (7, 448667)),
    (448676, (43, 448633)),
    (448678, (11, 448667)),
    (448680, (13, 448667)),
    (448682, (151, 448531)),
    (448684, (17, 448667)),
    (448686, (19, 448667)),
    (448688, (61, 448627)),
    (448690, (3, 448687)),
    (448692, (5, 448687)),
    (448694, (7, 448687)),
    (448696, (29, 448667)),
    (448698, (11, 448687)),
    (448700, (3, 448697)),
    (448702, (5, 448697)),
    (448704, (7, 448697)),
    (448706, (3, 448703)),
    (448708, (5, 448703)),
    (448710, (7, 448703)),
    (448712, (79, 448633)),
    (448714, (11, 448703)),
    (448716, (13, 448703)),
    (448718, (31, 448687)),
    (448720, (17, 448703)),
    (448722, (19, 448703)),
    (448724, (37, 448687)),
    (448726, (23, 448703)),
    (448728, (31, 448697)),
    (448730, (3, 448727)),
    (448732, (5, 448727)),
    (448734, (7, 448727)),
    (448736, (3, 448733)),
    (448738, (5, 448733)),
    (448740, (7, 448733)),
    (448742, (109, 448633)),
    (448744, (3, 448741)),
    (448746, (5, 448741)),
    (448748, (7, 448741)),
    (448750, (17, 448733)),
    (448752, (11, 448741)),
    (448754, (13, 448741)),
    (448756, (23, 448733)),
    (448758, (17, 448741)),
    (448760, (19, 448741)),
    (448762, (29, 448733)),
    (448764, (23, 448741)),
    (448766, (79, 448687)),
    (448768, (41, 448727)),
    (448770, (29, 448741)),
    (448772, (3, 448769)),
    (448774, (5, 448769)),
    (448776, (7, 448769)),
    (448778, (37, 448741)),
    (448780, (11, 448769)),
    (448782, (13, 448769)),
    (448784, (43, 448741)),
    (448786, (17, 448769)),
    (448788, (19, 448769)),
    (448790, (103, 448687)),
    (448792, (23, 448769)),
    (448794, (53, 448741)),
    (448796, (3, 448793)),
    (448798, (5, 448793)),
    (448800, (7, 448793)),
    (448802, (61, 448741)),
    (448804, (3, 448801)),
    (448806, (5, 448801))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk044_ak_verified
