/-
AUTOGENERATED (soundness mode): Chunk [365000..365236]
    Source: chunk_036.json  •  SHA256(JSON): cec62811816fec71b90953121afff5aa4d4db2845aace19e8485549fc94be1a4
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk036_v_verified

noncomputable section

def nLo : Nat := 365000
def nHi : Nat := 365236
def dataSHA256 : String := "cec62811816fec71b90953121afff5aa4d4db2845aace19e8485549fc94be1a4"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (365000, (3, 364997)),
    (365002, (5, 364997)),
    (365004, (7, 364997)),
    (365006, (3, 365003)),
    (365008, (5, 365003)),
    (365010, (7, 365003)),
    (365012, (19, 364993)),
    (365014, (11, 365003)),
    (365016, (13, 365003)),
    (365018, (97, 364921)),
    (365020, (3, 365017)),
    (365022, (5, 365017)),
    (365024, (3, 365021)),
    (365026, (5, 365021)),
    (365028, (7, 365021)),
    (365030, (13, 365017)),
    (365032, (11, 365021)),
    (365034, (13, 365021)),
    (365036, (19, 365017)),
    (365038, (17, 365021)),
    (365040, (19, 365021)),
    (365042, (3, 365039)),
    (365044, (5, 365039)),
    (365046, (7, 365039)),
    (365048, (31, 365017)),
    (365050, (11, 365039)),
    (365052, (13, 365039)),
    (365054, (37, 365017)),
    (365056, (17, 365039)),
    (365058, (19, 365039)),
    (365060, (43, 365017)),
    (365062, (23, 365039)),
    (365064, (43, 365021)),
    (365066, (3, 365063)),
    (365068, (5, 365063)),
    (365070, (7, 365063)),
    (365072, (3, 365069)),
    (365074, (5, 365069)),
    (365076, (7, 365069)),
    (365078, (61, 365017)),
    (365080, (11, 365069)),
    (365082, (13, 365069)),
    (365084, (67, 365017)),
    (365086, (17, 365069)),
    (365088, (19, 365069)),
    (365090, (73, 365017)),
    (365092, (3, 365089)),
    (365094, (5, 365089)),
    (365096, (7, 365089)),
    (365098, (29, 365069)),
    (365100, (11, 365089)),
    (365102, (13, 365089)),
    (365104, (41, 365063)),
    (365106, (17, 365089)),
    (365108, (19, 365089)),
    (365110, (3, 365107)),
    (365112, (5, 365107)),
    (365114, (7, 365107)),
    (365116, (47, 365069)),
    (365118, (11, 365107)),
    (365120, (13, 365107)),
    (365122, (3, 365119)),
    (365124, (5, 365119)),
    (365126, (7, 365119)),
    (365128, (59, 365069)),
    (365130, (11, 365119)),
    (365132, (3, 365129)),
    (365134, (5, 365129)),
    (365136, (7, 365129)),
    (365138, (19, 365119)),
    (365140, (3, 365137)),
    (365142, (5, 365137)),
    (365144, (7, 365137)),
    (365146, (17, 365129)),
    (365148, (11, 365137)),
    (365150, (3, 365147)),
    (365152, (5, 365147)),
    (365154, (7, 365147)),
    (365156, (19, 365137)),
    (365158, (11, 365147)),
    (365160, (13, 365147)),
    (365162, (3, 365159)),
    (365164, (5, 365159)),
    (365166, (7, 365159)),
    (365168, (31, 365137)),
    (365170, (11, 365159)),
    (365172, (13, 365159)),
    (365174, (37, 365137)),
    (365176, (3, 365173)),
    (365178, (5, 365173)),
    (365180, (7, 365173)),
    (365182, (3, 365179)),
    (365184, (5, 365179)),
    (365186, (7, 365179)),
    (365188, (29, 365159)),
    (365190, (11, 365179)),
    (365192, (13, 365179)),
    (365194, (47, 365147)),
    (365196, (17, 365179)),
    (365198, (19, 365179)),
    (365200, (41, 365159)),
    (365202, (23, 365179)),
    (365204, (3, 365201)),
    (365206, (5, 365201)),
    (365208, (7, 365201)),
    (365210, (31, 365179)),
    (365212, (11, 365201)),
    (365214, (13, 365201)),
    (365216, (3, 365213)),
    (365218, (5, 365213)),
    (365220, (7, 365213)),
    (365222, (43, 365179)),
    (365224, (11, 365213)),
    (365226, (13, 365213)),
    (365228, (109, 365119)),
    (365230, (17, 365213)),
    (365232, (19, 365213)),
    (365234, (3, 365231)),
    (365236, (5, 365231))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk036_v_verified
