/-
AUTOGENERATED (soundness mode): Chunk [973096..973332]
    Source: chunk_097.json  •  SHA256(JSON): 967ea33cae8693b6c98002f566079f434e4094c4d8c746278a9e56ce8c6a3c36
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk097_n_verified

noncomputable section

def nLo : Nat := 973096
def nHi : Nat := 973332
def dataSHA256 : String := "967ea33cae8693b6c98002f566079f434e4094c4d8c746278a9e56ce8c6a3c36"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (973096, (23, 973073)),
    (973098, (17, 973081)),
    (973100, (19, 973081)),
    (973102, (3, 973099)),
    (973104, (5, 973099)),
    (973106, (7, 973099)),
    (973108, (41, 973067)),
    (973110, (11, 973099)),
    (973112, (13, 973099)),
    (973114, (41, 973073)),
    (973116, (17, 973099)),
    (973118, (19, 973099)),
    (973120, (47, 973073)),
    (973122, (23, 973099)),
    (973124, (43, 973081)),
    (973126, (53, 973073)),
    (973128, (29, 973099)),
    (973130, (31, 973099)),
    (973132, (3, 973129)),
    (973134, (5, 973129)),
    (973136, (7, 973129)),
    (973138, (71, 973067)),
    (973140, (11, 973129)),
    (973142, (13, 973129)),
    (973144, (71, 973073)),
    (973146, (17, 973129)),
    (973148, (19, 973129)),
    (973150, (83, 973067)),
    (973152, (23, 973129)),
    (973154, (3, 973151)),
    (973156, (5, 973151)),
    (973158, (7, 973151)),
    (973160, (31, 973129)),
    (973162, (11, 973151)),
    (973164, (13, 973151)),
    (973166, (37, 973129)),
    (973168, (17, 973151)),
    (973170, (19, 973151)),
    (973172, (3, 973169)),
    (973174, (5, 973169)),
    (973176, (7, 973169)),
    (973178, (79, 973099)),
    (973180, (3, 973177)),
    (973182, (5, 973177)),
    (973184, (7, 973177)),
    (973186, (17, 973169)),
    (973188, (11, 973177)),
    (973190, (3, 973187)),
    (973192, (5, 973187)),
    (973194, (7, 973187)),
    (973196, (19, 973177)),
    (973198, (11, 973187)),
    (973200, (13, 973187)),
    (973202, (73, 973129)),
    (973204, (17, 973187)),
    (973206, (19, 973187)),
    (973208, (31, 973177)),
    (973210, (23, 973187)),
    (973212, (43, 973169)),
    (973214, (37, 973177)),
    (973216, (3, 973213)),
    (973218, (5, 973213)),
    (973220, (7, 973213)),
    (973222, (53, 973169)),
    (973224, (11, 973213)),
    (973226, (13, 973213)),
    (973228, (41, 973187)),
    (973230, (17, 973213)),
    (973232, (19, 973213)),
    (973234, (47, 973187)),
    (973236, (23, 973213)),
    (973238, (61, 973177)),
    (973240, (53, 973187)),
    (973242, (29, 973213)),
    (973244, (31, 973213)),
    (973246, (59, 973187)),
    (973248, (61, 973187)),
    (973250, (37, 973213)),
    (973252, (83, 973169)),
    (973254, (41, 973213)),
    (973256, (3, 973253)),
    (973258, (5, 973253)),
    (973260, (7, 973253)),
    (973262, (163, 973099)),
    (973264, (11, 973253)),
    (973266, (13, 973253)),
    (973268, (139, 973129)),
    (973270, (17, 973253)),
    (973272, (19, 973253)),
    (973274, (61, 973213)),
    (973276, (23, 973253)),
    (973278, (101, 973177)),
    (973280, (3, 973277)),
    (973282, (3, 973279)),
    (973284, (5, 973279)),
    (973286, (3, 973283)),
    (973288, (5, 973283)),
    (973290, (7, 973283)),
    (973292, (3, 973289)),
    (973294, (5, 973289)),
    (973296, (7, 973289)),
    (973298, (19, 973279)),
    (973300, (11, 973289)),
    (973302, (13, 973289)),
    (973304, (127, 973177)),
    (973306, (17, 973289)),
    (973308, (19, 973289)),
    (973310, (31, 973279)),
    (973312, (23, 973289)),
    (973314, (31, 973283)),
    (973316, (37, 973279)),
    (973318, (29, 973289)),
    (973320, (31, 973289)),
    (973322, (43, 973279)),
    (973324, (3, 973321)),
    (973326, (5, 973321)),
    (973328, (7, 973321)),
    (973330, (41, 973289)),
    (973332, (11, 973321))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk097_n_verified
