/-
AUTOGENERATED (soundness mode): Chunk [413096..413332]
    Source: chunk_041.json  •  SHA256(JSON): c850a2cbd010a481a199e44353d480c5dcc0b3c7d167c56d5f44bd68d8821460
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk041_n_verified

noncomputable section

def nLo : Nat := 413096
def nHi : Nat := 413332
def dataSHA256 : String := "c850a2cbd010a481a199e44353d480c5dcc0b3c7d167c56d5f44bd68d8821460"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (413096, (3, 413093)),
    (413098, (5, 413093)),
    (413100, (7, 413093)),
    (413102, (13, 413089)),
    (413104, (11, 413093)),
    (413106, (13, 413093)),
    (413108, (19, 413089)),
    (413110, (17, 413093)),
    (413112, (19, 413093)),
    (413114, (3, 413111)),
    (413116, (3, 413113)),
    (413118, (5, 413113)),
    (413120, (7, 413113)),
    (413122, (11, 413111)),
    (413124, (11, 413113)),
    (413126, (13, 413113)),
    (413128, (17, 413111)),
    (413130, (17, 413113)),
    (413132, (3, 413129)),
    (413134, (5, 413129)),
    (413136, (7, 413129)),
    (413138, (67, 413071)),
    (413140, (11, 413129)),
    (413142, (13, 413129)),
    (413144, (3, 413141)),
    (413146, (3, 413143)),
    (413148, (5, 413143)),
    (413150, (7, 413143)),
    (413152, (11, 413141)),
    (413154, (11, 413143)),
    (413156, (13, 413143)),
    (413158, (17, 413141)),
    (413160, (17, 413143)),
    (413162, (3, 413159)),
    (413164, (5, 413159)),
    (413166, (7, 413159)),
    (413168, (79, 413089)),
    (413170, (3, 413167)),
    (413172, (5, 413167)),
    (413174, (7, 413167)),
    (413176, (17, 413159)),
    (413178, (11, 413167)),
    (413180, (13, 413167)),
    (413182, (23, 413159)),
    (413184, (17, 413167)),
    (413186, (3, 413183)),
    (413188, (5, 413183)),
    (413190, (7, 413183)),
    (413192, (79, 413113)),
    (413194, (11, 413183)),
    (413196, (13, 413183)),
    (413198, (31, 413167)),
    (413200, (3, 413197)),
    (413202, (5, 413197)),
    (413204, (3, 413201)),
    (413206, (5, 413201)),
    (413208, (7, 413201)),
    (413210, (3, 413207)),
    (413212, (5, 413207)),
    (413214, (7, 413207)),
    (413216, (19, 413197)),
    (413218, (11, 413207)),
    (413220, (13, 413207)),
    (413222, (79, 413143)),
    (413224, (17, 413207)),
    (413226, (19, 413207)),
    (413228, (31, 413197)),
    (413230, (23, 413207)),
    (413232, (31, 413201)),
    (413234, (37, 413197)),
    (413236, (3, 413233)),
    (413238, (5, 413233)),
    (413240, (7, 413233)),
    (413242, (41, 413201)),
    (413244, (11, 413233)),
    (413246, (3, 413243)),
    (413248, (5, 413243)),
    (413250, (7, 413243)),
    (413252, (19, 413233)),
    (413254, (3, 413251)),
    (413256, (5, 413251)),
    (413258, (7, 413251)),
    (413260, (17, 413243)),
    (413262, (11, 413251)),
    (413264, (13, 413251)),
    (413266, (3, 413263)),
    (413268, (5, 413263)),
    (413270, (3, 413267)),
    (413272, (5, 413267)),
    (413274, (7, 413267)),
    (413276, (13, 413263)),
    (413278, (11, 413267)),
    (413280, (13, 413267)),
    (413282, (19, 413263)),
    (413284, (17, 413267)),
    (413286, (19, 413267)),
    (413288, (37, 413251)),
    (413290, (23, 413267)),
    (413292, (29, 413263)),
    (413294, (31, 413263)),
    (413296, (3, 413293)),
    (413298, (5, 413293)),
    (413300, (7, 413293)),
    (413302, (3, 413299)),
    (413304, (5, 413299)),
    (413306, (7, 413299)),
    (413308, (41, 413267)),
    (413310, (11, 413299)),
    (413312, (13, 413299)),
    (413314, (47, 413267)),
    (413316, (17, 413299)),
    (413318, (19, 413299)),
    (413320, (53, 413267)),
    (413322, (23, 413299)),
    (413324, (31, 413293)),
    (413326, (59, 413267)),
    (413328, (29, 413299)),
    (413330, (31, 413299)),
    (413332, (89, 413243))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk041_n_verified
