/-
AUTOGENERATED (soundness mode): Chunk [291430..291666]
    Source: chunk_029.json  •  SHA256(JSON): de7dd53f13071a968ee73359bff62faf3edbe00b0afdcf7b83c0d5d837117ed9
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk029_g_verified

noncomputable section

def nLo : Nat := 291430
def nHi : Nat := 291666
def dataSHA256 : String := "de7dd53f13071a968ee73359bff62faf3edbe00b0afdcf7b83c0d5d837117ed9"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (291430, (11, 291419)),
    (291432, (13, 291419)),
    (291434, (61, 291373)),
    (291436, (17, 291419)),
    (291438, (19, 291419)),
    (291440, (3, 291437)),
    (291442, (3, 291439)),
    (291444, (5, 291439)),
    (291446, (3, 291443)),
    (291448, (5, 291443)),
    (291450, (7, 291443)),
    (291452, (13, 291439)),
    (291454, (11, 291443)),
    (291456, (13, 291443)),
    (291458, (19, 291439)),
    (291460, (3, 291457)),
    (291462, (5, 291457)),
    (291464, (7, 291457)),
    (291466, (23, 291443)),
    (291468, (11, 291457)),
    (291470, (13, 291457)),
    (291472, (29, 291443)),
    (291474, (17, 291457)),
    (291476, (19, 291457)),
    (291478, (41, 291437)),
    (291480, (23, 291457)),
    (291482, (43, 291439)),
    (291484, (3, 291481)),
    (291486, (5, 291481)),
    (291488, (7, 291481)),
    (291490, (47, 291443)),
    (291492, (11, 291481)),
    (291494, (3, 291491)),
    (291496, (5, 291491)),
    (291498, (7, 291491)),
    (291500, (19, 291481)),
    (291502, (11, 291491)),
    (291504, (13, 291491)),
    (291506, (3, 291503)),
    (291508, (5, 291503)),
    (291510, (7, 291503)),
    (291512, (3, 291509)),
    (291514, (5, 291509)),
    (291516, (7, 291509)),
    (291518, (37, 291481)),
    (291520, (11, 291509)),
    (291522, (13, 291509)),
    (291524, (3, 291521)),
    (291526, (5, 291521)),
    (291528, (7, 291521)),
    (291530, (73, 291457)),
    (291532, (11, 291521)),
    (291534, (13, 291521)),
    (291536, (79, 291457)),
    (291538, (17, 291521)),
    (291540, (19, 291521)),
    (291542, (3, 291539)),
    (291544, (5, 291539)),
    (291546, (7, 291539)),
    (291548, (67, 291481)),
    (291550, (3, 291547)),
    (291552, (5, 291547)),
    (291554, (7, 291547)),
    (291556, (17, 291539)),
    (291558, (11, 291547)),
    (291560, (13, 291547)),
    (291562, (3, 291559)),
    (291564, (5, 291559)),
    (291566, (3, 291563)),
    (291568, (5, 291563)),
    (291570, (7, 291563)),
    (291572, (3, 291569)),
    (291574, (5, 291569)),
    (291576, (7, 291569)),
    (291578, (19, 291559)),
    (291580, (11, 291569)),
    (291582, (13, 291569)),
    (291584, (37, 291547)),
    (291586, (17, 291569)),
    (291588, (19, 291569)),
    (291590, (31, 291559)),
    (291592, (23, 291569)),
    (291594, (31, 291563)),
    (291596, (37, 291559)),
    (291598, (29, 291569)),
    (291600, (31, 291569)),
    (291602, (43, 291559)),
    (291604, (41, 291563)),
    (291606, (37, 291569)),
    (291608, (61, 291547)),
    (291610, (41, 291569)),
    (291612, (43, 291569)),
    (291614, (67, 291547)),
    (291616, (47, 291569)),
    (291618, (59, 291559)),
    (291620, (61, 291559)),
    (291622, (3, 291619)),
    (291624, (5, 291619)),
    (291626, (7, 291619)),
    (291628, (59, 291569)),
    (291630, (11, 291619)),
    (291632, (13, 291619)),
    (291634, (71, 291563)),
    (291636, (17, 291619)),
    (291638, (19, 291619)),
    (291640, (71, 291569)),
    (291642, (23, 291619)),
    (291644, (97, 291547)),
    (291646, (83, 291563)),
    (291648, (29, 291619)),
    (291650, (3, 291647)),
    (291652, (3, 291649)),
    (291654, (5, 291649)),
    (291656, (7, 291649)),
    (291658, (11, 291647)),
    (291660, (11, 291649)),
    (291662, (13, 291649)),
    (291664, (3, 291661)),
    (291666, (5, 291661))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk029_g_verified
