/-
AUTOGENERATED (soundness mode): Chunk [514762..514998]
    Source: chunk_051.json  •  SHA256(JSON): 1ac5e30d7de773f8e9b418b6b8e42733a9c1ed0d82b45fface144c7f08a311a3
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk051_u_verified

noncomputable section

def nLo : Nat := 514762
def nHi : Nat := 514998
def dataSHA256 : String := "1ac5e30d7de773f8e9b418b6b8e42733a9c1ed0d82b45fface144c7f08a311a3"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (514762, (5, 514757)),
    (514764, (7, 514757)),
    (514766, (19, 514747)),
    (514768, (11, 514757)),
    (514770, (13, 514757)),
    (514772, (3, 514769)),
    (514774, (5, 514769)),
    (514776, (7, 514769)),
    (514778, (31, 514747)),
    (514780, (11, 514769)),
    (514782, (13, 514769)),
    (514784, (37, 514747)),
    (514786, (3, 514783)),
    (514788, (5, 514783)),
    (514790, (7, 514783)),
    (514792, (23, 514769)),
    (514794, (11, 514783)),
    (514796, (3, 514793)),
    (514798, (5, 514793)),
    (514800, (7, 514793)),
    (514802, (19, 514783)),
    (514804, (11, 514793)),
    (514806, (13, 514793)),
    (514808, (61, 514747)),
    (514810, (17, 514793)),
    (514812, (19, 514793)),
    (514814, (31, 514783)),
    (514816, (23, 514793)),
    (514818, (61, 514757)),
    (514820, (37, 514783)),
    (514822, (3, 514819)),
    (514824, (5, 514819)),
    (514826, (3, 514823)),
    (514828, (5, 514823)),
    (514830, (7, 514823)),
    (514832, (13, 514819)),
    (514834, (3, 514831)),
    (514836, (5, 514831)),
    (514838, (7, 514831)),
    (514840, (17, 514823)),
    (514842, (11, 514831)),
    (514844, (3, 514841)),
    (514846, (5, 514841)),
    (514848, (7, 514841)),
    (514850, (3, 514847)),
    (514852, (5, 514847)),
    (514854, (7, 514847)),
    (514856, (3, 514853)),
    (514858, (5, 514853)),
    (514860, (7, 514853)),
    (514862, (3, 514859)),
    (514864, (5, 514859)),
    (514866, (7, 514859)),
    (514868, (37, 514831)),
    (514870, (3, 514867)),
    (514872, (5, 514867)),
    (514874, (7, 514867)),
    (514876, (3, 514873)),
    (514878, (5, 514873)),
    (514880, (7, 514873)),
    (514882, (23, 514859)),
    (514884, (11, 514873)),
    (514886, (13, 514873)),
    (514888, (29, 514859)),
    (514890, (17, 514873)),
    (514892, (3, 514889)),
    (514894, (5, 514889)),
    (514896, (7, 514889)),
    (514898, (31, 514867)),
    (514900, (11, 514889)),
    (514902, (13, 514889)),
    (514904, (31, 514873)),
    (514906, (3, 514903)),
    (514908, (5, 514903)),
    (514910, (7, 514903)),
    (514912, (23, 514889)),
    (514914, (11, 514903)),
    (514916, (13, 514903)),
    (514918, (29, 514889)),
    (514920, (17, 514903)),
    (514922, (19, 514903)),
    (514924, (71, 514853)),
    (514926, (23, 514903)),
    (514928, (61, 514867)),
    (514930, (41, 514889)),
    (514932, (29, 514903)),
    (514934, (31, 514903)),
    (514936, (3, 514933)),
    (514938, (5, 514933)),
    (514940, (7, 514933)),
    (514942, (3, 514939)),
    (514944, (5, 514939)),
    (514946, (7, 514939)),
    (514948, (59, 514889)),
    (514950, (11, 514939)),
    (514952, (3, 514949)),
    (514954, (5, 514949)),
    (514956, (7, 514949)),
    (514958, (19, 514939)),
    (514960, (11, 514949)),
    (514962, (13, 514949)),
    (514964, (31, 514933)),
    (514966, (17, 514949)),
    (514968, (19, 514949)),
    (514970, (3, 514967)),
    (514972, (5, 514967)),
    (514974, (7, 514967)),
    (514976, (37, 514939)),
    (514978, (11, 514967)),
    (514980, (13, 514967)),
    (514982, (43, 514939)),
    (514984, (17, 514967)),
    (514986, (19, 514967)),
    (514988, (157, 514831)),
    (514990, (23, 514967)),
    (514992, (43, 514949)),
    (514994, (61, 514933)),
    (514996, (29, 514967)),
    (514998, (31, 514967))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk051_u_verified
