/-
AUTOGENERATED (soundness mode): Chunk [67618..67854]
    Source: chunk_006.json  •  SHA256(JSON): 3a9f814f70834b4b7917fb00b6f27fd5d58826487f24473228ae53d5c5b0cdb1
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk006_ag_verified

noncomputable section

def nLo : Nat := 67618
def nHi : Nat := 67854
def dataSHA256 : String := "3a9f814f70834b4b7917fb00b6f27fd5d58826487f24473228ae53d5c5b0cdb1"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (67618, (11, 67607)),
    (67620, (13, 67607)),
    (67622, (3, 67619)),
    (67624, (5, 67619)),
    (67626, (7, 67619)),
    (67628, (61, 67567)),
    (67630, (11, 67619)),
    (67632, (13, 67619)),
    (67634, (3, 67631)),
    (67636, (5, 67631)),
    (67638, (7, 67631)),
    (67640, (61, 67579)),
    (67642, (11, 67631)),
    (67644, (13, 67631)),
    (67646, (67, 67579)),
    (67648, (17, 67631)),
    (67650, (19, 67631)),
    (67652, (73, 67579)),
    (67654, (3, 67651)),
    (67656, (5, 67651)),
    (67658, (7, 67651)),
    (67660, (29, 67631)),
    (67662, (11, 67651)),
    (67664, (13, 67651)),
    (67666, (47, 67619)),
    (67668, (17, 67651)),
    (67670, (19, 67651)),
    (67672, (41, 67631)),
    (67674, (23, 67651)),
    (67676, (97, 67579)),
    (67678, (47, 67631)),
    (67680, (29, 67651)),
    (67682, (3, 67679)),
    (67684, (5, 67679)),
    (67686, (7, 67679)),
    (67688, (37, 67651)),
    (67690, (11, 67679)),
    (67692, (13, 67679)),
    (67694, (43, 67651)),
    (67696, (17, 67679)),
    (67698, (19, 67679)),
    (67700, (163, 67537)),
    (67702, (3, 67699)),
    (67704, (5, 67699)),
    (67706, (7, 67699)),
    (67708, (29, 67679)),
    (67710, (11, 67699)),
    (67712, (3, 67709)),
    (67714, (5, 67709)),
    (67716, (7, 67709)),
    (67718, (19, 67699)),
    (67720, (11, 67709)),
    (67722, (13, 67709)),
    (67724, (73, 67651)),
    (67726, (3, 67723)),
    (67728, (5, 67723)),
    (67730, (7, 67723)),
    (67732, (23, 67709)),
    (67734, (11, 67723)),
    (67736, (3, 67733)),
    (67738, (5, 67733)),
    (67740, (7, 67733)),
    (67742, (19, 67723)),
    (67744, (3, 67741)),
    (67746, (5, 67741)),
    (67748, (7, 67741)),
    (67750, (17, 67733)),
    (67752, (11, 67741)),
    (67754, (3, 67751)),
    (67756, (5, 67751)),
    (67758, (7, 67751)),
    (67760, (3, 67757)),
    (67762, (3, 67759)),
    (67764, (5, 67759)),
    (67766, (3, 67763)),
    (67768, (5, 67763)),
    (67770, (7, 67763)),
    (67772, (13, 67759)),
    (67774, (11, 67763)),
    (67776, (13, 67763)),
    (67778, (19, 67759)),
    (67780, (3, 67777)),
    (67782, (5, 67777)),
    (67784, (7, 67777)),
    (67786, (3, 67783)),
    (67788, (5, 67783)),
    (67790, (7, 67783)),
    (67792, (3, 67789)),
    (67794, (5, 67789)),
    (67796, (7, 67789)),
    (67798, (41, 67757)),
    (67800, (11, 67789)),
    (67802, (13, 67789)),
    (67804, (3, 67801)),
    (67806, (5, 67801)),
    (67808, (7, 67801)),
    (67810, (3, 67807)),
    (67812, (5, 67807)),
    (67814, (7, 67807)),
    (67816, (53, 67763)),
    (67818, (11, 67807)),
    (67820, (13, 67807)),
    (67822, (3, 67819)),
    (67824, (5, 67819)),
    (67826, (7, 67819)),
    (67828, (71, 67757)),
    (67830, (11, 67819)),
    (67832, (3, 67829)),
    (67834, (5, 67829)),
    (67836, (7, 67829)),
    (67838, (19, 67819)),
    (67840, (11, 67829)),
    (67842, (13, 67829)),
    (67844, (37, 67807)),
    (67846, (3, 67843)),
    (67848, (5, 67843)),
    (67850, (7, 67843)),
    (67852, (23, 67829)),
    (67854, (11, 67843))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk006_ag_verified
