/-
AUTOGENERATED (soundness mode): Chunk [864762..864998]
    Source: chunk_086.json  •  SHA256(JSON): 7e793807e11b9d9b004b8f5c5b540eb02dd873c2c1ffd565856ef9e397a1358b
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk086_u_verified

noncomputable section

def nLo : Nat := 864762
def nHi : Nat := 864998
def dataSHA256 : String := "7e793807e11b9d9b004b8f5c5b540eb02dd873c2c1ffd565856ef9e397a1358b"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (864762, (5, 864757)),
    (864764, (7, 864757)),
    (864766, (29, 864737)),
    (864768, (11, 864757)),
    (864770, (13, 864757)),
    (864772, (131, 864641)),
    (864774, (17, 864757)),
    (864776, (19, 864757)),
    (864778, (41, 864737)),
    (864780, (23, 864757)),
    (864782, (103, 864679)),
    (864784, (3, 864781)),
    (864786, (5, 864781)),
    (864788, (7, 864781)),
    (864790, (53, 864737)),
    (864792, (11, 864781)),
    (864794, (13, 864781)),
    (864796, (3, 864793)),
    (864798, (5, 864793)),
    (864800, (7, 864793)),
    (864802, (173, 864629)),
    (864804, (11, 864793)),
    (864806, (3, 864803)),
    (864808, (5, 864803)),
    (864810, (7, 864803)),
    (864812, (19, 864793)),
    (864814, (3, 864811)),
    (864816, (5, 864811)),
    (864818, (7, 864811)),
    (864820, (3, 864817)),
    (864822, (5, 864817)),
    (864824, (7, 864817)),
    (864826, (23, 864803)),
    (864828, (11, 864817)),
    (864830, (13, 864817)),
    (864832, (29, 864803)),
    (864834, (17, 864817)),
    (864836, (19, 864817)),
    (864838, (101, 864737)),
    (864840, (23, 864817)),
    (864842, (31, 864811)),
    (864844, (41, 864803)),
    (864846, (29, 864817)),
    (864848, (31, 864817)),
    (864850, (47, 864803)),
    (864852, (41, 864811)),
    (864854, (37, 864817)),
    (864856, (53, 864803)),
    (864858, (41, 864817)),
    (864860, (43, 864817)),
    (864862, (59, 864803)),
    (864864, (47, 864817)),
    (864866, (73, 864793)),
    (864868, (131, 864737)),
    (864870, (53, 864817)),
    (864872, (61, 864811)),
    (864874, (71, 864803)),
    (864876, (59, 864817)),
    (864878, (61, 864817)),
    (864880, (173, 864707)),
    (864882, (71, 864811)),
    (864884, (67, 864817)),
    (864886, (3, 864883)),
    (864888, (5, 864883)),
    (864890, (3, 864887)),
    (864892, (5, 864887)),
    (864894, (7, 864887)),
    (864896, (13, 864883)),
    (864898, (11, 864887)),
    (864900, (13, 864887)),
    (864902, (19, 864883)),
    (864904, (3, 864901)),
    (864906, (5, 864901)),
    (864908, (7, 864901)),
    (864910, (23, 864887)),
    (864912, (11, 864901)),
    (864914, (3, 864911)),
    (864916, (5, 864911)),
    (864918, (7, 864911)),
    (864920, (3, 864917)),
    (864922, (5, 864917)),
    (864924, (7, 864917)),
    (864926, (43, 864883)),
    (864928, (11, 864917)),
    (864930, (13, 864917)),
    (864932, (31, 864901)),
    (864934, (17, 864917)),
    (864936, (19, 864917)),
    (864938, (37, 864901)),
    (864940, (23, 864917)),
    (864942, (31, 864911)),
    (864944, (43, 864901)),
    (864946, (29, 864917)),
    (864948, (31, 864917)),
    (864950, (3, 864947)),
    (864952, (5, 864947)),
    (864954, (7, 864947)),
    (864956, (3, 864953)),
    (864958, (5, 864953)),
    (864960, (7, 864953)),
    (864962, (3, 864959)),
    (864964, (5, 864959)),
    (864966, (7, 864959)),
    (864968, (67, 864901)),
    (864970, (3, 864967)),
    (864972, (5, 864967)),
    (864974, (7, 864967)),
    (864976, (17, 864959)),
    (864978, (11, 864967)),
    (864980, (13, 864967)),
    (864982, (3, 864979)),
    (864984, (5, 864979)),
    (864986, (7, 864979)),
    (864988, (29, 864959)),
    (864990, (11, 864979)),
    (864992, (3, 864989)),
    (864994, (5, 864989)),
    (864996, (7, 864989)),
    (864998, (19, 864979))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk086_u_verified
