/-
AUTOGENERATED (soundness mode): Chunk [837618..837854]
    Source: chunk_083.json  •  SHA256(JSON): ab7b2f15cd46eab2b032cc8b02479cc27b55f49dd3975df5d6f54d80f46d18f8
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk083_ag_verified

noncomputable section

def nLo : Nat := 837618
def nHi : Nat := 837854
def dataSHA256 : String := "ab7b2f15cd46eab2b032cc8b02479cc27b55f49dd3975df5d6f54d80f46d18f8"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (837618, (7, 837611)),
    (837620, (19, 837601)),
    (837622, (3, 837619)),
    (837624, (5, 837619)),
    (837626, (7, 837619)),
    (837628, (17, 837611)),
    (837630, (11, 837619)),
    (837632, (13, 837619)),
    (837634, (3, 837631)),
    (837636, (5, 837631)),
    (837638, (7, 837631)),
    (837640, (29, 837611)),
    (837642, (11, 837631)),
    (837644, (13, 837631)),
    (837646, (113, 837533)),
    (837648, (17, 837631)),
    (837650, (19, 837631)),
    (837652, (41, 837611)),
    (837654, (23, 837631)),
    (837656, (37, 837619)),
    (837658, (47, 837611)),
    (837660, (29, 837631)),
    (837662, (3, 837659)),
    (837664, (5, 837659)),
    (837666, (7, 837659)),
    (837668, (37, 837631)),
    (837670, (3, 837667)),
    (837672, (5, 837667)),
    (837674, (7, 837667)),
    (837676, (3, 837673)),
    (837678, (5, 837673)),
    (837680, (3, 837677)),
    (837682, (3, 837679)),
    (837684, (5, 837679)),
    (837686, (7, 837679)),
    (837688, (11, 837677)),
    (837690, (11, 837679)),
    (837692, (13, 837679)),
    (837694, (17, 837677)),
    (837696, (17, 837679)),
    (837698, (19, 837679)),
    (837700, (23, 837677)),
    (837702, (23, 837679)),
    (837704, (31, 837673)),
    (837706, (29, 837677)),
    (837708, (29, 837679)),
    (837710, (31, 837679)),
    (837712, (53, 837659)),
    (837714, (37, 837677)),
    (837716, (37, 837679)),
    (837718, (41, 837677)),
    (837720, (41, 837679)),
    (837722, (43, 837679)),
    (837724, (3, 837721)),
    (837726, (5, 837721)),
    (837728, (7, 837721)),
    (837730, (53, 837677)),
    (837732, (11, 837721)),
    (837734, (3, 837731)),
    (837736, (5, 837731)),
    (837738, (7, 837731)),
    (837740, (3, 837737)),
    (837742, (5, 837737)),
    (837744, (7, 837737)),
    (837746, (67, 837679)),
    (837748, (11, 837737)),
    (837750, (13, 837737)),
    (837752, (31, 837721)),
    (837754, (17, 837737)),
    (837756, (19, 837737)),
    (837758, (37, 837721)),
    (837760, (23, 837737)),
    (837762, (31, 837731)),
    (837764, (43, 837721)),
    (837766, (29, 837737)),
    (837768, (31, 837737)),
    (837770, (97, 837673)),
    (837772, (41, 837731)),
    (837774, (37, 837737)),
    (837776, (3, 837773)),
    (837778, (5, 837773)),
    (837780, (7, 837773)),
    (837782, (3, 837779)),
    (837784, (5, 837779)),
    (837786, (7, 837779)),
    (837788, (67, 837721)),
    (837790, (11, 837779)),
    (837792, (13, 837779)),
    (837794, (73, 837721)),
    (837796, (17, 837779)),
    (837798, (19, 837779)),
    (837800, (3, 837797)),
    (837802, (5, 837797)),
    (837804, (7, 837797)),
    (837806, (127, 837679)),
    (837808, (11, 837797)),
    (837810, (13, 837797)),
    (837812, (139, 837673)),
    (837814, (17, 837797)),
    (837816, (19, 837797)),
    (837818, (97, 837721)),
    (837820, (3, 837817)),
    (837822, (5, 837817)),
    (837824, (7, 837817)),
    (837826, (29, 837797)),
    (837828, (11, 837817)),
    (837830, (13, 837817)),
    (837832, (53, 837779)),
    (837834, (17, 837817)),
    (837836, (3, 837833)),
    (837838, (5, 837833)),
    (837840, (7, 837833)),
    (837842, (163, 837679)),
    (837844, (11, 837833)),
    (837846, (13, 837833)),
    (837848, (31, 837817)),
    (837850, (3, 837847)),
    (837852, (5, 837847)),
    (837854, (7, 837847))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk083_ag_verified
