/-
AUTOGENERATED (soundness mode): Chunk [595952..596188]
    Source: chunk_059.json  •  SHA256(JSON): 159fc8bad1a16ac0c1ea98c5ef2ee3071b1e865e2a286482c5c354acf434bb42
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk059_z_verified

noncomputable section

def nLo : Nat := 595952
def nHi : Nat := 596188
def dataSHA256 : String := "159fc8bad1a16ac0c1ea98c5ef2ee3071b1e865e2a286482c5c354acf434bb42"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (595952, (3, 595949)),
    (595954, (3, 595951)),
    (595956, (5, 595951)),
    (595958, (7, 595951)),
    (595960, (3, 595957)),
    (595962, (5, 595957)),
    (595964, (3, 595961)),
    (595966, (3, 595963)),
    (595968, (5, 595963)),
    (595970, (3, 595967)),
    (595972, (5, 595967)),
    (595974, (7, 595967)),
    (595976, (13, 595963)),
    (595978, (11, 595967)),
    (595980, (13, 595967)),
    (595982, (19, 595963)),
    (595984, (3, 595981)),
    (595986, (5, 595981)),
    (595988, (7, 595981)),
    (595990, (23, 595967)),
    (595992, (11, 595981)),
    (595994, (13, 595981)),
    (595996, (29, 595967)),
    (595998, (17, 595981)),
    (596000, (19, 595981)),
    (596002, (41, 595961)),
    (596004, (23, 595981)),
    (596006, (43, 595963)),
    (596008, (41, 595967)),
    (596010, (29, 595981)),
    (596012, (3, 596009)),
    (596014, (5, 596009)),
    (596016, (7, 596009)),
    (596018, (37, 595981)),
    (596020, (11, 596009)),
    (596022, (13, 596009)),
    (596024, (3, 596021)),
    (596026, (5, 596021)),
    (596028, (7, 596021)),
    (596030, (3, 596027)),
    (596032, (5, 596027)),
    (596034, (7, 596027)),
    (596036, (73, 595963)),
    (596038, (11, 596027)),
    (596040, (13, 596027)),
    (596042, (61, 595981)),
    (596044, (17, 596027)),
    (596046, (19, 596027)),
    (596048, (67, 595981)),
    (596050, (3, 596047)),
    (596052, (5, 596047)),
    (596054, (7, 596047)),
    (596056, (3, 596053)),
    (596058, (5, 596053)),
    (596060, (7, 596053)),
    (596062, (3, 596059)),
    (596064, (5, 596059)),
    (596066, (7, 596059)),
    (596068, (41, 596027)),
    (596070, (11, 596059)),
    (596072, (3, 596069)),
    (596074, (5, 596069)),
    (596076, (7, 596069)),
    (596078, (19, 596059)),
    (596080, (11, 596069)),
    (596082, (13, 596069)),
    (596084, (3, 596081)),
    (596086, (3, 596083)),
    (596088, (5, 596083)),
    (596090, (7, 596083)),
    (596092, (11, 596081)),
    (596094, (11, 596083)),
    (596096, (3, 596093)),
    (596098, (5, 596093)),
    (596100, (7, 596093)),
    (596102, (19, 596083)),
    (596104, (11, 596093)),
    (596106, (13, 596093)),
    (596108, (61, 596047)),
    (596110, (17, 596093)),
    (596112, (19, 596093)),
    (596114, (31, 596083)),
    (596116, (23, 596093)),
    (596118, (37, 596081)),
    (596120, (3, 596117)),
    (596122, (3, 596119)),
    (596124, (5, 596119)),
    (596126, (7, 596119)),
    (596128, (11, 596117)),
    (596130, (11, 596119)),
    (596132, (13, 596119)),
    (596134, (17, 596117)),
    (596136, (17, 596119)),
    (596138, (19, 596119)),
    (596140, (23, 596117)),
    (596142, (23, 596119)),
    (596144, (61, 596083)),
    (596146, (3, 596143)),
    (596148, (5, 596143)),
    (596150, (3, 596147)),
    (596152, (5, 596147)),
    (596154, (7, 596147)),
    (596156, (13, 596143)),
    (596158, (11, 596147)),
    (596160, (13, 596147)),
    (596162, (3, 596159)),
    (596164, (5, 596159)),
    (596166, (7, 596159)),
    (596168, (109, 596059)),
    (596170, (11, 596159)),
    (596172, (13, 596159)),
    (596174, (31, 596143)),
    (596176, (17, 596159)),
    (596178, (19, 596159)),
    (596180, (37, 596143)),
    (596182, (3, 596179)),
    (596184, (5, 596179)),
    (596186, (7, 596179)),
    (596188, (29, 596159))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk059_z_verified
