/-
AUTOGENERATED (soundness mode): Chunk [176190..176426]
    Source: chunk_017.json  •  SHA256(JSON): eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk017_aa_verified

noncomputable section

def nLo : Nat := 176190
def nHi : Nat := 176426
def dataSHA256 : String := "eb2be603c87ea9e45879f0e38abc23d0f87d160f1b1553e225bb698cd1596f2e"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (176190, (11, 176179)),
    (176192, (13, 176179)),
    (176194, (3, 176191)),
    (176196, (5, 176191)),
    (176198, (7, 176191)),
    (176200, (41, 176159)),
    (176202, (11, 176191)),
    (176204, (3, 176201)),
    (176206, (5, 176201)),
    (176208, (7, 176201)),
    (176210, (3, 176207)),
    (176212, (5, 176207)),
    (176214, (7, 176207)),
    (176216, (3, 176213)),
    (176218, (5, 176213)),
    (176220, (7, 176213)),
    (176222, (31, 176191)),
    (176224, (3, 176221)),
    (176226, (5, 176221)),
    (176228, (7, 176221)),
    (176230, (3, 176227)),
    (176232, (5, 176227)),
    (176234, (7, 176227)),
    (176236, (23, 176213)),
    (176238, (11, 176227)),
    (176240, (3, 176237)),
    (176242, (5, 176237)),
    (176244, (7, 176237)),
    (176246, (3, 176243)),
    (176248, (5, 176243)),
    (176250, (7, 176243)),
    (176252, (31, 176221)),
    (176254, (11, 176243)),
    (176256, (13, 176243)),
    (176258, (31, 176227)),
    (176260, (17, 176243)),
    (176262, (19, 176243)),
    (176264, (3, 176261)),
    (176266, (5, 176261)),
    (176268, (7, 176261)),
    (176270, (43, 176227)),
    (176272, (11, 176261)),
    (176274, (13, 176261)),
    (176276, (97, 176179)),
    (176278, (17, 176261)),
    (176280, (19, 176261)),
    (176282, (61, 176221)),
    (176284, (23, 176261)),
    (176286, (43, 176243)),
    (176288, (61, 176227)),
    (176290, (29, 176261)),
    (176292, (31, 176261)),
    (176294, (67, 176227)),
    (176296, (53, 176243)),
    (176298, (37, 176261)),
    (176300, (73, 176227)),
    (176302, (3, 176299)),
    (176304, (5, 176299)),
    (176306, (3, 176303)),
    (176308, (5, 176303)),
    (176310, (7, 176303)),
    (176312, (13, 176299)),
    (176314, (11, 176303)),
    (176316, (13, 176303)),
    (176318, (19, 176299)),
    (176320, (3, 176317)),
    (176322, (5, 176317)),
    (176324, (3, 176321)),
    (176326, (5, 176321)),
    (176328, (7, 176321)),
    (176330, (3, 176327)),
    (176332, (3, 176329)),
    (176334, (5, 176329)),
    (176336, (3, 176333)),
    (176338, (5, 176333)),
    (176340, (7, 176333)),
    (176342, (13, 176329)),
    (176344, (11, 176333)),
    (176346, (13, 176333)),
    (176348, (19, 176329)),
    (176350, (3, 176347)),
    (176352, (5, 176347)),
    (176354, (7, 176347)),
    (176356, (3, 176353)),
    (176358, (5, 176353)),
    (176360, (3, 176357)),
    (176362, (5, 176357)),
    (176364, (7, 176357)),
    (176366, (13, 176353)),
    (176368, (11, 176357)),
    (176370, (13, 176357)),
    (176372, (3, 176369)),
    (176374, (5, 176369)),
    (176376, (7, 176369)),
    (176378, (31, 176347)),
    (176380, (11, 176369)),
    (176382, (13, 176369)),
    (176384, (31, 176353)),
    (176386, (3, 176383)),
    (176388, (5, 176383)),
    (176390, (7, 176383)),
    (176392, (3, 176389)),
    (176394, (5, 176389)),
    (176396, (7, 176389)),
    (176398, (29, 176369)),
    (176400, (11, 176389)),
    (176402, (13, 176389)),
    (176404, (3, 176401)),
    (176406, (5, 176401)),
    (176408, (7, 176401)),
    (176410, (41, 176369)),
    (176412, (11, 176401)),
    (176414, (13, 176401)),
    (176416, (3, 176413)),
    (176418, (5, 176413)),
    (176420, (3, 176417)),
    (176422, (3, 176419)),
    (176424, (5, 176419)),
    (176426, (7, 176419))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk017_aa_verified
