/-
AUTOGENERATED (soundness mode): Chunk [322144..322380]
    Source: chunk_032.json  •  SHA256(JSON): 2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk032_j_verified

noncomputable section

def nLo : Nat := 322144
def nHi : Nat := 322380
def dataSHA256 : String := "2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (322144, (5, 322139)),
    (322146, (7, 322139)),
    (322148, (37, 322111)),
    (322150, (11, 322139)),
    (322152, (13, 322139)),
    (322154, (43, 322111)),
    (322156, (17, 322139)),
    (322158, (19, 322139)),
    (322160, (67, 322093)),
    (322162, (23, 322139)),
    (322164, (53, 322111)),
    (322166, (73, 322093)),
    (322168, (29, 322139)),
    (322170, (31, 322139)),
    (322172, (3, 322169)),
    (322174, (3, 322171)),
    (322176, (5, 322171)),
    (322178, (7, 322171)),
    (322180, (11, 322169)),
    (322182, (11, 322171)),
    (322184, (13, 322171)),
    (322186, (17, 322169)),
    (322188, (17, 322171)),
    (322190, (19, 322171)),
    (322192, (23, 322169)),
    (322194, (23, 322171)),
    (322196, (3, 322193)),
    (322198, (5, 322193)),
    (322200, (7, 322193)),
    (322202, (31, 322171)),
    (322204, (11, 322193)),
    (322206, (13, 322193)),
    (322208, (37, 322171)),
    (322210, (17, 322193)),
    (322212, (19, 322193)),
    (322214, (43, 322171)),
    (322216, (3, 322213)),
    (322218, (5, 322213)),
    (322220, (7, 322213)),
    (322222, (29, 322193)),
    (322224, (11, 322213)),
    (322226, (13, 322213)),
    (322228, (59, 322169)),
    (322230, (17, 322213)),
    (322232, (3, 322229)),
    (322234, (5, 322229)),
    (322236, (7, 322229)),
    (322238, (67, 322171)),
    (322240, (3, 322237)),
    (322242, (5, 322237)),
    (322244, (7, 322237)),
    (322246, (3, 322243)),
    (322248, (5, 322243)),
    (322250, (3, 322247)),
    (322252, (3, 322249)),
    (322254, (5, 322249)),
    (322256, (7, 322249)),
    (322258, (11, 322247)),
    (322260, (11, 322249)),
    (322262, (13, 322249)),
    (322264, (3, 322261)),
    (322266, (5, 322261)),
    (322268, (7, 322261)),
    (322270, (23, 322247)),
    (322272, (11, 322261)),
    (322274, (3, 322271)),
    (322276, (5, 322271)),
    (322278, (7, 322271)),
    (322280, (19, 322261)),
    (322282, (11, 322271)),
    (322284, (13, 322271)),
    (322286, (37, 322249)),
    (322288, (17, 322271)),
    (322290, (19, 322271)),
    (322292, (31, 322261)),
    (322294, (23, 322271)),
    (322296, (47, 322249)),
    (322298, (37, 322261)),
    (322300, (29, 322271)),
    (322302, (31, 322271)),
    (322304, (43, 322261)),
    (322306, (59, 322247)),
    (322308, (37, 322271)),
    (322310, (61, 322249)),
    (322312, (41, 322271)),
    (322314, (43, 322271)),
    (322316, (67, 322249)),
    (322318, (47, 322271)),
    (322320, (59, 322261)),
    (322322, (3, 322319)),
    (322324, (5, 322319)),
    (322326, (7, 322319)),
    (322328, (67, 322261)),
    (322330, (3, 322327)),
    (322332, (5, 322327)),
    (322334, (7, 322327)),
    (322336, (17, 322319)),
    (322338, (11, 322327)),
    (322340, (13, 322327)),
    (322342, (3, 322339)),
    (322344, (5, 322339)),
    (322346, (7, 322339)),
    (322348, (29, 322319)),
    (322350, (11, 322339)),
    (322352, (3, 322349)),
    (322354, (3, 322351)),
    (322356, (5, 322351)),
    (322358, (7, 322351)),
    (322360, (11, 322349)),
    (322362, (11, 322351)),
    (322364, (13, 322351)),
    (322366, (17, 322349)),
    (322368, (17, 322351)),
    (322370, (19, 322351)),
    (322372, (23, 322349)),
    (322374, (23, 322351)),
    (322376, (37, 322339)),
    (322378, (29, 322349)),
    (322380, (29, 322351))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk032_j_verified
