/-
AUTOGENERATED (soundness mode): Chunk [327618..327854]
    Source: chunk_032.json  •  SHA256(JSON): 2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk032_ag_verified

noncomputable section

def nLo : Nat := 327618
def nHi : Nat := 327854
def dataSHA256 : String := "2506ebef14b38b87216df10792242bb8096787541388ca874a20ec591e343f93"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (327618, (19, 327599)),
    (327620, (37, 327583)),
    (327622, (3, 327619)),
    (327624, (5, 327619)),
    (327626, (7, 327619)),
    (327628, (29, 327599)),
    (327630, (11, 327619)),
    (327632, (3, 327629)),
    (327634, (5, 327629)),
    (327636, (7, 327629)),
    (327638, (19, 327619)),
    (327640, (11, 327629)),
    (327642, (13, 327629)),
    (327644, (61, 327583)),
    (327646, (17, 327629)),
    (327648, (19, 327629)),
    (327650, (3, 327647)),
    (327652, (5, 327647)),
    (327654, (7, 327647)),
    (327656, (37, 327619)),
    (327658, (11, 327647)),
    (327660, (13, 327647)),
    (327662, (43, 327619)),
    (327664, (3, 327661)),
    (327666, (5, 327661)),
    (327668, (7, 327661)),
    (327670, (3, 327667)),
    (327672, (5, 327667)),
    (327674, (7, 327667)),
    (327676, (3, 327673)),
    (327678, (5, 327673)),
    (327680, (7, 327673)),
    (327682, (53, 327629)),
    (327684, (11, 327673)),
    (327686, (13, 327673)),
    (327688, (41, 327647)),
    (327690, (17, 327673)),
    (327692, (3, 327689)),
    (327694, (5, 327689)),
    (327696, (7, 327689)),
    (327698, (31, 327667)),
    (327700, (11, 327689)),
    (327702, (13, 327689)),
    (327704, (31, 327673)),
    (327706, (17, 327689)),
    (327708, (19, 327689)),
    (327710, (3, 327707)),
    (327712, (5, 327707)),
    (327714, (7, 327707)),
    (327716, (43, 327673)),
    (327718, (11, 327707)),
    (327720, (13, 327707)),
    (327722, (61, 327661)),
    (327724, (3, 327721)),
    (327726, (5, 327721)),
    (327728, (7, 327721)),
    (327730, (23, 327707)),
    (327732, (11, 327721)),
    (327734, (13, 327721)),
    (327736, (29, 327707)),
    (327738, (17, 327721)),
    (327740, (3, 327737)),
    (327742, (3, 327739)),
    (327744, (5, 327739)),
    (327746, (7, 327739)),
    (327748, (11, 327737)),
    (327750, (11, 327739)),
    (327752, (13, 327739)),
    (327754, (17, 327737)),
    (327756, (17, 327739)),
    (327758, (19, 327739)),
    (327760, (3, 327757)),
    (327762, (5, 327757)),
    (327764, (7, 327757)),
    (327766, (29, 327737)),
    (327768, (11, 327757)),
    (327770, (13, 327757)),
    (327772, (83, 327689)),
    (327774, (17, 327757)),
    (327776, (19, 327757)),
    (327778, (41, 327737)),
    (327780, (23, 327757)),
    (327782, (3, 327779)),
    (327784, (5, 327779)),
    (327786, (7, 327779)),
    (327788, (31, 327757)),
    (327790, (11, 327779)),
    (327792, (13, 327779)),
    (327794, (37, 327757)),
    (327796, (17, 327779)),
    (327798, (19, 327779)),
    (327800, (3, 327797)),
    (327802, (3, 327799)),
    (327804, (5, 327799)),
    (327806, (7, 327799)),
    (327808, (11, 327797)),
    (327810, (11, 327799)),
    (327812, (3, 327809)),
    (327814, (5, 327809)),
    (327816, (7, 327809)),
    (327818, (19, 327799)),
    (327820, (11, 327809)),
    (327822, (13, 327809)),
    (327824, (67, 327757)),
    (327826, (3, 327823)),
    (327828, (5, 327823)),
    (327830, (3, 327827)),
    (327832, (3, 327829)),
    (327834, (5, 327829)),
    (327836, (7, 327829)),
    (327838, (11, 327827)),
    (327840, (11, 327829)),
    (327842, (3, 327839)),
    (327844, (5, 327839)),
    (327846, (7, 327839)),
    (327848, (19, 327829)),
    (327850, (11, 327839)),
    (327852, (13, 327839)),
    (327854, (3, 327851))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk032_ag_verified
