/-
AUTOGENERATED (soundness mode): Chunk [251192..251428]
    Source: chunk_025.json  •  SHA256(JSON): f249f4e2da073cfe1af142d14170278e708dba4699cb7fda427c8d521f17fadf
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk025_f_verified

noncomputable section

def nLo : Nat := 251192
def nHi : Nat := 251428
def dataSHA256 : String := "f249f4e2da073cfe1af142d14170278e708dba4699cb7fda427c8d521f17fadf"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (251192, (13, 251179)),
    (251194, (3, 251191)),
    (251196, (5, 251191)),
    (251198, (7, 251191)),
    (251200, (3, 251197)),
    (251202, (5, 251197)),
    (251204, (3, 251201)),
    (251206, (3, 251203)),
    (251208, (5, 251203)),
    (251210, (7, 251203)),
    (251212, (11, 251201)),
    (251214, (11, 251203)),
    (251216, (13, 251203)),
    (251218, (17, 251201)),
    (251220, (17, 251203)),
    (251222, (3, 251219)),
    (251224, (3, 251221)),
    (251226, (5, 251221)),
    (251228, (7, 251221)),
    (251230, (11, 251219)),
    (251232, (11, 251221)),
    (251234, (3, 251231)),
    (251236, (3, 251233)),
    (251238, (5, 251233)),
    (251240, (7, 251233)),
    (251242, (11, 251231)),
    (251244, (11, 251233)),
    (251246, (13, 251233)),
    (251248, (17, 251231)),
    (251250, (17, 251233)),
    (251252, (19, 251233)),
    (251254, (23, 251231)),
    (251256, (23, 251233)),
    (251258, (37, 251221)),
    (251260, (3, 251257)),
    (251262, (5, 251257)),
    (251264, (3, 251261)),
    (251266, (3, 251263)),
    (251268, (5, 251263)),
    (251270, (7, 251263)),
    (251272, (11, 251261)),
    (251274, (11, 251263)),
    (251276, (13, 251263)),
    (251278, (17, 251261)),
    (251280, (17, 251263)),
    (251282, (19, 251263)),
    (251284, (23, 251261)),
    (251286, (23, 251263)),
    (251288, (31, 251257)),
    (251290, (3, 251287)),
    (251292, (5, 251287)),
    (251294, (3, 251291)),
    (251296, (5, 251291)),
    (251298, (7, 251291)),
    (251300, (3, 251297)),
    (251302, (5, 251297)),
    (251304, (7, 251297)),
    (251306, (19, 251287)),
    (251308, (11, 251297)),
    (251310, (13, 251297)),
    (251312, (79, 251233)),
    (251314, (17, 251297)),
    (251316, (19, 251297)),
    (251318, (31, 251287)),
    (251320, (23, 251297)),
    (251322, (31, 251291)),
    (251324, (37, 251287)),
    (251326, (3, 251323)),
    (251328, (5, 251323)),
    (251330, (7, 251323)),
    (251332, (41, 251291)),
    (251334, (11, 251323)),
    (251336, (13, 251323)),
    (251338, (41, 251297)),
    (251340, (17, 251323)),
    (251342, (19, 251323)),
    (251344, (47, 251297)),
    (251346, (23, 251323)),
    (251348, (61, 251287)),
    (251350, (3, 251347)),
    (251352, (5, 251347)),
    (251354, (7, 251347)),
    (251356, (3, 251353)),
    (251358, (5, 251353)),
    (251360, (7, 251353)),
    (251362, (3, 251359)),
    (251364, (5, 251359)),
    (251366, (7, 251359)),
    (251368, (71, 251297)),
    (251370, (11, 251359)),
    (251372, (13, 251359)),
    (251374, (83, 251291)),
    (251376, (17, 251359)),
    (251378, (19, 251359)),
    (251380, (83, 251297)),
    (251382, (23, 251359)),
    (251384, (31, 251353)),
    (251386, (89, 251297)),
    (251388, (29, 251359)),
    (251390, (3, 251387)),
    (251392, (5, 251387)),
    (251394, (7, 251387)),
    (251396, (3, 251393)),
    (251398, (5, 251393)),
    (251400, (7, 251393)),
    (251402, (43, 251359)),
    (251404, (11, 251393)),
    (251406, (13, 251393)),
    (251408, (61, 251347)),
    (251410, (17, 251393)),
    (251412, (19, 251393)),
    (251414, (61, 251353)),
    (251416, (23, 251393)),
    (251418, (31, 251387)),
    (251420, (3, 251417)),
    (251422, (5, 251417)),
    (251424, (7, 251417)),
    (251426, (67, 251359)),
    (251428, (11, 251417))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk025_f_verified
