/-
AUTOGENERATED (soundness mode): Chunk [525952..526188]
    Source: chunk_052.json  •  SHA256(JSON): 897e6c8f43b6d1a1279d7d437cc2a10c1992198ffe2b2af69242ea5582f3909e
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk052_z_verified

noncomputable section

def nLo : Nat := 525952
def nHi : Nat := 526188
def dataSHA256 : String := "897e6c8f43b6d1a1279d7d437cc2a10c1992198ffe2b2af69242ea5582f3909e"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (525952, (3, 525949)),
    (525954, (5, 525949)),
    (525956, (3, 525953)),
    (525958, (5, 525953)),
    (525960, (7, 525953)),
    (525962, (13, 525949)),
    (525964, (3, 525961)),
    (525966, (5, 525961)),
    (525968, (7, 525961)),
    (525970, (17, 525953)),
    (525972, (11, 525961)),
    (525974, (13, 525961)),
    (525976, (23, 525953)),
    (525978, (17, 525961)),
    (525980, (19, 525961)),
    (525982, (3, 525979)),
    (525984, (5, 525979)),
    (525986, (3, 525983)),
    (525988, (5, 525983)),
    (525990, (7, 525983)),
    (525992, (13, 525979)),
    (525994, (11, 525983)),
    (525996, (13, 525983)),
    (525998, (19, 525979)),
    (526000, (17, 525983)),
    (526002, (19, 525983)),
    (526004, (43, 525961)),
    (526006, (23, 525983)),
    (526008, (29, 525979)),
    (526010, (31, 525979)),
    (526012, (29, 525983)),
    (526014, (31, 525983)),
    (526016, (37, 525979)),
    (526018, (71, 525947)),
    (526020, (37, 525983)),
    (526022, (43, 525979)),
    (526024, (41, 525983)),
    (526026, (43, 525983)),
    (526028, (67, 525961)),
    (526030, (3, 526027)),
    (526032, (5, 526027)),
    (526034, (7, 526027)),
    (526036, (53, 525983)),
    (526038, (11, 526027)),
    (526040, (3, 526037)),
    (526042, (5, 526037)),
    (526044, (7, 526037)),
    (526046, (19, 526027)),
    (526048, (11, 526037)),
    (526050, (13, 526037)),
    (526052, (3, 526049)),
    (526054, (3, 526051)),
    (526056, (5, 526051)),
    (526058, (7, 526051)),
    (526060, (11, 526049)),
    (526062, (11, 526051)),
    (526064, (13, 526051)),
    (526066, (3, 526063)),
    (526068, (5, 526063)),
    (526070, (3, 526067)),
    (526072, (3, 526069)),
    (526074, (5, 526069)),
    (526076, (3, 526073)),
    (526078, (5, 526073)),
    (526080, (7, 526073)),
    (526082, (13, 526069)),
    (526084, (11, 526073)),
    (526086, (13, 526073)),
    (526088, (19, 526069)),
    (526090, (3, 526087)),
    (526092, (5, 526087)),
    (526094, (7, 526087)),
    (526096, (23, 526073)),
    (526098, (11, 526087)),
    (526100, (13, 526087)),
    (526102, (29, 526073)),
    (526104, (17, 526087)),
    (526106, (19, 526087)),
    (526108, (41, 526067)),
    (526110, (23, 526087)),
    (526112, (43, 526069)),
    (526114, (41, 526073)),
    (526116, (29, 526087)),
    (526118, (31, 526087)),
    (526120, (3, 526117)),
    (526122, (5, 526117)),
    (526124, (3, 526121)),
    (526126, (5, 526121)),
    (526128, (7, 526121)),
    (526130, (13, 526117)),
    (526132, (11, 526121)),
    (526134, (13, 526121)),
    (526136, (19, 526117)),
    (526138, (17, 526121)),
    (526140, (19, 526121)),
    (526142, (3, 526139)),
    (526144, (5, 526139)),
    (526146, (7, 526139)),
    (526148, (31, 526117)),
    (526150, (11, 526139)),
    (526152, (13, 526139)),
    (526154, (37, 526117)),
    (526156, (17, 526139)),
    (526158, (19, 526139)),
    (526160, (3, 526157)),
    (526162, (3, 526159)),
    (526164, (5, 526159)),
    (526166, (7, 526159)),
    (526168, (11, 526157)),
    (526170, (11, 526159)),
    (526172, (13, 526159)),
    (526174, (17, 526157)),
    (526176, (17, 526159)),
    (526178, (19, 526159)),
    (526180, (23, 526157)),
    (526182, (23, 526159)),
    (526184, (67, 526117)),
    (526186, (29, 526157)),
    (526188, (29, 526159))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk052_z_verified
