/-
AUTOGENERATED (soundness mode): Chunk [408332..408568]
    Source: chunk_040.json  •  SHA256(JSON): d5e7aa7acc146b45b36e25ba5df01ef74a1648684242950d572e4ce2581f3455
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk040_aj_verified

noncomputable section

def nLo : Nat := 408332
def nHi : Nat := 408568
def dataSHA256 : String := "d5e7aa7acc146b45b36e25ba5df01ef74a1648684242950d572e4ce2581f3455"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (408332, (61, 408271)),
    (408334, (23, 408311)),
    (408336, (53, 408283)),
    (408338, (67, 408271)),
    (408340, (3, 408337)),
    (408342, (5, 408337)),
    (408344, (3, 408341)),
    (408346, (5, 408341)),
    (408348, (7, 408341)),
    (408350, (3, 408347)),
    (408352, (5, 408347)),
    (408354, (7, 408347)),
    (408356, (19, 408337)),
    (408358, (11, 408347)),
    (408360, (13, 408347)),
    (408362, (79, 408283)),
    (408364, (3, 408361)),
    (408366, (5, 408361)),
    (408368, (7, 408361)),
    (408370, (23, 408347)),
    (408372, (11, 408361)),
    (408374, (13, 408361)),
    (408376, (29, 408347)),
    (408378, (17, 408361)),
    (408380, (19, 408361)),
    (408382, (3, 408379)),
    (408384, (5, 408379)),
    (408386, (7, 408379)),
    (408388, (41, 408347)),
    (408390, (11, 408379)),
    (408392, (3, 408389)),
    (408394, (5, 408389)),
    (408396, (7, 408389)),
    (408398, (19, 408379)),
    (408400, (11, 408389)),
    (408402, (13, 408389)),
    (408404, (43, 408361)),
    (408406, (3, 408403)),
    (408408, (5, 408403)),
    (408410, (7, 408403)),
    (408412, (23, 408389)),
    (408414, (11, 408403)),
    (408416, (3, 408413)),
    (408418, (5, 408413)),
    (408420, (7, 408413)),
    (408422, (19, 408403)),
    (408424, (11, 408413)),
    (408426, (13, 408413)),
    (408428, (67, 408361)),
    (408430, (3, 408427)),
    (408432, (5, 408427)),
    (408434, (3, 408431)),
    (408436, (3, 408433)),
    (408438, (5, 408433)),
    (408440, (3, 408437)),
    (408442, (5, 408437)),
    (408444, (7, 408437)),
    (408446, (13, 408433)),
    (408448, (11, 408437)),
    (408450, (13, 408437)),
    (408452, (19, 408433)),
    (408454, (17, 408437)),
    (408456, (19, 408437)),
    (408458, (31, 408427)),
    (408460, (23, 408437)),
    (408462, (29, 408433)),
    (408464, (3, 408461)),
    (408466, (5, 408461)),
    (408468, (7, 408461)),
    (408470, (37, 408433)),
    (408472, (3, 408469)),
    (408474, (5, 408469)),
    (408476, (7, 408469)),
    (408478, (17, 408461)),
    (408480, (11, 408469)),
    (408482, (3, 408479)),
    (408484, (5, 408479)),
    (408486, (7, 408479)),
    (408488, (19, 408469)),
    (408490, (11, 408479)),
    (408492, (13, 408479)),
    (408494, (3, 408491)),
    (408496, (5, 408491)),
    (408498, (7, 408491)),
    (408500, (3, 408497)),
    (408502, (5, 408497)),
    (408504, (7, 408497)),
    (408506, (37, 408469)),
    (408508, (11, 408497)),
    (408510, (13, 408497)),
    (408512, (43, 408469)),
    (408514, (17, 408497)),
    (408516, (19, 408497)),
    (408518, (139, 408379)),
    (408520, (23, 408497)),
    (408522, (31, 408491)),
    (408524, (97, 408427)),
    (408526, (29, 408497)),
    (408528, (31, 408497)),
    (408530, (61, 408469)),
    (408532, (41, 408491)),
    (408534, (37, 408497)),
    (408536, (3, 408533)),
    (408538, (5, 408533)),
    (408540, (7, 408533)),
    (408542, (3, 408539)),
    (408544, (5, 408539)),
    (408546, (7, 408539)),
    (408548, (79, 408469)),
    (408550, (11, 408539)),
    (408552, (13, 408539)),
    (408554, (127, 408427)),
    (408556, (3, 408553)),
    (408558, (5, 408553)),
    (408560, (7, 408553)),
    (408562, (23, 408539)),
    (408564, (11, 408553)),
    (408566, (3, 408563)),
    (408568, (5, 408563))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk040_aj_verified
