/-
AUTOGENERATED (soundness mode): Chunk [587142..587378]
    Source: chunk_058.json  •  SHA256(JSON): 909df3fccd4e1574a38d9bbcae1ca46c11dc45fdb55a5ee286c2bcfd1ff30a78
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk058_ae_verified

noncomputable section

def nLo : Nat := 587142
def nHi : Nat := 587378
def dataSHA256 : String := "909df3fccd4e1574a38d9bbcae1ca46c11dc45fdb55a5ee286c2bcfd1ff30a78"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (587142, (5, 587137)),
    (587144, (7, 587137)),
    (587146, (3, 587143)),
    (587148, (5, 587143)),
    (587150, (7, 587143)),
    (587152, (3, 587149)),
    (587154, (5, 587149)),
    (587156, (7, 587149)),
    (587158, (41, 587117)),
    (587160, (11, 587149)),
    (587162, (13, 587149)),
    (587164, (41, 587123)),
    (587166, (17, 587149)),
    (587168, (19, 587149)),
    (587170, (47, 587123)),
    (587172, (23, 587149)),
    (587174, (31, 587143)),
    (587176, (3, 587173)),
    (587178, (5, 587173)),
    (587180, (7, 587173)),
    (587182, (3, 587179)),
    (587184, (5, 587179)),
    (587186, (7, 587179)),
    (587188, (71, 587117)),
    (587190, (11, 587179)),
    (587192, (3, 587189)),
    (587194, (5, 587189)),
    (587196, (7, 587189)),
    (587198, (19, 587179)),
    (587200, (11, 587189)),
    (587202, (13, 587189)),
    (587204, (3, 587201)),
    (587206, (5, 587201)),
    (587208, (7, 587201)),
    (587210, (31, 587179)),
    (587212, (11, 587201)),
    (587214, (13, 587201)),
    (587216, (37, 587179)),
    (587218, (17, 587201)),
    (587220, (19, 587201)),
    (587222, (3, 587219)),
    (587224, (5, 587219)),
    (587226, (7, 587219)),
    (587228, (79, 587149)),
    (587230, (11, 587219)),
    (587232, (13, 587219)),
    (587234, (61, 587173)),
    (587236, (17, 587219)),
    (587238, (19, 587219)),
    (587240, (61, 587179)),
    (587242, (23, 587219)),
    (587244, (43, 587201)),
    (587246, (67, 587179)),
    (587248, (29, 587219)),
    (587250, (31, 587219)),
    (587252, (73, 587179)),
    (587254, (53, 587201)),
    (587256, (37, 587219)),
    (587258, (79, 587179)),
    (587260, (41, 587219)),
    (587262, (43, 587219)),
    (587264, (127, 587137)),
    (587266, (3, 587263)),
    (587268, (5, 587263)),
    (587270, (3, 587267)),
    (587272, (3, 587269)),
    (587274, (5, 587269)),
    (587276, (7, 587269)),
    (587278, (11, 587267)),
    (587280, (11, 587269)),
    (587282, (13, 587269)),
    (587284, (3, 587281)),
    (587286, (5, 587281)),
    (587288, (7, 587281)),
    (587290, (3, 587287)),
    (587292, (5, 587287)),
    (587294, (7, 587287)),
    (587296, (29, 587267)),
    (587298, (11, 587287)),
    (587300, (3, 587297)),
    (587302, (5, 587297)),
    (587304, (7, 587297)),
    (587306, (3, 587303)),
    (587308, (5, 587303)),
    (587310, (7, 587303)),
    (587312, (31, 587281)),
    (587314, (11, 587303)),
    (587316, (13, 587303)),
    (587318, (31, 587287)),
    (587320, (17, 587303)),
    (587322, (19, 587303)),
    (587324, (37, 587287)),
    (587326, (23, 587303)),
    (587328, (31, 587297)),
    (587330, (43, 587287)),
    (587332, (29, 587303)),
    (587334, (31, 587303)),
    (587336, (67, 587269)),
    (587338, (41, 587297)),
    (587340, (37, 587303)),
    (587342, (61, 587281)),
    (587344, (3, 587341)),
    (587346, (5, 587341)),
    (587348, (7, 587341)),
    (587350, (47, 587303)),
    (587352, (11, 587341)),
    (587354, (13, 587341)),
    (587356, (53, 587303)),
    (587358, (17, 587341)),
    (587360, (19, 587341)),
    (587362, (59, 587303)),
    (587364, (23, 587341)),
    (587366, (79, 587287)),
    (587368, (71, 587297)),
    (587370, (29, 587341)),
    (587372, (31, 587341)),
    (587374, (3, 587371)),
    (587376, (5, 587371)),
    (587378, (7, 587371))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk058_ae_verified
