/-
AUTOGENERATED (soundness mode): Chunk [759760..760000]
    Source: chunk_075.json  •  SHA256(JSON): 39f93fcbfda2ea46f88cb4114ef5ea03e794628142b6413e184f645562e488b7
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk075_ap_verified

noncomputable section

def nLo : Nat := 759760
def nHi : Nat := 760000
def dataSHA256 : String := "39f93fcbfda2ea46f88cb4114ef5ea03e794628142b6413e184f645562e488b7"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (759760, (3, 759757)),
    (759762, (5, 759757)),
    (759764, (7, 759757)),
    (759766, (3, 759763)),
    (759768, (5, 759763)),
    (759770, (7, 759763)),
    (759772, (53, 759719)),
    (759774, (11, 759763)),
    (759776, (13, 759763)),
    (759778, (59, 759719)),
    (759780, (17, 759763)),
    (759782, (19, 759763)),
    (759784, (83, 759701)),
    (759786, (23, 759763)),
    (759788, (31, 759757)),
    (759790, (71, 759719)),
    (759792, (29, 759763)),
    (759794, (31, 759763)),
    (759796, (137, 759659)),
    (759798, (41, 759757)),
    (759800, (3, 759797)),
    (759802, (3, 759799)),
    (759804, (5, 759799)),
    (759806, (7, 759799)),
    (759808, (11, 759797)),
    (759810, (11, 759799)),
    (759812, (13, 759799)),
    (759814, (17, 759797)),
    (759816, (17, 759799)),
    (759818, (19, 759799)),
    (759820, (23, 759797)),
    (759822, (23, 759799)),
    (759824, (3, 759821)),
    (759826, (5, 759821)),
    (759828, (7, 759821)),
    (759830, (31, 759799)),
    (759832, (11, 759821)),
    (759834, (13, 759821)),
    (759836, (3, 759833)),
    (759838, (5, 759833)),
    (759840, (7, 759833)),
    (759842, (43, 759799)),
    (759844, (11, 759833)),
    (759846, (13, 759833)),
    (759848, (109, 759739)),
    (759850, (17, 759833)),
    (759852, (19, 759833)),
    (759854, (97, 759757)),
    (759856, (23, 759833)),
    (759858, (37, 759821)),
    (759860, (61, 759799)),
    (759862, (29, 759833)),
    (759864, (31, 759833)),
    (759866, (67, 759799)),
    (759868, (47, 759821)),
    (759870, (37, 759833)),
    (759872, (73, 759799)),
    (759874, (41, 759833)),
    (759876, (43, 759833)),
    (759878, (79, 759799)),
    (759880, (47, 759833)),
    (759882, (61, 759821)),
    (759884, (3, 759881)),
    (759886, (5, 759881)),
    (759888, (7, 759881)),
    (759890, (127, 759763)),
    (759892, (11, 759881)),
    (759894, (13, 759881)),
    (759896, (3, 759893)),
    (759898, (5, 759893)),
    (759900, (7, 759893)),
    (759902, (103, 759799)),
    (759904, (11, 759893)),
    (759906, (13, 759893)),
    (759908, (109, 759799)),
    (759910, (17, 759893)),
    (759912, (19, 759893)),
    (759914, (3, 759911)),
    (759916, (5, 759911)),
    (759918, (7, 759911)),
    (759920, (157, 759763)),
    (759922, (11, 759911)),
    (759924, (13, 759911)),
    (759926, (3, 759923)),
    (759928, (5, 759923)),
    (759930, (7, 759923)),
    (759932, (3, 759929)),
    (759934, (5, 759929)),
    (759936, (7, 759929)),
    (759938, (139, 759799)),
    (759940, (11, 759929)),
    (759942, (13, 759929)),
    (759944, (181, 759763)),
    (759946, (17, 759929)),
    (759948, (19, 759929)),
    (759950, (3, 759947)),
    (759952, (5, 759947)),
    (759954, (7, 759947)),
    (759956, (3, 759953)),
    (759958, (5, 759953)),
    (759960, (7, 759953)),
    (759962, (3, 759959)),
    (759964, (3, 759961)),
    (759966, (5, 759961)),
    (759968, (7, 759961)),
    (759970, (11, 759959)),
    (759972, (11, 759961)),
    (759974, (13, 759961)),
    (759976, (3, 759973)),
    (759978, (5, 759973)),
    (759980, (7, 759973)),
    (759982, (23, 759959)),
    (759984, (11, 759973)),
    (759986, (13, 759973)),
    (759988, (29, 759959)),
    (759990, (17, 759973)),
    (759992, (19, 759973)),
    (759994, (41, 759953)),
    (759996, (23, 759973)),
    (759998, (37, 759961)),
    (760000, (41, 759959))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk075_ap_verified
