/-
AUTOGENERATED (soundness mode): Chunk [744286..744522]
    Source: chunk_074.json  •  SHA256(JSON): 9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk074_s_verified

noncomputable section

def nLo : Nat := 744286
def nHi : Nat := 744522
def dataSHA256 : String := "9d52180bad81731e9c7e8e529f542c41b3ebf85247571cff53dfa4792c6693b1"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (744286, (3, 744283)),
    (744288, (5, 744283)),
    (744290, (7, 744283)),
    (744292, (41, 744251)),
    (744294, (11, 744283)),
    (744296, (13, 744283)),
    (744298, (47, 744251)),
    (744300, (17, 744283)),
    (744302, (19, 744283)),
    (744304, (3, 744301)),
    (744306, (5, 744301)),
    (744308, (7, 744301)),
    (744310, (59, 744251)),
    (744312, (11, 744301)),
    (744314, (13, 744301)),
    (744316, (3, 744313)),
    (744318, (5, 744313)),
    (744320, (7, 744313)),
    (744322, (71, 744251)),
    (744324, (11, 744313)),
    (744326, (13, 744313)),
    (744328, (89, 744239)),
    (744330, (17, 744313)),
    (744332, (19, 744313)),
    (744334, (83, 744251)),
    (744336, (23, 744313)),
    (744338, (37, 744301)),
    (744340, (89, 744251)),
    (744342, (29, 744313)),
    (744344, (31, 744313)),
    (744346, (107, 744239)),
    (744348, (47, 744301)),
    (744350, (37, 744313)),
    (744352, (101, 744251)),
    (744354, (41, 744313)),
    (744356, (3, 744353)),
    (744358, (5, 744353)),
    (744360, (7, 744353)),
    (744362, (61, 744301)),
    (744364, (11, 744353)),
    (744366, (13, 744353)),
    (744368, (67, 744301)),
    (744370, (17, 744353)),
    (744372, (19, 744353)),
    (744374, (3, 744371)),
    (744376, (5, 744371)),
    (744378, (7, 744371)),
    (744380, (3, 744377)),
    (744382, (5, 744377)),
    (744384, (7, 744377)),
    (744386, (73, 744313)),
    (744388, (11, 744377)),
    (744390, (13, 744377)),
    (744392, (3, 744389)),
    (744394, (3, 744391)),
    (744396, (5, 744391)),
    (744398, (7, 744391)),
    (744400, (3, 744397)),
    (744402, (5, 744397)),
    (744404, (7, 744397)),
    (744406, (17, 744389)),
    (744408, (11, 744397)),
    (744410, (3, 744407)),
    (744412, (3, 744409)),
    (744414, (5, 744409)),
    (744416, (7, 744409)),
    (744418, (11, 744407)),
    (744420, (11, 744409)),
    (744422, (13, 744409)),
    (744424, (17, 744407)),
    (744426, (17, 744409)),
    (744428, (19, 744409)),
    (744430, (23, 744407)),
    (744432, (23, 744409)),
    (744434, (3, 744431)),
    (744436, (5, 744431)),
    (744438, (7, 744431)),
    (744440, (31, 744409)),
    (744442, (11, 744431)),
    (744444, (13, 744431)),
    (744446, (37, 744409)),
    (744448, (17, 744431)),
    (744450, (19, 744431)),
    (744452, (43, 744409)),
    (744454, (3, 744451)),
    (744456, (5, 744451)),
    (744458, (7, 744451)),
    (744460, (29, 744431)),
    (744462, (11, 744451)),
    (744464, (13, 744451)),
    (744466, (59, 744407)),
    (744468, (17, 744451)),
    (744470, (19, 744451)),
    (744472, (41, 744431)),
    (744474, (23, 744451)),
    (744476, (67, 744409)),
    (744478, (47, 744431)),
    (744480, (29, 744451)),
    (744482, (31, 744451)),
    (744484, (53, 744431)),
    (744486, (79, 744407)),
    (744488, (37, 744451)),
    (744490, (59, 744431)),
    (744492, (41, 744451)),
    (744494, (43, 744451)),
    (744496, (3, 744493)),
    (744498, (5, 744493)),
    (744500, (7, 744493)),
    (744502, (71, 744431)),
    (744504, (11, 744493)),
    (744506, (3, 744503)),
    (744508, (5, 744503)),
    (744510, (7, 744503)),
    (744512, (19, 744493)),
    (744514, (3, 744511)),
    (744516, (5, 744511)),
    (744518, (7, 744511)),
    (744520, (17, 744503)),
    (744522, (11, 744511))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk074_s_verified
