/-
AUTOGENERATED (soundness mode): Chunk [505000..505236]
    Source: chunk_050.json  •  SHA256(JSON): c4191e3fb81caa03fefe50540bfc1c812ee90eed650d52dbc4437ec8c4a7ff99
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk050_v_verified

noncomputable section

def nLo : Nat := 505000
def nHi : Nat := 505236
def dataSHA256 : String := "c4191e3fb81caa03fefe50540bfc1c812ee90eed650d52dbc4437ec8c4a7ff99"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (505000, (11, 504989)),
    (505002, (11, 504991)),
    (505004, (13, 504991)),
    (505006, (17, 504989)),
    (505008, (17, 504991)),
    (505010, (19, 504991)),
    (505012, (23, 504989)),
    (505014, (23, 504991)),
    (505016, (73, 504943)),
    (505018, (29, 504989)),
    (505020, (29, 504991)),
    (505022, (31, 504991)),
    (505024, (41, 504983)),
    (505026, (37, 504989)),
    (505028, (37, 504991)),
    (505030, (3, 505027)),
    (505032, (5, 505027)),
    (505034, (3, 505031)),
    (505036, (3, 505033)),
    (505038, (5, 505033)),
    (505040, (7, 505033)),
    (505042, (11, 505031)),
    (505044, (11, 505033)),
    (505046, (13, 505033)),
    (505048, (17, 505031)),
    (505050, (17, 505033)),
    (505052, (3, 505049)),
    (505054, (3, 505051)),
    (505056, (5, 505051)),
    (505058, (7, 505051)),
    (505060, (11, 505049)),
    (505062, (11, 505051)),
    (505064, (3, 505061)),
    (505066, (5, 505061)),
    (505068, (7, 505061)),
    (505070, (3, 505067)),
    (505072, (5, 505067)),
    (505074, (7, 505067)),
    (505076, (3, 505073)),
    (505078, (5, 505073)),
    (505080, (7, 505073)),
    (505082, (31, 505051)),
    (505084, (11, 505073)),
    (505086, (13, 505073)),
    (505088, (37, 505051)),
    (505090, (17, 505073)),
    (505092, (19, 505073)),
    (505094, (3, 505091)),
    (505096, (5, 505091)),
    (505098, (7, 505091)),
    (505100, (3, 505097)),
    (505102, (5, 505097)),
    (505104, (7, 505097)),
    (505106, (73, 505033)),
    (505108, (11, 505097)),
    (505110, (13, 505097)),
    (505112, (61, 505051)),
    (505114, (3, 505111)),
    (505116, (5, 505111)),
    (505118, (7, 505111)),
    (505120, (3, 505117)),
    (505122, (5, 505117)),
    (505124, (7, 505117)),
    (505126, (3, 505123)),
    (505128, (5, 505123)),
    (505130, (7, 505123)),
    (505132, (3, 505129)),
    (505134, (5, 505129)),
    (505136, (7, 505129)),
    (505138, (41, 505097)),
    (505140, (11, 505129)),
    (505142, (3, 505139)),
    (505144, (5, 505139)),
    (505146, (7, 505139)),
    (505148, (19, 505129)),
    (505150, (11, 505139)),
    (505152, (13, 505139)),
    (505154, (31, 505123)),
    (505156, (17, 505139)),
    (505158, (19, 505139)),
    (505160, (3, 505157)),
    (505162, (3, 505159)),
    (505164, (5, 505159)),
    (505166, (7, 505159)),
    (505168, (11, 505157)),
    (505170, (11, 505159)),
    (505172, (13, 505159)),
    (505174, (17, 505157)),
    (505176, (17, 505159)),
    (505178, (19, 505159)),
    (505180, (23, 505157)),
    (505182, (23, 505159)),
    (505184, (3, 505181)),
    (505186, (5, 505181)),
    (505188, (7, 505181)),
    (505190, (3, 505187)),
    (505192, (5, 505187)),
    (505194, (7, 505187)),
    (505196, (37, 505159)),
    (505198, (11, 505187)),
    (505200, (13, 505187)),
    (505202, (43, 505159)),
    (505204, (3, 505201)),
    (505206, (5, 505201)),
    (505208, (7, 505201)),
    (505210, (23, 505187)),
    (505212, (11, 505201)),
    (505214, (13, 505201)),
    (505216, (3, 505213)),
    (505218, (5, 505213)),
    (505220, (7, 505213)),
    (505222, (41, 505181)),
    (505224, (11, 505213)),
    (505226, (13, 505213)),
    (505228, (41, 505187)),
    (505230, (17, 505213)),
    (505232, (19, 505213)),
    (505234, (3, 505231)),
    (505236, (5, 505231))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk050_v_verified
