/-
AUTOGENERATED (soundness mode): Chunk [790240..790476]
    Source: chunk_079.json  •  SHA256(JSON): ef715a2c7549b3c98e67a2f612a9ad1708c6df8ac5312cf550c575895e710573
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk079_b_verified

noncomputable section

def nLo : Nat := 790240
def nHi : Nat := 790476
def dataSHA256 : String := "ef715a2c7549b3c98e67a2f612a9ad1708c6df8ac5312cf550c575895e710573"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (790240, (41, 790199)),
    (790242, (23, 790219)),
    (790244, (3, 790241)),
    (790246, (5, 790241)),
    (790248, (7, 790241)),
    (790250, (31, 790219)),
    (790252, (11, 790241)),
    (790254, (13, 790241)),
    (790256, (37, 790219)),
    (790258, (17, 790241)),
    (790260, (19, 790241)),
    (790262, (43, 790219)),
    (790264, (3, 790261)),
    (790266, (5, 790261)),
    (790268, (7, 790261)),
    (790270, (29, 790241)),
    (790272, (11, 790261)),
    (790274, (3, 790271)),
    (790276, (5, 790271)),
    (790278, (7, 790271)),
    (790280, (3, 790277)),
    (790282, (5, 790277)),
    (790284, (7, 790277)),
    (790286, (67, 790219)),
    (790288, (11, 790277)),
    (790290, (13, 790277)),
    (790292, (3, 790289)),
    (790294, (3, 790291)),
    (790296, (5, 790291)),
    (790298, (7, 790291)),
    (790300, (11, 790289)),
    (790302, (11, 790291)),
    (790304, (13, 790291)),
    (790306, (17, 790289)),
    (790308, (17, 790291)),
    (790310, (19, 790291)),
    (790312, (23, 790289)),
    (790314, (23, 790291)),
    (790316, (97, 790219)),
    (790318, (29, 790289)),
    (790320, (29, 790291)),
    (790322, (31, 790291)),
    (790324, (47, 790277)),
    (790326, (37, 790289)),
    (790328, (37, 790291)),
    (790330, (3, 790327)),
    (790332, (5, 790327)),
    (790334, (3, 790331)),
    (790336, (3, 790333)),
    (790338, (5, 790333)),
    (790340, (7, 790333)),
    (790342, (11, 790331)),
    (790344, (11, 790333)),
    (790346, (13, 790333)),
    (790348, (17, 790331)),
    (790350, (17, 790333)),
    (790352, (19, 790333)),
    (790354, (3, 790351)),
    (790356, (5, 790351)),
    (790358, (7, 790351)),
    (790360, (29, 790331)),
    (790362, (11, 790351)),
    (790364, (13, 790351)),
    (790366, (89, 790277)),
    (790368, (17, 790351)),
    (790370, (19, 790351)),
    (790372, (3, 790369)),
    (790374, (5, 790369)),
    (790376, (7, 790369)),
    (790378, (47, 790331)),
    (790380, (11, 790369)),
    (790382, (3, 790379)),
    (790384, (5, 790379)),
    (790386, (7, 790379)),
    (790388, (19, 790369)),
    (790390, (11, 790379)),
    (790392, (13, 790379)),
    (790394, (43, 790351)),
    (790396, (17, 790379)),
    (790398, (19, 790379)),
    (790400, (3, 790397)),
    (790402, (5, 790397)),
    (790404, (7, 790397)),
    (790406, (3, 790403)),
    (790408, (5, 790403)),
    (790410, (7, 790403)),
    (790412, (43, 790369)),
    (790414, (11, 790403)),
    (790416, (13, 790403)),
    (790418, (67, 790351)),
    (790420, (3, 790417)),
    (790422, (5, 790417)),
    (790424, (3, 790421)),
    (790426, (5, 790421)),
    (790428, (7, 790421)),
    (790430, (13, 790417)),
    (790432, (3, 790429)),
    (790434, (5, 790429)),
    (790436, (7, 790429)),
    (790438, (17, 790421)),
    (790440, (11, 790429)),
    (790442, (13, 790429)),
    (790444, (23, 790421)),
    (790446, (17, 790429)),
    (790448, (19, 790429)),
    (790450, (29, 790421)),
    (790452, (23, 790429)),
    (790454, (3, 790451)),
    (790456, (5, 790451)),
    (790458, (7, 790451)),
    (790460, (31, 790429)),
    (790462, (3, 790459)),
    (790464, (5, 790459)),
    (790466, (7, 790459)),
    (790468, (17, 790451)),
    (790470, (11, 790459)),
    (790472, (13, 790459)),
    (790474, (23, 790451)),
    (790476, (17, 790459))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk079_b_verified
