/-
AUTOGENERATED (soundness mode): Chunk [883810..884046]
    Source: chunk_088.json  •  SHA256(JSON): c0e81f80b11fab33558f5429ff101468877a9f4ace81b4ec11e3d19a7d3f3285
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk088_q_verified

noncomputable section

def nLo : Nat := 883810
def nHi : Nat := 884046
def dataSHA256 : String := "c0e81f80b11fab33558f5429ff101468877a9f4ace81b4ec11e3d19a7d3f3285"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (883810, (3, 883807)),
    (883812, (5, 883807)),
    (883814, (7, 883807)),
    (883816, (53, 883763)),
    (883818, (11, 883807)),
    (883820, (13, 883807)),
    (883822, (41, 883781)),
    (883824, (17, 883807)),
    (883826, (19, 883807)),
    (883828, (47, 883781)),
    (883830, (23, 883807)),
    (883832, (193, 883639)),
    (883834, (53, 883781)),
    (883836, (29, 883807)),
    (883838, (31, 883807)),
    (883840, (59, 883781)),
    (883842, (59, 883783)),
    (883844, (37, 883807)),
    (883846, (83, 883763)),
    (883848, (41, 883807)),
    (883850, (43, 883807)),
    (883852, (71, 883781)),
    (883854, (47, 883807)),
    (883856, (73, 883783)),
    (883858, (137, 883721)),
    (883860, (53, 883807)),
    (883862, (79, 883783)),
    (883864, (83, 883781)),
    (883866, (59, 883807)),
    (883868, (61, 883807)),
    (883870, (89, 883781)),
    (883872, (89, 883783)),
    (883874, (3, 883871)),
    (883876, (5, 883871)),
    (883878, (7, 883871)),
    (883880, (3, 883877)),
    (883882, (5, 883877)),
    (883884, (7, 883877)),
    (883886, (79, 883807)),
    (883888, (11, 883877)),
    (883890, (13, 883877)),
    (883892, (3, 883889)),
    (883894, (5, 883889)),
    (883896, (7, 883889)),
    (883898, (199, 883699)),
    (883900, (11, 883889)),
    (883902, (13, 883889)),
    (883904, (97, 883807)),
    (883906, (17, 883889)),
    (883908, (19, 883889)),
    (883910, (103, 883807)),
    (883912, (23, 883889)),
    (883914, (37, 883877)),
    (883916, (109, 883807)),
    (883918, (29, 883889)),
    (883920, (31, 883889)),
    (883922, (139, 883783)),
    (883924, (3, 883921)),
    (883926, (5, 883921)),
    (883928, (7, 883921)),
    (883930, (41, 883889)),
    (883932, (11, 883921)),
    (883934, (13, 883921)),
    (883936, (3, 883933)),
    (883938, (5, 883933)),
    (883940, (7, 883933)),
    (883942, (53, 883889)),
    (883944, (11, 883933)),
    (883946, (13, 883933)),
    (883948, (59, 883889)),
    (883950, (17, 883933)),
    (883952, (19, 883933)),
    (883954, (83, 883871)),
    (883956, (23, 883933)),
    (883958, (37, 883921)),
    (883960, (71, 883889)),
    (883962, (29, 883933)),
    (883964, (31, 883933)),
    (883966, (3, 883963)),
    (883968, (5, 883963)),
    (883970, (7, 883963)),
    (883972, (3, 883969)),
    (883974, (5, 883969)),
    (883976, (3, 883973)),
    (883978, (5, 883973)),
    (883980, (7, 883973)),
    (883982, (3, 883979)),
    (883984, (5, 883979)),
    (883986, (7, 883979)),
    (883988, (19, 883969)),
    (883990, (11, 883979)),
    (883992, (13, 883979)),
    (883994, (3, 883991)),
    (883996, (5, 883991)),
    (883998, (7, 883991)),
    (884000, (31, 883969)),
    (884002, (11, 883991)),
    (884004, (13, 883991)),
    (884006, (3, 884003)),
    (884008, (5, 884003)),
    (884010, (7, 884003)),
    (884012, (43, 883969)),
    (884014, (3, 884011)),
    (884016, (5, 884011)),
    (884018, (7, 884011)),
    (884020, (17, 884003)),
    (884022, (11, 884011)),
    (884024, (13, 884011)),
    (884026, (23, 884003)),
    (884028, (17, 884011)),
    (884030, (19, 884011)),
    (884032, (3, 884029)),
    (884034, (5, 884029)),
    (884036, (7, 884029)),
    (884038, (47, 883991)),
    (884040, (11, 884029)),
    (884042, (13, 884029)),
    (884044, (41, 884003)),
    (884046, (17, 884029))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk088_q_verified
