/-
AUTOGENERATED (soundness mode): Chunk [474762..474998]
    Source: chunk_047.json  •  SHA256(JSON): 21e571aeac2088627b076ee11462fc27db5537d5a82e82d810a7b611acfa9616
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics true

namespace Goldbach.FiniteBase.Chunks.Chunk047_u_verified

noncomputable section

def nLo : Nat := 474762
def nHi : Nat := 474998
def dataSHA256 : String := "21e571aeac2088627b076ee11462fc27db5537d5a82e82d810a7b611acfa9616"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (474762, (5, 474757)),
    (474764, (7, 474757)),
    (474766, (29, 474737)),
    (474768, (11, 474757)),
    (474770, (13, 474757)),
    (474772, (3, 474769)),
    (474774, (5, 474769)),
    (474776, (7, 474769)),
    (474778, (41, 474737)),
    (474780, (11, 474769)),
    (474782, (3, 474779)),
    (474784, (5, 474779)),
    (474786, (7, 474779)),
    (474788, (19, 474769)),
    (474790, (3, 474787)),
    (474792, (5, 474787)),
    (474794, (7, 474787)),
    (474796, (17, 474779)),
    (474798, (11, 474787)),
    (474800, (13, 474787)),
    (474802, (23, 474779)),
    (474804, (17, 474787)),
    (474806, (19, 474787)),
    (474808, (29, 474779)),
    (474810, (23, 474787)),
    (474812, (3, 474809)),
    (474814, (3, 474811)),
    (474816, (5, 474811)),
    (474818, (7, 474811)),
    (474820, (11, 474809)),
    (474822, (11, 474811)),
    (474824, (13, 474811)),
    (474826, (17, 474809)),
    (474828, (17, 474811)),
    (474830, (19, 474811)),
    (474832, (23, 474809)),
    (474834, (23, 474811)),
    (474836, (67, 474769)),
    (474838, (29, 474809)),
    (474840, (29, 474811)),
    (474842, (3, 474839)),
    (474844, (5, 474839)),
    (474846, (7, 474839)),
    (474848, (37, 474811)),
    (474850, (3, 474847)),
    (474852, (5, 474847)),
    (474854, (7, 474847)),
    (474856, (17, 474839)),
    (474858, (11, 474847)),
    (474860, (3, 474857)),
    (474862, (5, 474857)),
    (474864, (7, 474857)),
    (474866, (19, 474847)),
    (474868, (11, 474857)),
    (474870, (13, 474857)),
    (474872, (61, 474811)),
    (474874, (17, 474857)),
    (474876, (19, 474857)),
    (474878, (31, 474847)),
    (474880, (23, 474857)),
    (474882, (43, 474839)),
    (474884, (37, 474847)),
    (474886, (29, 474857)),
    (474888, (31, 474857)),
    (474890, (43, 474847)),
    (474892, (53, 474839)),
    (474894, (37, 474857)),
    (474896, (109, 474787)),
    (474898, (41, 474857)),
    (474900, (43, 474857)),
    (474902, (3, 474899)),
    (474904, (5, 474899)),
    (474906, (7, 474899)),
    (474908, (61, 474847)),
    (474910, (3, 474907)),
    (474912, (5, 474907)),
    (474914, (3, 474911)),
    (474916, (5, 474911)),
    (474918, (7, 474911)),
    (474920, (3, 474917)),
    (474922, (5, 474917)),
    (474924, (7, 474917)),
    (474926, (3, 474923)),
    (474928, (5, 474923)),
    (474930, (7, 474923)),
    (474932, (163, 474769)),
    (474934, (3, 474931)),
    (474936, (5, 474931)),
    (474938, (7, 474931)),
    (474940, (3, 474937)),
    (474942, (5, 474937)),
    (474944, (3, 474941)),
    (474946, (5, 474941)),
    (474948, (7, 474941)),
    (474950, (13, 474937)),
    (474952, (3, 474949)),
    (474954, (5, 474949)),
    (474956, (7, 474949)),
    (474958, (17, 474941)),
    (474960, (11, 474949)),
    (474962, (3, 474959)),
    (474964, (5, 474959)),
    (474966, (7, 474959)),
    (474968, (19, 474949)),
    (474970, (11, 474959)),
    (474972, (13, 474959)),
    (474974, (37, 474937)),
    (474976, (17, 474959)),
    (474978, (19, 474959)),
    (474980, (3, 474977)),
    (474982, (5, 474977)),
    (474984, (7, 474977)),
    (474986, (3, 474983)),
    (474988, (5, 474983)),
    (474990, (7, 474983)),
    (474992, (43, 474949)),
    (474994, (11, 474983)),
    (474996, (13, 474983)),
    (474998, (61, 474937))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk047_u_verified
