/-
AUTOGENERATED (soundness mode): Chunk [469284..469520]
    Source: chunk_046.json  •  SHA256(JSON): 0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc
-/
import Goldbach.FiniteBase.FiniteBaseChunkKit
import Goldbach.FiniteBase.Completeness.CompletenessKit
open Goldbach.Base
open Goldbach.FiniteBase.Completeness

set_option maxRecDepth 8000
set_option diagnostics false

namespace Goldbach.FiniteBase.Chunks.Chunk046_an_verified

noncomputable section

def nLo : Nat := 469284
def nHi : Nat := 469520
def dataSHA256 : String := "0efed2dc2525afbf62bf70f010f413b8af2e526b1392583074f0dcefec3050dc"

-- Table of (n,p,q) witnesses for this sub-window.
def table : Array (Nat × Nat × Nat) :=
  #[
    (469284, (5, 469279)),
    (469286, (3, 469283)),
    (469288, (5, 469283)),
    (469290, (7, 469283)),
    (469292, (13, 469279)),
    (469294, (11, 469283)),
    (469296, (13, 469283)),
    (469298, (19, 469279)),
    (469300, (17, 469283)),
    (469302, (19, 469283)),
    (469304, (37, 469267)),
    (469306, (3, 469303)),
    (469308, (5, 469303)),
    (469310, (7, 469303)),
    (469312, (29, 469283)),
    (469314, (11, 469303)),
    (469316, (13, 469303)),
    (469318, (89, 469229)),
    (469320, (17, 469303)),
    (469322, (19, 469303)),
    (469324, (3, 469321)),
    (469326, (5, 469321)),
    (469328, (7, 469321)),
    (469330, (47, 469283)),
    (469332, (11, 469321)),
    (469334, (3, 469331)),
    (469336, (5, 469331)),
    (469338, (7, 469331)),
    (469340, (19, 469321)),
    (469342, (11, 469331)),
    (469344, (13, 469331)),
    (469346, (43, 469303)),
    (469348, (17, 469331)),
    (469350, (19, 469331)),
    (469352, (31, 469321)),
    (469354, (3, 469351)),
    (469356, (5, 469351)),
    (469358, (7, 469351)),
    (469360, (29, 469331)),
    (469362, (11, 469351)),
    (469364, (13, 469351)),
    (469366, (3, 469363)),
    (469368, (5, 469363)),
    (469370, (3, 469367)),
    (469372, (3, 469369)),
    (469374, (5, 469369)),
    (469376, (7, 469369)),
    (469378, (11, 469367)),
    (469380, (11, 469369)),
    (469382, (3, 469379)),
    (469384, (5, 469379)),
    (469386, (7, 469379)),
    (469388, (19, 469369)),
    (469390, (11, 469379)),
    (469392, (13, 469379)),
    (469394, (31, 469363)),
    (469396, (17, 469379)),
    (469398, (19, 469379)),
    (469400, (3, 469397)),
    (469402, (5, 469397)),
    (469404, (7, 469397)),
    (469406, (37, 469369)),
    (469408, (11, 469397)),
    (469410, (13, 469397)),
    (469412, (43, 469369)),
    (469414, (3, 469411)),
    (469416, (5, 469411)),
    (469418, (7, 469411)),
    (469420, (23, 469397)),
    (469422, (11, 469411)),
    (469424, (13, 469411)),
    (469426, (29, 469397)),
    (469428, (17, 469411)),
    (469430, (19, 469411)),
    (469432, (3, 469429)),
    (469434, (5, 469429)),
    (469436, (7, 469429)),
    (469438, (41, 469397)),
    (469440, (11, 469429)),
    (469442, (3, 469439)),
    (469444, (5, 469439)),
    (469446, (7, 469439)),
    (469448, (19, 469429)),
    (469450, (11, 469439)),
    (469452, (13, 469439)),
    (469454, (43, 469411)),
    (469456, (17, 469439)),
    (469458, (19, 469439)),
    (469460, (3, 469457)),
    (469462, (5, 469457)),
    (469464, (7, 469457)),
    (469466, (37, 469429)),
    (469468, (11, 469457)),
    (469470, (13, 469457)),
    (469472, (43, 469429)),
    (469474, (17, 469457)),
    (469476, (19, 469457)),
    (469478, (67, 469411)),
    (469480, (23, 469457)),
    (469482, (43, 469439)),
    (469484, (73, 469411)),
    (469486, (29, 469457)),
    (469488, (31, 469457)),
    (469490, (3, 469487)),
    (469492, (5, 469487)),
    (469494, (7, 469487)),
    (469496, (67, 469429)),
    (469498, (11, 469487)),
    (469500, (13, 469487)),
    (469502, (73, 469429)),
    (469504, (3, 469501)),
    (469506, (5, 469501)),
    (469508, (7, 469501)),
    (469510, (23, 469487)),
    (469512, (11, 469501)),
    (469514, (13, 469501)),
    (469516, (29, 469487)),
    (469518, (17, 469501)),
    (469520, (19, 469501))
  ]

/-- For any row i of `table`, both entries are prime and sum to its n. -/
lemma entry_sound (i : Fin table.size) :
    ∃ p q,
      table[i].snd.fst = p ∧ table[i].snd.snd = q ∧ Nat.Prime p ∧ Nat.Prime q ∧ p + q = table[i].fst := by
  classical
  -- Enumerate the finitely many rows and discharge each by computation.
  fin_cases i <;>
    refine ⟨_, _, rfl, rfl, ?_, ?_, ?_⟩ <;>
    native_decide

/-- The first column is the expected even range (computable). -/
def table_first_col : table.map (·.fst) = evenRange nLo nHi := by
  native_decide

/-- Computable completeness for this chunk's table. -/
def completeness :
  ∀ n, Even n → nLo ≤ n → n ≤ nHi →
    ∃ i : Fin table.size, table[i].fst = n := by
  simpa using
    (completeness_by_decide
      (nLo := nLo) (nHi := nHi) (table := table)
      (h_match := table_first_col))

/-- Finite base for this sub-window, assuming completeness of the table coverage. -/
theorem base
  (completeness :
    ∀ n, Even n → nLo ≤ n → n ≤ nHi →
      ∃ i : Fin table.size, (table[i].fst) = n) :
  FiniteBaseOn nLo nHi := by
  intro n hn hna hnb
  rcases completeness n hn hna hnb with ⟨i, hmatch⟩
  have h := entry_sound i
  rcases h with ⟨p, q, rflp, rflq, hp, hq, hsum⟩
  have hmatch' : table[↑i].1 = n := by simpa using hmatch
  have hsum' : p + q = n := hsum.trans hmatch'
  simpa [GoldbachRep, hmatch] using ⟨p, ⟨hp, ⟨q, ⟨hq, hsum'⟩⟩⟩⟩

/-- Finite base for this sub-window (unconditional). -/
theorem base_verified : FiniteBaseOn nLo nHi :=
  base completeness

end

end Goldbach.FiniteBase.Chunks.Chunk046_an_verified
